### ISSUE TITLE
Error when copying from backend

### ISSUE THREAD

**Issue by agung-kargo** [antoniomika/sish#103]
Hi,

I've tried to use sish to expose my website (that also has websocket connection). The website is working fine behind the sish tunnel. However there is always error on websocket connection

```
time="2020-06-17T09:48:36Z" level=error msg="vulcand/oxy/forward/websocket: Error when copying from backend to client: websocket: close 1006 (abnormal closure): unexpected EOF"
2020/06/17 - 09:48:36 | <my-domain> | 404 |  5.374837132s |   182.30.35.121 | GET      /socket.io/?uip=182.30.35.121&EIO=3&transport=websocket

```

Any idea why is this? Without tunnel, I can access my local site without error

**Comment by antoniomika** [comment]
Hmm, that looks like a client disconnect. This is potentially related to the idle connection timeout. What's interesting though is the error wouldn't be an EOF like it is here. I'd try disabling idle timeouts for now (--idle-connection=false) and see where that gets you.

Can you include a snippet of code that I can reproduce with? The version of sish you're using as well as the flags you use to start it would also be helpful.

**Comment by agung-kargo** [comment]
Hi @antoniomika , yes it works now. Thanks a lot for the advice :+1:
