### ISSUE TITLE
How to remove authentication 

### ISSUE THREAD

**Issue by sshuvro58** [antoniomika/sish#105]
I tried to host it  in my server , I have used the following command to build 

```
docker run -itd --name builder \
--net=host antoniomika/sish:latest \
 --ssh-address=:28\
 --http-address=:8090 \
 --https-address=:444\
 --https=true \
 --https-certificate-directory=/ssl \
 --authentication-keys-directory=/pubkeys \
 --private-key-location=/keys/ssh_key \
 --bind-random-ports=false
```

The build was successful, later I tried to forward my localhost using the following command 

` ssh -R xyz.tunnel.mydoamin.net:8090:localhost:1337 xyz.tunnel.mydomain.net`

it is giving me an error Permission denied (publickey).

How can I accomplish this without any password

**Comment by antoniomika** [comment]
It looks like you need to change the port of your ssh command. You start sish on port `:28` but ssh will use port `22` by default unless you provide it. You'll likely need to add `-p 28` to your ssh command.
