### ISSUE TITLE
Is it possible to useusername and password based verification , rather than public key

### ISSUE THREAD

**Issue by sshuvro58** [antoniomika/sish#107]
I do not want to use key based verification .  Rather than I would like to use user name and key based verification system

**Comment by antoniomika** [comment]
Currently, there is only support for single password (defined by `--authentication-password`) or public keys as you've said. To limit sish's complexity, I have intentionally omitted the use of a persistent data store, so specific user/password combinations aren't currently possible.

If there is significant interest, I may consider adding support. That being said, I do not currently plan on doing so. Would be happy to accept a PR if you're interested in adding support!
