### ISSUE TITLE
Is there any way get the list all tunnels?

### ISSUE THREAD

**Issue by sshuvro58** [antoniomika/sish#108]
Is there any possible way to get a call back when a new tunnel is created or destroyed and a list of tunnel?

**Comment by antoniomika** [comment]
This is also something that is generally out of scope for this project, but you can access this data from sish's web console.

The endpoints that are used to generate `domain.com/_sish/console?x-authorization=secret` can be used to get a list of clients. The route is at `domain.com/_sish/api/clients` with the same authorization query parameter.
