### ISSUE TITLE
ssh close if I use 2> /dev/null &

### ISSUE THREAD

**Issue by usama7628674** [antoniomika/sish#11]
@sardaukar @antoniomika 
`ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -R 80:localhost:1111 ssi.sh > link.url 2> /dev/null &`

I get output in link.url file but ssh connection closed after outputting link.
SSH does not close if I use serveo.net with `2> /dev/null &`.

I want the output but at the same time ssh should not close.

**Comment by antoniomika** [comment]
Hmm, that's actually interesting. I can't seem to get the command to not suspend even when using serveo, however. I wonder if having SSH fork first and then backgrounding the task would help? A quick Google sent me to [this gist](https://gist.github.com/scy/6781836) which could be helpful with what you're looking for. Regardless, I'm going to close this issue as it doesn't seem like a root problem in sish.
