### ISSUE TITLE
Need help on Load Balancing

### ISSUE THREAD

**Issue by W3-MajorArif** [antoniomika/sish#112]
Hello Sir,

I've tried to deploy sish project on my machine under docker, and it's working fine. After that, I tried to enable load balancing. So I set all three load balancing flags to true and tried to run four containers in the docker so they can communicate with each other. Actually I'm not sure whether I'm doing correct or wrong. Could you please help me by giving some information and instruction on how I could achieve load balancing for sish project? 

THanks a lot in advance.

**Comment by antoniomika** [comment]
Hello there!

Just want to clarify first, are you using sish as the loadbalancer or are you trying to have multiple sish backends be load balanced?

Let me explain that a bit more with a diagram. This is sish acting as a loadbalancer:
![image](https://user-images.githubusercontent.com/6239308/87554565-455d1e00-c682-11ea-91a2-42fe750f0de8.png)

And this is sish behind a loadbalancer:
![image](https://user-images.githubusercontent.com/6239308/87554797-953be500-c682-11ea-8696-c7d204c15141.png)

sish only supports the first scenario currently. Clustering support (the second scenario, which is required for loadbalancing) is a feature I am interested in implementing, but requires a consistent storage mechanism to exist between the services which we do not currently use.

Gonna close this issue but feel free to ask questions here or over irc! If these diagrams don't represent what you're thinking, feel free to send me a screenshot from [here](https://draw.io)

**Comment by W3-MajorArif** [comment]
Hello Sir,

THank you for your quick response. Actually I wanted to have the second option. Though it's not implemented in current, hope soon you will come up with that feature in sish. So far a very good job man, and best of luck for the future.

THanks again.
