### ISSUE TITLE
Question: Is there a way to prevent multiple clients with DIFFERENT credentials requesting forwarding using the SAME remote port 

### ISSUE THREAD

**Issue by murat-shiftright** [antoniomika/sish#114]
In a test setup, I have a sish server that is configured to use key based authentication and TCP load balancing.

I have two ssh clients with DIFFERENT keys request forwarding using the SAME remote port.

The sish server accepts both forwarding requests and load baiances connections between them.

Is there a way to achieve the following behavior when load balancing is enabled?

  - If a client requests forwarding to a remote port for which there is already an accepted forwarding from a client using a different credential, reject the request.

  - If the credentials of the client making the new request is the same as that of the existing client, accept the request and do load balancing.

**Comment by antoniomika** [comment]
Hi @murat-shiftright!

There’s not currently a way to handle this. Main reason is sish doesn’t handle user state more than authentication. A bit curious on what the proposed use case for this would be?

**Comment by murat-shiftright** [comment]
Hi,

Thanks for the response.

The envisoned use case would be for supporting access to on-premise endpoints of multiple customers from a multi-tenant cloud based service.   Load balancing is desirable for redundant access to endpoints in a given customer's on-premise network.   The concern is if by mistake ssh clients associated with two different customers requested forwarding from the same remote port on the sish server running in the cloud.

Of course, one can use different sish servers for different customers but that would not be efficient.
