### ISSUE TITLE
Idea: allow users/ keys to be restricted to certain sub-domains

### ISSUE THREAD

**Issue by gucki** [antoniomika/sish#116]
For our use case we have to create a subdomain for each user. It'd be great if it'd be possible to limit a ssh key to one/ multiple sub-domains, so one user cannot use the subdomain of another user.

**Comment by antoniomika** [comment]
Hey @gucki!

This is actually possible using DNS txt records for each sub domain that corresponds to a user’s ssh keys. Here’s some relevant documentation:

https://github.com/antoniomika/sish#custom-domains
