### ISSUE TITLE
Can't deploy the project to elastic-beanstalk

### ISSUE THREAD

**Issue by W3-MajorArif** [antoniomika/sish#117]
Hello Sir,

I've tried to deploy the project to Amazon elastic beanstalk. For this purpose, I've created a Dockerrun.aws.json file and tried to run **eb deploy**, but it failed with an unknown error.
My Dockerrun.aws.json file contains
{
  "AWSEBDockerrunVersion": 1,
  "volumes": [
    {
      "name": "tunnel-app-ssl-vol",
      "host": {
        "sourcePath": "/var/app/current/deploy/ssl"
      }
    },
    {
      "name": "tunnel-app-keys-vol",
      "host": {
        "sourcePath": "/var/app/current/deploy/keys"
      }
    },
    {
      "name": "tunnel-app-pubkeys-vol",
      "host": {
        "sourcePath": "/var/app/current/deploy/pubkeys"
      }
    }
  ],
  "containerDefinitions": [
    {
      "name": "sish_rsa-1",
      "essential": true,
      "memory": 1024,
      "mountPoints": [
        {
          "sourceVolume": "tunnel-app-ssl-vol",
          "containerPath": "/deploy/ssl"
        },
        {
          "sourceVolume": "tunnel-app-keys-vol",
          "containerPath": "/deploy/keys"
        },
        {
          "sourceVolume": "tunnel-app-pubkeys-vol",
          "containerPath": "/deploy/pubkeys"
        }
      ],
      "network_mode": "host",
      "command" : ["--ssh-address=:22", "--http-address=:80", "--https-address=:443"]
    }
  ]
}

Not sure where did I do a mistake, Could you please help me on this?

THanks in advance.

**Comment by antoniomika** [comment]
Hi @W3-MajorArif,

I think this might be related to the network mode for the container. I’m not super familiar with elastic beanstalk, so I could be wrong, but I’m not sure how they could support host network mode containers.

Hope that helps.
