### ISSUE TITLE
ssh.client.ListenTCP hangs

### ISSUE THREAD

**Issue by JustinGrote** [antoniomika/sish#118]
Awesome app, thanks for the work.

I'm trying to write a golang client that uses this relay to establish a remote port forward, and when I try to start a port listener from a tcpclient with client.Listen or client.ListenTCP, the client blocks. If I do it against an openssh server, it works fine. Using `ssh.exe -R`  against the SISH server also works fine.

I tried connecting to the port to see if it continues it but it stays blocked, so I think something is wrong here (maybe a confirmation message not coming back correctly)?

## Steps to reproduce
```go
	cfg := &ssh.ClientConfig{
		User: "test",
		Auth: []ssh.AuthMethod{
			ssh.Password("test"),
		},
		HostKeyCallback: ssh.InsecureIgnoreHostKey(),
	}
	client, err := ssh.Dial("tcp", "mytestserver:2222", cfg)

	listenAddress := &net.TCPAddr{
		IP:   net.ParseIP("127.0.0.1"),
		Port: 40022,
	}
	l, err := client.ListenTCP(listenAddress) //It hangs here but proceeds fine against a openssh server. No message on the server
```

**Comment by JustinGrote** [comment]
I found the problem in that sish never sends a global success reply, only failure replies, to the first tcp forward request. Openssh doesn't seem to care for whatever reason but the RFC says that message must come back and that's why these other apps hang.

In requests.go, right before `sshConn.SendMessage(mainRequestMessages, false)`, a `newRequest.Reply(true, nil)` should be added. @antoniomika want me to PR?

**Comment by antoniomika** [comment]
Of course! Thanks for taking a look at this, I appreciate your help!
