### ISSUE TITLE
Use 443 as ssh port. 

### ISSUE THREAD

**Issue by leiserfg** [antoniomika/sish#12]
Is possible to add  443 as an alternative port for people without 22 port access (like in public WIFI)?

**Comment by leiserfg** [comment]
Another way I was thinking was using port 80 for ssh and in the case of receiving a request with an HTTP protocol (that will make the ssh connection fail), then hide the socket error and send a redirect to 443 response by that socket.

**Comment by antoniomika** [comment]
This is a bit out of scope for this project as this has been solved elsewhere (see [yrutschle's sslh project](https://github.com/yrutschle/sslh), which multiplexes multiple protocols over one port). I definitely wouldn't mind if someone wanted to add this functionality to sish, but I think this problem has already been solved.
