### ISSUE TITLE
A Google Compute Engine setup guide

### ISSUE THREAD

**Issue by lmarianski** [antoniomika/sish#121]
Hi, i've been trying to set this up on a GCE f1-micro vm, but i'm not quite sure how to go about that (I did try a few things in the dashboard thing, and i have been able to get it to start and bind to a port, but now i have issues configuring it, exposing the ssh server etc.), and I haven't been able to find any tutorials that use GCE, i'll probably be able to figure it out after staring at the documentation for a bit longer but a easy straight forward guide specifically with sish in mind would be nice :)

Thanks!

**Comment by antoniomika** [comment]
Hello!

I like this idea and I have been thinking of creating either simple guides to get an instance up and running with sish, or images that are prebuilt with sish use in mind. Not sure when I'll have time to work on this though.

Best,

**Comment by antoniomika** [comment]
Deploying to heroku isn't currently possible sadly! Mainly because sish listens on a TCP service and last I checked you can't do that with heroku.

**Comment by neo** [comment]
I spent more than an hour to try with gcloud and couldn't get it working either... So it would be really great if we have this 😆

**Comment by antoniomika** [comment]
Hi there! Could you describe the issues you're having a little bit? I plan on spending some time on this in the coming weeks!

**Comment by neo** [comment]
Many in fact, I first tried using it's image feature to try to run it directly when creating a new vm instance, which didn't work... And then I tried to do it manually (with my own ssh keys but without specifying the ssh private key) and it refuses my ssh connections. I then went to firewall and realized the default firewall rule only allows port 22, so I added my own rule allowing 2222, but still no luck yet...

**Comment by neo** [comment]
So would be great to have a guide to work with the image directly when creating a vm 😆 
Also am wondering if it's possible to use a root domain rather than a subdomain for this...

Thank you a lot!!

**Comment by antoniomika** [comment]
Yep, GCP has a bunch of different features so it definitely is difficult to make sure everything is setup properly so I'll take a look! sish does support routing to a domain root instead of a subdomain, just take a look at the CLI flags!

**Comment by neo** [comment]
I thought so, and I did go through the flags; but maybe it wasn't obvious enough to me which one is the flag I want...
Anyway, I might be able to figure it out myself if I have gcp set up to begin with 😂 so I think the guide would be what we need.

Many thanks!

**Comment by neo** [comment]
Hi! Just trying to resurface this in a friendly and gentle manner 😁

**Comment by lahma0** [comment]
I am working on setting up sish in a Google Compute Engine f1 micro instance (debian) right now. If I manage to get things setup properly, I'll return here and provide any tips or answers I can.

**Comment by antoniomika** [comment]
Hey everyone, I've put together something [here](https://github.com/antoniomika/sish#google-cloud-platform). Sorry about the delay, I've been dealing with a loss in the family and have been quite busy lately. I'm going to close this issue, but any comments or recommendations to update the tutorial would be helpful if you could leave them in this issue.
