### ISSUE TITLE
I just wanna use only ssh forwarding with aliases

### ISSUE THREAD

**Issue by advancel** [antoniomika/sish#124]
Hello,
Well i think its clear.
as you seen on title. how can i use sish for only ssh forwarding.
Cuz i couldn't find it how to do.
First of all i have a server on amazon and i don't have any domain for it(don't needed).
I installed serveo and using it but serveo gives only 3 devices for tunneling. 
How can i forward my devices only ssh terminals via sish through my server.
Thx for now

**Comment by antoniomika** [comment]
Hey there,

I’ve actually detailed this in the readme. Here’s a direct link: https://github.com/antoniomika/sish#tcp-alias-forwarding
 
I’m also happy to explain it more over IRC
