### ISSUE TITLE
Difficulty In Setup On Windows OS!

### ISSUE THREAD

**Issue by Xeek3y** [antoniomika/sish#125]
Hello i'm having difficulty with this script on windows. There's no manual and tutorial for this script in windows. i tried running the exe file with cmd and all i get this error: https://i.imgur.com/An4I6C0.png

What i tried:
>Tried generating a pulic ssh key with `ssh-keygen` command
>Then created a dir and sub dir `deploy/pubkeys` within sish folder and copy pasted that rsa public key in it.
>But i'm still getting the error: https://i.imgur.com/An4I6C0.png

**Comment by antoniomika** [comment]
Hmm, there is also another directory that needs to be created `keys`. I just noticed that windows zips aren't including the deploy directory which setups up the filesystem hierarchy.
