### ISSUE TITLE
TLS / SNI support

### ISSUE THREAD

**Issue by regbo** [antoniomika/sish#126]
First of all, great project. Very simple and straight forward.

I'm wondering, is there a way to enable TLS for tcp connections?

We currently use HAProxy to do TLS termination for products that support encryption but don't use http. EX: rabbitmq, various databases

What would be even better, is using SNI to route traffic to sub domains. For example: -R foo:5555: localhost:5555 could create a TLS tunnel ://foo.domain.tld:5555 that could exist alongside a TLS tunnel to ://bar.domain.tld:5555.

Is that currently possible or is support planned in the future?

**Comment by antoniomika** [comment]
This isn't currently planned, but I don't see why it would be super difficult to do. I think this is a cool feature to add!
