### ISSUE TITLE
TCP alias forwarding not working

### ISSUE THREAD

**Issue by blop** [antoniomika/sish#129]
With the example from the README : 
`ssh -R mylaptop:22:localhost:22 sishserverhostname`

I get : 
`Starting SSH Forwarding service for tcp:22. Forwarded connections can be accessed via the following methods:
HTTP: http://mylaptop.sishserverhostname
HTTPS: https://mylaptop.sishserverhostname
`

Not sure why it list HTTP(S) URLs ?!

When trying to use the tunnel : 
`ssh -J sishserverhostname mylaptop
Connection to sishserverhostname closed by remote host.
kex_exchange_identification: Connection closed by remote host
`

It looks like something is broken.
I'm using version 1.0.10.

**Comment by antoniomika** [comment]
Have you enabled tcp aliasing? A quick tell is the fact that it mentions `tcp:22` and spits out http(s) addressing. 

Try adding `--tcp-aliases` to your sish startup command.

**Comment by blop** [comment]
Indeed, didn't see it was something that needed to be enabled ;-)
Thanks!

**Comment by blop** [comment]
The error message could be a bit more explicit though ;-)
