### ISSUE TITLE
HTTP(S) forward to a local HTTPS server not working

### ISSUE THREAD

**Issue by blop** [antoniomika/sish#130]
`ssh -R foo:443:localhost:443 sishserverhostname`

`Starting SSH Forwarding service for https:443. Forwarded connections can be accessed via the following methods:
HTTP: http://foo.sishserverhostname
HTTPS: https://foo.sishserverhostname`

`curl -v http://foo.sishserverhostname`
> GET / HTTP/1.1
> Host: foo.sishserverhostname
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Date: Thu, 17 Sep 2020 13:49:16 GMT
< Content-Length: 21
< Content-Type: text/plain; charset=utf-8
`

Same for https.

Also when trying with :
`ssh -R foo:80:localhost:443 sishserverhostname`
I get a `Bad Gateway` error.

If both http and https are always configured, I think providing either 80 or 443 in the client should result in the same configuration and behaviour, regardless of whether the target server is http or https itself.

**Comment by antoniomika** [comment]
Hmm, not sure where that ISE is coming from. Could you include the logs from sish?

**Comment by blop** [comment]
I get only this in the logs :
`2020/09/24 - 11:19:42 | foo.bar.com | 502 |   27.229524ms |    62.4.131.103 | GET      /
`
When mapping on 80, and same with 500 ISE when mapping on 443.

**Comment by blop** [comment]
With debug enabled (80/BG) :
`time="2020-09-24T11:36:48Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.64.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"foo.bar.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"62.4.131.103:14096\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2020-09-24T11:36:48Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" ForwardURL="http://L3RtcC82Mi40LjEzMS4xMDM6MTY2MTI6ODA3NDkwOTE4MTg=" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.64.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"foo.bar.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"62.4.131.103:14096\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2020-09-24T11:36:48Z" level=debug msg="vulcand/oxy/forward: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"L3RtcC82Mi40LjEzMS4xMDM6MTY2MTI6ODA3NDkwOTE4MTg=\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.64.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"foo.bar.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"62.4.131.103:14096\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2020-09-24T11:36:48Z" level=debug msg="vulcand/oxy/forward/http: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"L3RtcC82Mi40LjEzMS4xMDM6MTY2MTI6ODA3NDkwOTE4MTg=\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.64.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"foo.bar.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"62.4.131.103:14096\",\"RequestURI\":\"/\",\"TLS\":null}"
2020/09/24 - 11:36:48 | Error copying to reader: read unix /tmp/62.4.131.103:16612:80749091818->@: use of closed network connection
time="2020-09-24T11:36:48Z" level=debug msg="'502 Bad Gateway' caused by: EOF"
time="2020-09-24T11:36:48Z" level=debug msg="vulcand/oxy/forward/http: Round trip: http://L3RtcC82Mi40LjEzMS4xMDM6MTY2MTI6ODA3NDkwOTE4MTg=, code: 502, Length: 11, duration: 31.926575ms tls:version: 303, tls:resume:false, tls:csuite:c030, tls:server:foo.bar.com"
time="2020-09-24T11:36:48Z" level=debug msg="vulcand/oxy/forward/http: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"L3RtcC82Mi40LjEzMS4xMDM6MTY2MTI6ODA3NDkwOTE4MTg=\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.64.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"foo.bar.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"62.4.131.103:14096\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2020-09-24T11:36:48Z" level=debug msg="vulcand/oxy/forward: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"L3RtcC82Mi40LjEzMS4xMDM6MTY2MTI6ODA3NDkwOTE4MTg=\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.64.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"foo.bar.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"62.4.131.103:14096\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2020-09-24T11:36:48Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.64.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"foo.bar.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"62.4.131.103:14096\",\"RequestURI\":\"/\",\"TLS\":null}"
2020/09/24 - 11:36:48 | foo.bar.com | 502 |   33.431716ms |    62.4.131.103 | GET      /
`

**Comment by blop** [comment]
With debug enabled (443/ISE) : 
`time="2020-09-24T11:38:49Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.64.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"foo.bar.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"62.4.131.103:14742\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2020-09-24T11:38:49Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" ForwardURL="https://L3RtcC82Mi40LjEzMS4xMDM6MTUyNjI6NDQzMDY2MTU3NjMz" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.64.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"foo.bar.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"62.4.131.103:14742\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2020-09-24T11:38:49Z" level=debug msg="vulcand/oxy/forward: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"L3RtcC82Mi40LjEzMS4xMDM6MTUyNjI6NDQzMDY2MTU3NjMz\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.64.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"foo.bar.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"62.4.131.103:14742\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2020-09-24T11:38:49Z" level=debug msg="vulcand/oxy/forward/http: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"L3RtcC82Mi40LjEzMS4xMDM6MTUyNjI6NDQzMDY2MTU3NjMz\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.64.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"foo.bar.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"62.4.131.103:14742\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2020-09-24T11:38:49Z" level=debug msg="'500 Internal Server Error' caused by: x509: certificate is valid for self.taktik.com, not L3RtcC82Mi40LjEzMS4xMDM6MTUyNjI6NDQzMDY2MTU3NjMz"
time="2020-09-24T11:38:49Z" level=debug msg="vulcand/oxy/forward/http: Round trip: https://L3RtcC82Mi40LjEzMS4xMDM6MTUyNjI6NDQzMDY2MTU3NjMz, code: 500, Length: 21, duration: 74.554031ms tls:version: 303, tls:resume:false, tls:csuite:c030, tls:server:foo.bar.com"
time="2020-09-24T11:38:49Z" level=debug msg="vulcand/oxy/forward/http: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"L3RtcC82Mi40LjEzMS4xMDM6MTUyNjI6NDQzMDY2MTU3NjMz\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.64.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"foo.bar.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"62.4.131.103:14742\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2020-09-24T11:38:49Z" level=debug msg="vulcand/oxy/forward: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"L3RtcC82Mi40LjEzMS4xMDM6MTUyNjI6NDQzMDY2MTU3NjMz\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.64.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"foo.bar.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"62.4.131.103:14742\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2020-09-24T11:38:49Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.64.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"foo.bar.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"62.4.131.103:14742\",\"RequestURI\":\"/\",\"TLS\":null}"
2020/09/24 - 11:38:49 | foo.bar.com | 500 |   75.023139ms |    62.4.131.103 | GET      /
`

**Comment by blop** [comment]
Seems the issue is due to the target certificate verification.
I tried with both a self signed, and a valid certificate (but that one requires SNI to get sent).

Can we tell sish to ignore local/target certificate issues?

**Comment by antoniomika** [comment]
If you’re using HTTPS, you actually need to tell sish to try connecting using HTTPS. The way you do this is change port 80 to 443 to signal using TLS.

For example, you want to use -R 443:local host:443.

If you don’t have a valid cert on the proxy side, you need to set: 

--verify-ssl                                  Verify SSL certificates made on proxied HTTP connections (default true)

To false

**Comment by blop** [comment]
Yes, the thing is, the certificate is valid, but the local https server requires SNI which is not supported.
Actualy, I'm not sure how it could be supported since you need to know the local hostname to use, I don't think it's sent to sish by the ssh client.

I'll disable the --verify-ssl because we rely on SNI everywhere ;-)

**Comment by blop** [comment]
Again, maybe sish could catch this error and give a more explicit error message ;-)

**Comment by antoniomika** [comment]
Correct, the local hostname is not sent. Therefore, it can't be supported. 

The unfortunate thing about these issues is you can't predict when they occur. For example, SSL issues could be because of certificate or because of user error. Both require the same syntax, and a user may undefine it. The same is true for tcp aliases unfortunately.

I'm happy to hear of a way to differentiate this by using the currently defined method of access though!
