### ISSUE TITLE
Error loading unmanaged certificate

### ISSUE THREAD

**Issue by vidursatija** [antoniomika/sish#131]
Hi there!

Thank you for this amazing piece of work.

I've been having a few issues with SSL
I followed the Docker Compose way and used DNSRoboCert to get the certificates and create a symlink to /ssl/<domain>.crt/key. When I started the sish container it gives me the following error:
```
Error loading unmanaged certificate: open /ssl/<domain>.crt: no such file or directory
```
There are no problems with permissions as I gave the files `0777`. 

How can I resolve this?

Thank you!

**Comment by antoniomika** [comment]
Howdy! Have you added the DNSRoboCert volumes into the sish container? The symlinks that you made need to be resolvable from within the container filesystem also!
