### ISSUE TITLE
User group permissions

### ISSUE THREAD

**Issue by blop** [antoniomika/sish#136]
It'd be nice to be able to create user groups with different set of authentication-keys.

Then we could configure each group and define what action they can perform:
- create TCP tunnel / aliases (filter allowed alias names)
- create HTTP(S) tunnel
- jump to an existing TCP alias (also could be filtered using regexp to say which aliases you can access)

This way we could allow some devices to connect to sish and expose themselves using a TCP alias, without allowing them to jump to other devices. And have another group of users that can access these.

What do you think? ;-)

**Comment by antoniomika** [comment]
I think this could be a cool feature, but I am still limited by time! 

If sish was able to pay my tuition and bills, I'd be all over it! :)
Until then, I'm marking this as a feature request.

**Comment by antoniomika** [comment]
Hey @bibo38,

I decided I'm actually gonna close this issue for now. This is a bit out of scope for the goal of sish. I have some ideas for another project this will probably fit into though, so I'll update this when I get that out.

In the meantime, you can achieve what you want with running different instances of sish with certain features disabled and then having a reverse proxy in front if needed.

**Comment by bibo38** [comment]
@antoniomika you've addressed the wrong person, it's actually @blop :smile_cat:

**Comment by antoniomika** [comment]
Whoops! I blame GitHub autocorrect for that one!
