### ISSUE TITLE
HTTPS Tunneling without re-encryption

### ISSUE THREAD

**Issue by zzaurak** [antoniomika/sish#143]
From what I understand, the HTTPS forwarding currently requires re-encryption. 
Is there a possibility to forward an HTTPS request directly to the local https port? so that only the local server has the https certificate and the server never sees any cleartext?

**Comment by antoniomika** [comment]
Hey @zzaurak!

Sish actually does this by default. It will allow the service to be accessed over both http and https without needing TLS between the local service and ssh.

**Comment by zzaurak** [comment]
Oh okay thanks for the quick reply!! So i can disable --https-ondemand-certificate and do the letsencrypt challenge response from my local webserver?

**Comment by zzaurak** [comment]
Just tried it, can get a certificate but then, while trying to connect to the https site, the sish debug shows:
2020/11/07 - 00:39:54 | http: TLS handshake error from 62.XX.XX.XX:5892: ondemand certificate retrieval is not enabled
and chrome shows: "ERR_SSL_PROTOCOL_ERROR"

**Comment by zzaurak** [comment]
So basically what I want to do is:
`ssh -p 2222 -R test:80:localhost:80 -R test:443:localhost:443 mydomain.com`
and have test.mydomain.com http/https pass through to localhost, exactly as it would be with normal sshd:
`ssh -p 22 -R 80:localhost:80 -R 443:localhost:443 mydomain.com` <- with normal sshd the local apache server is accessible through mydomain.com and can generate its own letsencrypt certificates
----
is this possible with sish? I really like all the other features so much! just want to deactivate the special http/https logic and be 'dump' as sshd again

**Comment by antoniomika** [comment]
Yes, it is possible. You just need to disable `https` or change the ports sish's https server listens on. This will make it possible to then use sish as you want.
