### ISSUE TITLE
Am I missing something obvious?

### ISSUE THREAD

**Issue by voarsh2** [antoniomika/sish#147]
My subdomain:
test.example.com (not the real one) goes to my DigitalOcean IP.

DigitalOcean is running this docker container:
```
docker run -itd --name sish   -v ~/sish/ssl:/ssl   -v ~/sish/keys:/keys   -v ~/sish/pubkeys:/pubkeys   --net=host antoniomika/sish:latest   --ssh-address=:22   --http-address=:80   --https-address=:443   --https=true   --https-certificate-directory=/ssl   --authentication-keys-directory=/pubkeys   --private-key-location=/keys/ssh_key   --bind-random-ports=false
```
My localhost... aka the actual site... did:
```
ssh -R test:80:localhost:8080 root@test.example.com
```
I logged in and got logged into the (remote) box.

Where is this proxying supposed to happen?
The address gives back nothing.
Loading locally I get an apache test page.... what am I doing wrong?

Thanks.

**Comment by antoniomika** [comment]
Hey @voarsh2,

sish implements a separate ssh server, so if you're running the sshd daemon on port 22, sish won't be able to bind the same port. Best to either change the `--ssh-address` or sshd `Port`
