### ISSUE TITLE
TCP Port forwarding set-up

### ISSUE THREAD

**Issue by CharLee674** [antoniomika/sish#148]
This isn't quite an issue and more of a support request, but I am trying to set up a TCP tunnel for a service I have set up on `localhost:8888` as a replacement for a ngrok tunnel and I am not quite sure what steps to take (did not really understand the README as I'm still somewhat new to networking). I am getting stuck when it asks for a password from my service (I can't seem to figure out what 'password' to give even after I turned the authentication option to false on my service).

So far I've tried the following:
- start my `sish` service with specific options
- set up TCP aliasing as detailed in the README

```
$ sudo ./sish --authentication=false --bind-random-subdomains=false --tcp-aliases -d myservername --append-user-to-subdomain
2020/11/30 - 12:14:19 | Starting SSH service on address: localhost:2222
```

Then when I follow the TCP aliasing steps:
```
ssh -R mypi:2222:localhost:8888 myservername.ssi.sh
pi@gpiotests.ssi.sh's password: #I don't know what this password is
```

Any help would be greatly appreciated!

**Comment by antoniomika** [comment]
Hello!

You're most of the way there. First thing you'd want to do is change the port that sish is listening on. By default, it listens to `localhost:2222` so only things on the local machine will be able to access sish. You'll likely want to change this to something other than the default ssh port also, so using something like `--ssh-address=:2222` to listen on all interfaces with port `2222`. Then, add `-p 2222` to your ssh command to change the address to ssh to.

**Comment by CharLee674** [comment]
So to check that I am understanding this correctly, I need to change `localhost:2222` (how do you do this?) so that it allows remote connections and adding the ssh-address option allows me to create a tunnel on a separate port so it doesn't interfere with my normal ssh connections. Is this correct?

**Comment by antoniomika** [comment]
Sorta, we change the localhost:2222 by setting the extra flag on the sish process. This then makes it so communications to sish don't impact your normal ssh communications.

**Comment by CharLee674** [comment]
I'm trying to use this without Docker and just wanted to make sure I'm doing this correctly as I haven't been able to get it set up.

I'm just gonna go through my current process and say how I am understanding sish so far, please correct me if I am wrong in my understanding anywhere:

I have a server running on 8888 inside machine A that I wish to expose much like I would with ngrok. I try to access it on machine B.

## First, I need to start the sish command-line server on machine A. This should be set up to listen from any interface (so I can remotely access it)
The command I run is:
```
sudo ./sish --authentication=false --bind-random-subdomains=false --tcp-aliases --append-user-to-subdomain --ssh-address=:2222
```

If I wanted to listen on a different port (ie. 2300), I would change the `ssh-address` setting to `:2300`

## Then, I need to forward the port of the server I have on 8888 to the sish server. This is done on machine A with the SSH client:
```
ssh -R 2222:localhost:8888 ssi.sh -p 2222
```

If I wanted an alias:
```
ssh -R mylaptop:2222:localhost:8888 ssi.sh
```

## On machine B, I connect to this forwarded port via:
```ssh -p 2222 ssi.sh```
or if an alias has been set up
```ssh -J ssi.sh mylaptop```

Is this correct? Thanks again for the help!

**Comment by antoniomika** [comment]
Hi @CharLee674 

Yes, this is correct, but you need to have external access on the host you are accessing sish. There isn't a publicly available endpoint sadly.
