### ISSUE TITLE
502 response received; sometimes

### ISSUE THREAD

**Issue by W3-Arman** [antoniomika/sish#149]
Thanks for sharing the repository. sometime contentious communication among 3/4 devices through a fixed sub-domain received **502 response**.
Multiple try resolved the case; any idea on that issue. As Client  I have used android devices with [JCraft](http://www.jcraft.com/jsch/)

Thanks in advance!

**Comment by antoniomika** [comment]
Hmm, interesting! Do you have a way to reproduce this? Even if curling in parallel that might be a good test?

**Comment by W3-Arman** [comment]
It's already happening in continuous requesting. And any retry mechanism for fail case is implemented there. Actually, I want to know about the core protocol on fail handling.
________________________________

**Comment by antoniomika** [comment]
Can you at least share how you've setup sish and what command you're using for `ssh`?

**Comment by W3-Arman** [comment]
Thanks for your time.
The last commits resolved most of the cases.
