### ISSUE TITLE
proxy protocol support

### ISSUE THREAD

**Issue by unixfox** [antoniomika/sish#15]
When using a TCP tunnel on sish I lost the original IP address because every request looks like they come from localhost.

The HAPROXY team developed [the PROXY protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) to resolve that issue.

Would it be possible to implement the proxy protocol into sish for TCP tunnels? This would allow the applications that are compatible with the PROXY protocol to keep the original IP address.

I gathered some resources about the proxy protocol if you are interested:
- golang library for the proxy protocol: https://github.com/pires/go-proxyproto
- another golang library for the proxy protocol : https://github.com/armon/go-proxyproto

**Comment by antoniomika** [comment]
I like the idea of adding this. Is there a way you envision enabling the proxy protocol for certain tunnels and not others? I don't want to impact users that don't have support for the proxy protocol built in.

**Comment by unixfox** [comment]
Thank you for you reply, I appreciate that you take this issue into consideration!

> Is there a way you envision enabling the proxy protocol for certain tunnels and not others? I don't want to impact users that don't have support for the proxy protocol built in

What about adding a flag in the command line that would enable the proxy protocol for TCP tunnels?

**Comment by antoniomika** [comment]
Just added this in with a3ffd2b. Should be good to go, but it will only support TCP connections, not HTTP/S connections made via the reverse proxy (just do to how that part is implemented). You can either force it enabled with a specific version for all connections or allow it to be user defined. Take a look at the documentation and try it out and let me know how it works for you!
