### ISSUE TITLE
Ssh Tcp Forwarding Identity Files

### ISSUE THREAD

**Issue by mustafayuce33** [antoniomika/sish#150]
Hi,

I am forwarding our ssh port on my `rpi3` device by the following command 

ssh -p ```<sish_server_port>``` -R 0:127.0.0.1:22 ```<sish_server_ip>``` -i ~/.ssh/sish_server_private_key

This gives me a random port; lets say ```34792```

Both our rpi3 and sish server has ```key authentication```. So I guess I need to provide private keys for both of the machines (`rpi3 `and `sish server`) to connect via rpi3 from `my computer` something like that 

ssh ```<sish_server_ip>``` -p ```34792```  -i ~/.ssh/sish_server_private_key -i ~/.ssh/rpi3_private_key

Indeed, I know there is no such arguments that we can give for ssh command as above. But I am wondering how I can connect to `rpi3 `from `my computer` by using random port (```34792```) that is opened by sish server for the `rpi3`

**Comment by antoniomika** [comment]
If you're using TCP forwarding, you shouldn't need both private keys. You should only need to provide the private key for `rpi3`. If you want to use TCP aliases (where you have to use sish to open the socket to `rpi3`), you should then use a `ProxyJump` or `ProxyCommand` and provide the two different ssh keys using an ssh config.

**Comment by mustafayuce33** [comment]
Thanks for your quick response
