### ISSUE TITLE
Redirect to another location 

### ISSUE THREAD

**Issue by thangnd85** [antoniomika/sish#152]
By default sish will redirect to root location, like domain.tld/location
How can I redirect to another location when I type domain.tld to www.domain.tld?
Many thanks

**Comment by antoniomika** [comment]
Hi @thangnd85 ,

is this using the `-r, --redirect-root-location string               The location to redirect requests to the root domain` flag? If so, you can redirect this to anywhere as it will use any url for the redirect.

**Comment by thangnd85** [comment]
Thanks for support. 
But i tried, it redirect to child
Example my domain is: domain.com
And I redirect root location to www.domain.com
Then, when i type domain.com, it redirect to domain.com/www.domain.com instead of www.domain.com
