### ISSUE TITLE
How to properly set up sish

### ISSUE THREAD

**Issue by thearsamjaved** [antoniomika/sish#153]
can you please create a beginner friendly tutorial for setting up sish. I followed all steps but at the end when i try to cmmunicate with it aks for password.

**Comment by Dalkson** [comment]
same here

**Comment by XfedeX** [comment]
I have the same issue! Using Windows 10.
I get this "error":
`C:\Users\Toshiba\Downloads\sish-1.1.4.windows-amd64>ssh -R 25565:localhost:25565 ssi.sh
toshiba@ssi.sh's password:`

**Comment by XfedeX** [comment]
@antoniomika can you help?

**Comment by antoniomika** [comment]
Sorry folks, you need to self host sish on an outside server in order to use it to forward ports. The above looks like you're attempting to use the demo service. If you read the README, it'll describe why that has been shutdown.

**Comment by antoniomika** [comment]
Here's a tutorial how to setup an instance in GCP using the free tier: https://github.com/antoniomika/sish#google-cloud-platform
