### ISSUE TITLE
certmagic certificate "no such file or directory" (docker)

### ISSUE THREAD

**Issue by tokaskakadis** [antoniomika/sish#155]
hey Antonio,
Thanks for your awesome software... 
Running few months, the docker latest image (antoniomika/sish:latest) in gcp vm with out any problem... Suddenly i received those ERROR messages below in log file....

my docker-compose volumes snippet

    volumes:
      - ./pubkeys:/pubkeys
      - ./keys:/keys
      - ./ssl:/ssl
      - ./logs:/tmp
    command: |
      --ssh-address=:2222
      --http-address=:80
      --https-address=:443
      --https=true
      --https-certificate-directory=/ssl
      --authentication-keys-directory=/pubkeys
      --private-key-location=/keys/ssh_key
      --bind-random-ports=false
      --bind-random-subdomains=false
      --domain=mydomain.com
      --authentication=true
      --log-to-file=true
      --https-ondemand-certificate
      --https-ondemand-certificate-accept-terms
      --https-ondemand-certificate-email=test@mydomain.com
      --ping-client=true

[ERROR] attempt 16: open /.local/share/certmagic/certificates/acme-v02.api.letsencrypt.org-directory/xxx.mydomain.com/xxx.mydomain.com.crt: no such file or directory - retrying in 6h0m0s (30h0m0.005212165s/720h0m0s elapsed)...

the mounted ssl folder includes the certmagic folder and all those files ...

suspecting is something  with the renewal algorithm file path ?

thanks in advance.

**Comment by antoniomika** [comment]
Hey @tokaskakadis!

Hopefully have a fix that I can get merged in once I run my smoke test! Looks like sometimes the default storage might persist so I went ahead and fixed that.
