### ISSUE TITLE
Connection closed/cannot find connection for host

### ISSUE THREAD

**Issue by lahma0** [antoniomika/sish#156]
I rarely ask for help in instances like this and usually continue to beat my head against the wall until I finally figure it out by brute force, but I humbly ask for your help in this instance as I've been trying to get this setup for 3 days now. If this is asking for "too much" help, I totally understand if you politely decline (I can relate as I spend an inordinate amount of time offering support for an open source project I run). I successfully used docker-compose to setup my container, finally got all my DNS records sorted out (A/AAAA, TXT, etc) and successfully got LetsEncrypt to issue my certs for my domain and wildcard domain, setup the appropriate TXT records to include my ssh key fingerprint, got my public ssh keys properly loaded into the container, etc and so on. 

To provide a little more info, I'm using a **Google Cloud Engine f1 micro** instance running **Debian** (I noticed you just updated the README in like the last few hours with an example for setting up this exact type of instance but it looks pretty similar to what I'm already doing so it hasn't helped much in figuring out my issues). Before building my container, I put my public key in the '**/pubkeys**' dir, placed the corresponding private key (question about this below) file at '**/keys/ssh_key**', and created the proper symlinks to my LetsEncrypt certs in '**/ssl**'. I believe I have my firewall rules setup correctly:

| Name | Type | Targets | Filters | Protocols / ports | Action | Priority | Network | Logs |
| -- | -- | --| --| -- | -- | -- | -- | -- |
| allow-all-tcp-sish | Ingress | Apply to all | IP Ranges: 0.0.0.0/0 | tcp | Allow | 1000 | default | Off |

Furthermore, the admin console at '**http(s)://my-domain.com/_sish/console?x-authorization=XXXXXXXXXXX**' is working perfectly fine (both http and https and my SSL certificate is valid). At one point, I did successfully get the command '**ssh -p 222 -R foo:80:httpbin.org:80 my-domain.com**' to work but now even that is not working for some reason (my primary problem(s) are at the end of this stupidly long post).

Here is my '**docker-compose.yml**':
<pre>
version: '3.7'

services:
  letsencrypt:
    image: adferrand/dnsrobocert:latest
    container_name: letsencrypt-dns
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/etc/letsencrypt
      - ./le-config.yml:/etc/dnsrobocert/config.yml
    restart: always
    environment:
      - TIMEZONE=America/Chicago
      - LEXICON_SLEEP_TIME=200
      - LEXICON_MAX_CHECKS=2
  sish:
    image: antoniomika/sish:latest
    container_name: sish
    depends_on:
      - letsencrypt
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./pubkeys:/pubkeys
      - ./keys:/keys
      - ./ssl:/ssl
    command: |
      --admin-console=true
      --admin-console-token=*************
      --authentication=true
      --authentication-password=""
      --bind-random-aliases=false
      --https-ondemand-certificate=true
      --https-ondemand-certificate-accept-terms=true
      --https-ondemand-certificate-email=*******@*****.***
      --log-to-file=true
      --private-key-passphrase=************
      --tcp-aliases=true
      --service-console=true
      --log-to-client=true
      --ssh-address=:222
      --http-address=:80
      --https-address=:443
      --https=true
      --https-certificate-directory=/ssl
      --authentication-keys-directory=/pubkeys
      --private-key-location=/keys/ssh_key
      --bind-random-ports=false
      --bind-random-subdomains=false
      --domain=my-domain.com
    network_mode: host
    restart: always
</pre>

### SSH Keys

1. In regards to putting your ssh key fingerprint into your domain's txt records, exactly what format should it be in? Should it be in SHA256 format (I'm guessing this one) or MD5 format? Should it be prefixed with the hashing algorithm (I'm guessing yes)? Just to be safe, I added separate TXT records with all of them just to be sure one of them was correct, but can you confirm with me which is the correct way? **I've bolded the one that I think is correct, so if I'm right, you can just tell me I was correct in my assumption.** (I've used fake domains and keys below for the purpose of demonstration.)

_The 2 TXT records in SHA256 format, one with 'SHA256' prefix, the other without:_
| Hostname               | Type        | Data                                                                                           | TTL           |
| -------------------- | --------- | ----------------------------------------------------------------- | ---------- |
| my-domain.com       | TXT        | sish=2fjlsF0345aseiIG394IRLS83sdf89nslsdfjls9DFS                     | 120          |
| **my-domain.com** | **TXT**  | **sish=SHA256:2fjlsF0345aseiIG394IRLS83sdf89nslsdfjls9DFS**  | **120**    |

_The 2 TXT records in MD5 format, one with the 'MD5' prefix, the other without:_
| Hostname           | Type  | Data                                                                             | TTL     |
| ----------------- | ----- | -------------------------------------------------------- | ------ |
| my-domain.com | TXT   | sish=76:9f:ad:1d:44:5e:4f:03:79:25:f7:bf:39:24:ff:ec          | 120    |
| my-domain.com | TXT   | sish=MD5:76:9f:ad:1d:44:5e:4f:03:79:25:f7:bf:39:24:ff:ec  | 120   |

3. Does the private key in the location denoted by '--private-key-location' (default: /keys/ssh_key) need to be the key pair of the public key placed into the location denoted by '--authentication-keys-directory' (default: /pubkeys)? In other words, it should be the same private key (and password) that I'm using to connect to sish?

### sudo docker-compose

4, Should the docker container be run (docker-compose) with sudo?

### Primary Problem(s)

Like I said before, I got the command '**ssh -p 222 -R foo:80:httpbin.org:80 my-domain.com**' to work a couple of times but even when that was working, trying to forward anything from my local machine still wasn't. For example, I started a local Python 3 web server on my machine using '**python3 -m http.server 9999**' and then tried running the command '**ssh -p 222 -R foo:80:localhost:9999 my-domain.com**' in another console without success. Here is the first error that I am seeing on almost every attempt:

Here is an example command I'm running on my local machine and its corresponding output:
<pre>
 $ ssh -p 222 -R foo:80:localhost:9999 my-domain.com
Enter passphrase for key '/home/*****/.ssh/id_ed25519':
Connection closed by xxx.xxx.xxx.xxx port 222
</pre>
And here is the corresponding log from sish:
<pre>
2021/02/14 - 17:40:47 | Accepted SSH connection for: xxx.xxx.xxx.xxx:56794
2021/02/14 - 17:40:47 | Login attempt: xxx.xxx.xxx.xxx:56794, user ***** key: ssh-ed25519 ***********************************************************
2021/02/14 - 17:40:52 | read tcp 10.128.0.2:222->xxx.xxx.xxx.xxx:56794: use of closed network connection
</pre>

Another common error I'm seeing in my logs is:
<pre>
Aborting with error cannot find connection for host: xxx.xxx.xxx.xxx
</pre>

I started writing this post 3 days into trying to get this to work and I'm now on my 4th day when I'm actually posting this. Any help, tips, or just some general direction to look in for resolution to this issue would be GREATLY appreciated. You've made a really awesome project here and I would really like to make use of it. Thanks!

**Comment by lahma0** [comment]
Just to further demonstrate the strangeness I'm experiencing, I just ran the following command (which didn't work):
<pre>
 $ ssh -p 222 -R foo:80:httpbin.org:80 my-domain.com
Enter passphrase for key '/home/*****/.ssh/id_ed25519':
Connection closed by 34.123.23.202 port 222
</pre>
And immediately afterwards, I ran the following command (which very surprisingly, DID work):
<pre>
 $ ssh -p 222 -R tst:80:httpbin.org:80 my-domain.com
Press Ctrl-C to close the session.

Starting SSH Forwarding service for http:80. Forwarded connections can be accessed via the following methods:
Service console can be accessed here: https://tst.my-domain.com/_sish/console?x-authorization=***********
HTTP: http://tst.my-domain.com
HTTPS: https://tst.my-domain.com

2021/02/14 - 18:23:33 | tst.my-domain.com | 200 |  390.824639ms |    xxx.xxx.xxx.xxx | GET      /anything
</pre>

So, literally just changing the subdomain letters from 'foo' to 'tst' made the command work... WTF? Here are my sish logs for both of those commands (btw, I don't know what the '146.88.240.17' IP address is... maybe a CDN or something?):
<pre>
2021/02/14 - 18:19:38 | Starting SSH service on address: :222
2021/02/14 - 18:19:38 | [INFO][cache:0xc0000610e0] Started certificate maintenance routine
2021/02/14 - 18:20:36 | Accepted SSH connection for: xxx.xxx.xxx.xxx:56818
2021/02/14 - 18:20:36 | http: TLS handshake error from 146.88.240.17:49918: cannot find connection for host: 10.128.0.2
2021/02/14 - 18:20:41 | read tcp 10.128.0.2:222->xxx.xxx.xxx.xxx:56818: use of closed network connection
2021/02/14 - 18:23:00 | Accepted SSH connection for: xxx.xxx.xxx.xxx:56820
2021/02/14 - 18:23:01 | HTTP forwarding started: http://tst.my-domain.com -> /tmp/xxx.xxx.xxx.xxx:56820:80287386462 for client: xxx.xxx.xxx.xxx:56820
2021/02/14 - 18:23:01 | HTTPS forwarding started: https://tst.my-domain.com -> /tmp/xxx.xxx.xxx.xxx:56820:80287386462 for client: xxx.xxx.xxx.xxx:56820
2021/02/14 - 18:23:33 | tst.my-domain.com | 200 |  390.824639ms |    xxx.xxx.xxx.xxx | GET      /anything
</pre>

**Comment by lahma0** [comment]
FYI, on the last comment I made, I had actually turned off authentication prior to that for testing. After posting that, for the 1st time, I was able to get forwarding working to a local python web server I had running. However, after turning authentication back on, regardless of what I changed the subdomain to, or what local port the local web server was running on, I am not able to get it to work again. I just keep getting the "Connection closed" error. Same thing with trying to forward to 'httpbin.org'.. regardless of the subdomain. Looks like some issue with authentication but I literally have zero clues on what else I can try...

**Comment by antoniomika** [comment]
Hey @lahma0!

I'm more than happy to help. I appreciate you digging into this first and giving me a lot of info on what's going on. Honestly, your issue is an OSS developer's dream as it made it really easy to figure out what's going on.

For the main issue of the `Connection closed` with authentication turned on, this is likely due to the time it takes to enter the private key passphrase being longer than the idle timeout that sish uses to request SSH connections fast (this feature is because bots like to sticky connect SSH connections which is honestly very annoying). This is controlled by the `cleanup-unbound` flags:

```
      --cleanup-unbound                             Cleanup unbound (unforwarded) SSH connections after a set timeout (default true)
      --cleanup-unbound-timeout duration            Duration to wait before cleaning up an unbound (unforwarded) connection (default 5s)
```

You may either choose to disable cleaning up unbound connections, but this means if clients never pass auth they will stay connected to sish. Instead, I'd suggest increasing the timeout from 5s to 1m or 2m which gives ample time for connection.

For the error regarding 

```
Aborting with error cannot find connection for host: xxx.xxx.xxx.xxx
```

This is another common issue made by bots/hard coded clients when they make requests to sish prior to a connection being forwarded. Any HTTP request that comes in, sish will attempt to look up the host in its internal routing table, but if it doesn't find it because the forwarded connection doesn't exist, this error will occur ([source here if you're curious](https://github.com/antoniomika/sish/blob/52fb3937a33a86ce759afaa1d8e2ae71082fbdc9/httpmuxer/httpmuxer.go#L127)).

Regarding SSH keys, you are correct that it should be in base64 encoded sha256 format (the one below), more info on that is [here](https://github.com/antoniomika/sish#custom-domains) which includes what to do if you want to allow any custom domain without authentication. I'll leave this issue open until you're satisfied with closing it.

Hostname | Type | Data | TTL
-- | -- | -- | --
my-domain.com | TXT | sish=SHA256:2fjlsF0345aseiIG394IRLS83sdf89nslsdfjls9DFS | 120

For

```
Does the private key in the location denoted by '--private-key-location' (default: /keys/ssh_key) need to be the key pair of the public key placed into the location denoted by '--authentication-keys-directory' (default: /pubkeys)? In other words, it should be the same private key (and password) that I'm using to connect to sish?
```

The `private-key-location` is actually the private key for the [host SSH key](https://github.com/antoniomika/sish/blob/a147db64bcec1cbf3ad95dfa931927d2b0761cab/utils/utils.go#L337). sish can create this for you or you can bring it yourself if your SSH client's have a specific requirement for it. Only the sish server should have access to this private key and it doesn't have to have a corresponding public key for it anywhere, and it shouldn't be the same private key (and pass) that you're using to connect to sish. To connect to sish, you should take the public key from your local machine and place it into a file in the `--authentication-keys-directory` similar to how you would with an ssh `authorized_keys` file.

I hope this all helps with getting things setup. I want to thank you again for the kind words and I appreciate your level of detail here. If you need anymore help, don't hesitate to reach out here or jump onto [freenode IRC](https://github.com/antoniomika/sish#notes).

**Comment by lahma0** [comment]
Wow, you're a quick one! I didn't even check back here to see if you had responded until just now as I thought it would surely take you a couple of days to get back to me. Thank you SO much for answering my questions so quickly. I will try all the things you suggested and return here with the outcome. I'll probably join your IRC channel too just to say hello. I suspect you're a bit closer to my age if you're still using IRC :) All these darn kids using Discord these days... Ha, anyways, thanks again man. I appreciate you leaving the issue open and I will most certainly close it when I'm sure the issue is resolved.

**Comment by lahma0** [comment]
Wohoo! It looks like it is working! All down to that one little switch (--cleanup-unbound-timeout)! I'm going to do some more testing over the next day or so before I close out the issue but I just wanted to say thanks for your help. Oh, one more question.. Can you immediately reuse the same subdomain again? Like say I start forwarding use 'test.my-domain.com' and then stop that forwarding session. Can I immediately reopen another forwarding session using that same subdomain (test.my-domain.com)?

**Comment by antoniomika** [comment]
Awesome! Glad it's all working! You should be able to start using the same subdomain immediately after disconnecting (might take a little bit of time as listeners are cleaned up). If you're unable to, it also could be that sish still believes the SSH client is connected. This is usually cleaned up by the idle connection manager that detects when the connection has died, so it can take however long `idle-connection-timeout` is set to before it becomes available.

**Comment by lahma0** [comment]
Sorry I haven't closed the issue yet. I live in Texas and we've been having record cold weather/snow and our power has been out for over 3 days. The power is back on now though and hopefully it stays on. As a result of not having power, I haven't had a chance to do all the testing I wanted to do before closing out this issue. If you don't mind, I'm going to test things a bit further over the next couple of days and then I will close out the issue.

**Comment by lahma0** [comment]
Thanks again for all your help! I'm sure I will be back with other questions (or I may just join your IRC channel).

**Comment by antoniomika** [comment]
You're good, and no problem at all! I hope you and your family has been safe in this difficult time!
