### ISSUE TITLE
how to use without Docker

### ISSUE THREAD

**Issue by gvsurenderreddy** [antoniomika/sish#16]
Hello sir 
How can i use this application without Docker on ubuntu please.Is there any init.d script too.How many  tunnels at a time can be used sir.

**Comment by antoniomika** [comment]
`sish` is fairly lightweight, so any number of tunnels can be used as long as resources are permitted. Without docker, you need to build the project manually with the go toolchain. There aren't any prebuilt binaries, but I can look at potentially creating them through CI. As for the init.d script, you're mainly on your own. Here's some decent [documentation on this](https://bash.cyberciti.biz/guide//etc/init.d). Note that you can use systemd with most recent linux distros.

**Comment by gvsurenderreddy** [comment]
Thank you so much.I have build successfully
