### ISSUE TITLE
Listing tunnels

### ISSUE THREAD

**Issue by capriciousduck** [antoniomika/sish#162]
How do I know how many tunnels are presently connected to sish?

**Comment by antoniomika** [comment]
You can check by either enabling the main admin console (which prints users as well as their tunnels) or enabling debug mode which will print the number of tunnels to stdout.

**Comment by capriciousduck** [comment]
I enabled admin console, but I am getting a 404 error. Here is my docker command.

`docker run -itd --name sish --restart unless-stopped \
  -v /mnt/sysdisk/sish/ssl:/ssl \
  -v /mnt/sysdisk/sish/keys:/keys \
  -v /mnt/sysdisk/sish/pubkeys:/pubkeys \
  --net=host antoniomika/sish:latest \
  --ssh-address=:2222 \
  --http-address=:80 \
  --https-address=:443 \
  --https=false \
  --https-certificate-directory=/ssl \
  --authentication-keys-directory=/pubkeys \
  --private-key-location=/keys/ssh_key \
  --bind-random-ports=false \
  --authentication-password=mypassword \
  --bind-random-subdomains=false \
  --domain=sish.capriciousduck.tech \
  --idle-connection=false \
  --admin-console=true \
  --admin-console-token=mytoken`

**Comment by antoniomika** [comment]
What's the URL you are using to connect to sish?

**Comment by capriciousduck** [comment]
sish.capriciousduck.tech

**Comment by antoniomika** [comment]
Ahh I see! My bad, I should've probably highlighted that more in the README. The documentation is in the flag though:

```
      --admin-console                               Enable the admin console accessible at http(s)://domain/_sish/console?x-authorization=admin-console-token
```

The route to the admin console is /_sish/console?x-authorization=password.

Hope this helps!

**Comment by capriciousduck** [comment]
Great! Now it is working!
