### ISSUE TITLE
Timeout of a requested domain or tcp port

### ISSUE THREAD

**Issue by capriciousduck** [antoniomika/sish#164]
Hi. If I create a port 80 forwarded subdomain or tcp address and then stop the session. After few seconds if If I create the tunnel using the same port or subdomain, then will I'll be assigned the same port or subdomain or something else?

**Comment by antoniomika** [comment]
You should be assigned the same domain but this all depends on how timeouts are handled. The readme outlines specifics on ping client interval and idle timings.
