### ISSUE TITLE
Allow binding the Root/Base domain

### ISSUE THREAD

**Issue by bibo38** [antoniomika/sish#166]
Add the feature to allow binding the base domain (probably behind a flag).

Example
------------
`ssh -R :80:localhost:8080 ssi.sh` should proxy `http://localhost:8080/` to `http://ssi.sh/`

Why?
-------
Basically because i usually only need one connection, it is shorter to drop the subdomain.

**Comment by antoniomika** [comment]
This should be easy enough to do. I see this implemented with:

1. Command flag to allow for the root to be bound, also allowed if any host is allowed to be bound
2. Modify the hostname generator to allow empty strings and use as the root
3. Update the reverse proxy module to check for the root before redirect

This can be done by using the root as a empty string or creating the full domain to load into the routing map
