### ISSUE TITLE
Allow binding of paths

### ISSUE THREAD

**Issue by bibo38** [antoniomika/sish#167]
Why?
-------
Mainly to provide an alternative way without the need for an Wildcard SSL certificate (as it's harder to automatically obtain via LE and dynamic certs may be problematic to use with an Reverse Proxy before sish).

Design Idea
-----------------
`ssh -R foo/bar:443:localhost:8080 ssi.sh` should proxy `https://foo.ssi.sh/bar/*` to `http://localhost:8080/*`. Also this doesn't prevent anything, as using `/` in the subdomain is not really practical (as it breaks the URL).

**Comment by antoniomika** [comment]
I like this idea too. I think it'd be confusing to use a `/` to separate the subdomain and path. Do you know of another symbol that would be easier to use? For example, `@` isn't traditionally used inside of URLs other than to signify basic auth creds, therefore, we could signify the domain as `ssh -R this/is/path@subdomain:443:localhost:8080 ssi.sh` or something like that?

**Comment by bibo38** [comment]
I don't mind using the `@`. My main goal is that this doesn't break existing usages by using some char that doesn't practically work in a subdomain. In combination with #166 it may look a bit awkward to use `bar@:443:localhost:8080` (vs `/bar:443:localhost:8080`), which is my practical usage (just one domain with paths to eliminate the wildcard need).

**Comment by antoniomika** [comment]
@bibo38 true, but I just realized you can already set the same domain. All you need to do is:
1. Set `--redirect-root` to false so that requests to the root domain aren't redirected
2. Use `--bind-any-host` or setup the TXT record for the domain to allow it to be bound
3. Provide the root domain entirely `ssh -R ssi.sh:80:localhost:8080 ssi.sh`
So if we leave it explicitly defined rather than empty is evaluated as the root, then the `@` wouldn't look weird.

**Comment by bibo38** [comment]
When providing the root domain entirely, the `/` option get's even better (`bar@ssi.sh:443:localhost:8080` vs `ssi.sh/bar:443:localhost:8080`) :smirk: . I don't mind the awkward look that i mentioned in my last comment, but I do want to have the ability to omit the domain name (less typing), so supporting `bar@:443:localhost:8080` would be fine for me.

**Comment by bibo38** [comment]
Quick idea: Maybe we can support both symbols/ideas (i've omit the `:443:localhost:8080` trailer):

- `/bar` goes to `ssi.sh/bar`, for consistency this also works on nested paths (`/this/is/path` -> `ssi.sh/this/is/path`)
- For subdomains you add the `@`. E.g. `/this/is/path@foo` -> `foo.ssi.sh/this/is/path`
- Explicit domain can be done both ways, so `foo.ssi.sh/this/is/path` and `/this/is/path@foo.ssi.sh` are equivalent and point to `foo.ssi.sh/this/is/path`

The explicit `/` prefix indicates that you specify a path and not a subdomain and is mandatory. So `this/is/path:443:localhost:8080` will be handled as it currently works (returning the unusable url `https://this/is/path.ssi.sh`).

**Comment by blop** [comment]
Could you also support a way to create a TCP alias tunnel for a 80/443 port ?

Currently if we choose the port defined for either http or https will create a HTTP(S) tunnel and use the alias part as subdomain.

It could be useful to have some syntax to allow explicit TCP aliasing, especially if you introduce some advanced alias syntax features like paths.

**Comment by bibo38** [comment]
@antoniomika what design of paths was now implemented? A quick look at 03a634e0fafbef42613f31de6da8a139671d9cc1 doesn't reveal it to me, as it seems to be mixed with authentication handling.

**Comment by antoniomika** [comment]
@bibo38 pretty much above as we discussed. Here's a full forward example:

Forward username:password@test.ssi.sh/this/is/a/path -> localhost:8080 and rewrite the host header to google.com
ssh -R username\\:password@test/this/is/a/path:80:localhost:8080 ssi.sh host-header=google.com

You can also disable stripping the path on the proxy (the full path is sent to the service) by calling the above with strip-path=false

**Comment by bibo38** [comment]
thanks, i think the username/password thing is new (atleast for this issue), but now I understand why the commit mixed in authentication.
