### ISSUE TITLE
own subdomain instead of relying on a randomly  -sish.bindrandom option to false

### ISSUE THREAD

**Issue by gvsurenderreddy** [antoniomika/sish#17]
Hello 
-sish.bindrandom = flase is not the correct one as in Readme sish.bindrandom", true, "Bind ports randomly (OS chooses)"

own subdomain Correct -sish.forcerandomsubdomain =false (Whether or not to force a random subdomain)

Thank you for the excellent project.Thanks again

**Comment by antoniomika** [comment]
I'm not sure what you mean here. The bind random flag refers to random port binding vs force random subdomain refers to ensuring subdomain are randomly set. The docker compose example in the readme is intentionally disallowing public port and subdomain binding to prevent abuse for the demo instance.

**Comment by gvsurenderreddy** [comment]
choose your own subdomain instead of relying on a randomly for this to work 
-sish.forcerandomsubdomain =false on then we can use our own subdomain i mean sir

**Comment by antoniomika** [comment]
Correct, if you set `-sish.forcerandomsubdomain=false`, you will be able to select your own subdomain
