### ISSUE TITLE
Authentication Issues

### ISSUE THREAD

**Issue by Previesam** [antoniomika/sish#170]
Please do you have an idea why I am getting this error?

previesam@ssi.sh's password: 

Not an error but I am been asked for a password and I have no idea what to enter as the password.

Here is the command `ssh -R doaco:80:localhost:2222 ssi.sh`

**Comment by edorgeville** [comment]
See README: https://github.com/antoniomika/sish#demo---at-this-time-the-demo-instance-has-been-set-to-require-auth-due-to-abuse

**Comment by antoniomika** [comment]
Thanks @edorgeville! I'm going to remove that from the README now.
