### ISSUE TITLE
Cannot use root domain port

### ISSUE THREAD

**Issue by sonntuet1997** [antoniomika/sish#172]
I cannot use the root domain port for my website, is there a way I can bind it with another port or disable it if possible ?

**Comment by antoniomika** [comment]
@sonntuet1997 could you provide a bit more context here? I'm sorry but I don't think I'm following very clearly.

**Comment by lahma0** [comment]
My guess is that he still wants his domain (ex: mydomain.com) to point to his website/webserver and only use subdomains with sish (ex: home.mydomain.com). I suspect this comes down to DNS configuration/provider settings but obviously you're better suited to answer this than me.

**Comment by antoniomika** [comment]
@lahma0 I think you're probably right. I'm gonna close this while we get more context from @sonntuet1997.
