### ISSUE TITLE
Password Auth Bypass

### ISSUE THREAD

**Issue by capriciousduck** [antoniomika/sish#173]
I have setup sish with password as authentication method. When I create a new tunnel on a new machine it doesn't ask for password.

Here is my docker command:

docker run -itd --name sish --restart unless-stopped \
  -v /mnt/mclaren/sish/ssl:/ssl \
  -v /mnt/mclaren/sish/keys:/keys \
  -v /mnt/mclaren/sish/pubkeys:/pubkeys \
  --net=host antoniomika/sish:latest \
  --ssh-address=:2222 \
  --http-address=:80 \
  --https-address=:443 \
  --https=false \
  --https-certificate-directory=/ssl \
  --authentication-keys-directory=/pubkeys \
  --private-key-location=/keys/ssh_key \
  --bind-random-ports=false \
  --authentication-password=mypassword \
  --bind-random-subdomains=false \
  --domain=mydomain.tech \
  --idle-connection=false \
  --admin-console=true \
  --cleanup-unbound=true \
  --cleanup-unbound-timeout=1s \
  --admin-console-token=mypasstoken

**Comment by antoniomika** [comment]
@capriciousduck please read the documentation. You need to set `--authentication=true`. I'm going to close this in favor of #168 where we will enable auth by default.
