### ISSUE TITLE
Request auto close the ssh client if the requested domain is unavailable.

### ISSUE THREAD

**Issue by sonntuet1997** [antoniomika/sish#174]
![image](https://user-images.githubusercontent.com/33181397/122503613-fa325480-d022-11eb-9899-954a8029d458.png)
I use Docker to run the tunnel but when the requested domain is unavailable it cannot auto restart because the ssh didn't auto close. Please add this feature!

**Comment by antoniomika** [comment]
Hi @sonntuet1997

So is port 8080 a previously bound tunnel? There's some funky logic to handle tunnel cleanup that you might need to verify you flags for. Could you post the flags you're using?

**Comment by sonntuet1997** [comment]
Here it is![58F20B51-EA86-4534-A7B3-0483EAFBE70F](https://user-images.githubusercontent.com/33181397/123531890-7cf99480-d732-11eb-9d7f-264bd5e952ea.png)

**Comment by antoniomika** [comment]
Hey @sonntuet1997

Following up on your PR here so we can have more of a discussion. Maybe we add a flag to the ssh command that tells sish to close the connection when there are 0 forwards setup for a client? Then the command to talk to sish would be like:

`ssh -R 8080:localhost:8080 ssi.sh autoclose=true`

**Comment by antoniomika** [comment]
With the newest release, you can either provide `auto-close=true` similar to the above or enable the `--cleanup-unbound` setting. Either of these will close an SSH session once there are no connections open. Not that `auto-close` will always check to see if that is the case, whereas `cleanup-unbound` will only close connections if they are within a certain timeout.

**Comment by sonntuet1997** [comment]
Thanks
