### ISSUE TITLE
Rewrite Host header

### ISSUE THREAD

**Issue by santicastro** [antoniomika/sish#175]
It should allow rewriting http `Host` header like ngrok does with param `-host-header=example.com`

**Comment by antoniomika** [comment]
Hi @santicastro,

How would you envision this would work as part of an ssh command? Trying to account for the multitenancy aspect of sish.

**Comment by pschichtel** [comment]
I don't fully know how sish works, so this might be complete non-sense:
if I add a command to the ssh command like `ssh -R test:80:localhost:80 root@sish-server 'echo "$(hostname)"'` I would assume that sish could somehow read that command line. If so, then I could imagine having a small CLI to configure certain proxy functions like e.g. HTTP header filtering.

does that make sense?
