### ISSUE TITLE
question about TCP "The alias is unavailable"

### ISSUE THREAD

**Issue by andreasunterhuber** [antoniomika/sish#179]
Dear @antoniomika - we use sish since a while (for HTTPS) but need extensive SSH tunneling for some servers now. 
Opening a tunnel by `ssh -p 2222 -R tunnel1:22:localhost:22 router.example.com` tells us always `The alias tunnel1:22 is unavailable. Assigning a random alias.` - but we don't want a random one. In our config we have: 
```
...
tcp-aliases: true
tcp-load-balancer: false
...
```

What we do wrong? Thanks a lot for your help!

**Comment by antoniomika** [comment]
Hey @andreasunterhuber ,

Thanks for reaching out! Looks like you just need to set sish to not bind subdomains randomly for aliases:
```
--bind-random-aliases                         Force bound alias tunnels to use random aliases instead of user provided ones (default true)
      --bind-random-aliases-length int              The length of the random alias to generate if a alias is unavailable or if random aliases are enforced (default 3)
```

i.e. set `--bind-random-aliases=false` or set it to false in your config.

**Comment by andreasunterhuber** [comment]
@antoniomika wow 🤩  works like a charm! Thanks

**Comment by andreasunterhuber** [comment]
@antoniomika SISH is OK, but trying to connect to the host gives us an error.
We run: 
1. `ssh -p 2222 -R tunnel1:22:localhost:22 router.example.com` ... works! Connection is open. 
    * `Starting SSH Forwarding service for tcp:22. Forwarded connections can be accessed via the following methods:
TCP Alias: tunnel1:22`
2. Trying to connect from other host: `ssh -o ProxyCommand="ssh -p 2222 -W %h:%p router.example.com" tunnel1` gives us the following errors: 
   * Host trying to connect: `kex_exchange_identification: Connection closed by remote host`
   * SISH log: `ssh: rejected: connect failed (Connection refused), Accepted connection from 11.22.244.221:61085 -> tunnel1:22`

How can we identify by password or key from the host?
Thanks again a LOT!

**Comment by andreasunterhuber** [comment]
@antoniomika thanks anyway - I messed up a local configuration 😛 Therefore it was not working. Works everything as expected 👍
