### ISSUE TITLE
Questions: ~/sish contents

### ISSUE THREAD

**Issue by vicpon** [antoniomika/sish#18]
What should be in your sish directory? I see there are 3 subdirs (ssl, keys, pubkeys). What did you use to generate these folders? Thanks

**Comment by antoniomika** [comment]
These directories are created manually and unmanaged by sish. Even if they do not exist, sish will operate fine but you wouldn't be able to use SSL (ssl dir), prevent the host key from being regenerate (keys dir), or use public key authentication (pubkeys dir). When using the docker compose file provided or the docker image, volumes are created that automatically create these directories, therefore docker manages them. Does that info help? It can definitely be better outlined in the readme! Feel free to let me know!

**Comment by cedricve** [comment]
would be great to document this as well. thankyou @antoniomika
