### ISSUE TITLE
kerostampcrab@ssi.sh: Permission denied (password,publickey).

### ISSUE THREAD

**Issue by kerostampcrab** [antoniomika/sish#180]
This might not be a sish problem, but i get this error 'ssh -p 2222 -R 80:localhost:8080 ssi.sh', after it asks to put my password in and i put my password in. I am a total ssh (and sish) newb, so i don't know what to do. 'ssh -R floof:25565:localhost:22 ssi.sh' gives me "Connection closed by 104.225.216.27 port 22".

I am trying to get this to work my Minecraft server. I am on Arch Linux (KDE Plasma).

**Comment by antoniomika** [comment]
Hey @kerostampcrab,

Unfortunately, the demo instance at ssi.sh is no more. I removed that from the README as I had to deal with abuse. 

You can however run your own sish instance in google cloud for free forever. Just follow the instructions here: https://github.com/antoniomika/sish#google-cloud-platform

**Comment by rvenky125** [comment]
I'm also getting the same issue
