### ISSUE TITLE
Question about TXT record and .crt/.key files

### ISSUE THREAD

**Issue by escomputers** [antoniomika/sish#186]
I'd like to expose a private http web server running on localhost:8083
to my aws server with public ip 1.1.1.1 and domain record A cloud.example.com

I connect to this server via ssh using a .pem file
my /root/.ssh/authorized_keys contains:
ssh-rsa XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

When trying to start the server I get this error:
```
./sish --ssh-address=:9001 --http-address=:80 --https-address=:443 --https=true --https-certificate-directory=deploy/ssl --authentication-keys-directory=deploy/pubkeys --private-key-location=deploy/keys/ssh_key --bind-random-ports=false --bind-random-subdomains=false --domain=cloud.example.com --bind-any-host=true
2021/07/31 - 14:15:16 | Starting SSH service on address: :9001
2021/07/31 - 14:15:16 | Error loading private key, generating a new one: open deploy/keys/ssh_key: no such file or directory
2021/07/31 - 14:15:16 | Generated ED25519 Keypair
panic: html/template: pattern matches no files: `templates/*`

goroutine 13 [running]:
html/template.Must(...)
        /opt/hostedtoolcache/go/1.15.8/x64/src/html/template/template.go:372
github.com/gin-gonic/gin.(*Engine).LoadHTMLGlob(0xc000272500, 0xde4cdc, 0xb)
        /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:185 +0x36a
github.com/antoniomika/sish/httpmuxer.Start(0xc000070500)
        /home/runner/work/sish/sish/httpmuxer/httpmuxer.go:39 +0xeca
created by github.com/antoniomika/sish/sshmuxer.Start
        /home/runner/work/sish/sish/sshmuxer/sshmuxer.go:66 +0x56b
```

I guess the command to be run on the client is:
`ssh -p 9001 -R web01:80:localhost:8083 cloud.example.com`

I've already set dns records as follows:
record A) cloud.example.com 1.1.1.1
rercord A) *.cloud.example.com 1.1.1.1

but how TXT record should be set it up?

If I would use testing.cloud.example.com should I edit /etc/hosts on the client according to this?
testing.cloud.example.com 1.1.1.1

Thanks in advance for the support

**Comment by antoniomika** [comment]
Hi @escomputers 

I need to publish a new release to solve the templates issue you're having. You don't need to use TXT records if you allow `bind-any-host` to be true and set `--verify-dns=false`.
