### ISSUE TITLE
[Setup-Help] Stuck at ssh command infinitely

### ISSUE THREAD

**Issue by Shabinder** [antoniomika/sish#189]
Hey, thanks for this project, first of all, I appreciate your open-source contributions

I followed this guide but I am still stuck at last step , can you point me in right direction / help me Debug this;
: https://trustmeiamaninja.github.io/posts/deploying-sish/

**(I can confirm my Sish Intance is active as , as soon as I visit my domain I am redirected to https://github.com/antoniomika/sish/)**

command : `ssh -p 2222 -R hostit:80:localhost:8000 spotiflyer.ml`
![image](https://user-images.githubusercontent.com/44765050/128396919-78ab7af8-8f36-42ee-bcc6-9c11d2a8db3e.png)

**Comment by antoniomika** [comment]
Hey @Shabinder thanks for that!

As to your issue, could you try running `ssh` with the `-vv` parameter and post that output here? Also, what VPS provider are you using? Sometimes you have to change the firewall configuration to let connections through too.

**Comment by Shabinder** [comment]
ssh is redirecting to IPV6 Address , why not ipv4? as I have an A record pointing to my VPS
See Images Below:

![image](https://user-images.githubusercontent.com/44765050/128399524-f54ab733-2529-463f-bc49-a32d2fde3178.png)

![image](https://user-images.githubusercontent.com/44765050/128399367-cf40859d-d2b5-4a4a-9724-4d8f43a3bdda.png)
![image](https://user-images.githubusercontent.com/44765050/128399417-02fdc84c-638e-4f1b-8466-b1b4b655c025.png)

**Comment by Shabinder** [comment]
Also Sish Logs , Seems Like letsEncrypt didn't worked fine ....
![image](https://user-images.githubusercontent.com/44765050/128399853-12b4d533-28a5-453f-9d79-613c8f930769.png)

**Comment by Shabinder** [comment]
```
version: '3.7'

services:
  letsencrypt:
    image: adferrand/dnsrobocert:latest
    container_name: letsencrypt-dns
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/etc/letsencrypt
      - ./le-config.yml:/etc/dnsrobocert/config.yml
    restart: always
  sish:
    image: antoniomika/sish:latest
    container_name: sish
    depends_on:
      - letsencrypt
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./pubkeys:/pubkeys
      - ./keys:/keys
      - ./ssl:/ssl
      - ./log:/var/log
    command: |
      --ssh-address=:2222
      --http-address=:80
      --https-address=:443
      --https=true
      --https-certificate-directory=/ssl
      --log-to-file
      --log-to-file-path=/var/log/sish/sish.log
      --log-to-file-max-size=200
      --redirect-root-location=https://github.com/Shabinder/SpotiFlyer/
      --authentication=false
      --authentication-keys-directory=/pubkeys
      --authentication-password=""
      --private-key-location=/keys/ssh_key
      --bind-random-ports=false
      --bind-random-subdomains=false
      --service-console
      --domain=spotiflyer.ml
    network_mode: host                                                   
    restart: always

```


I just turned authentication = false , in order to try if that works but no luck

**Comment by antoniomika** [comment]
Ahh, it looks like the reason that you can't connect is because you have the domain proxied by cloudflare (which is also why you see the IPv6 address). Go ahead and disable that (click the cloud that's orange in your cloudflare screenshot).

**Comment by Shabinder** [comment]
@antoniomika Thanks that and opening 2222 port in IpTables did the trick :+1:

**Comment by kwekewk** [comment]
> Ahh, it looks like the reason that you can't connect is because you have the domain proxied by cloudflare (which is also why you see the IPv6 address). Go ahead and disable that (click the cloud that's orange in your cloudflare screenshot).

sorry for bump. are sish can't work when we use proxy mode

**Comment by antoniomika** [comment]
If you're using one of cloudflares forwarded ports, everything should work as expected (as above). Cloudflare doesn't proxy every port.
