### ISSUE TITLE
SISH panic recovered

### ISSUE THREAD

**Issue by gvsurenderreddy** [antoniomika/sish#19]
2019/09/01 20:35:22 [Recovery] 2019/09/01 - 20:35:22 panic recovered:
GET /include/Orbitron700.woff HTTP/2.0
Host: bule40.ip2.io
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Origin: https://bule40.ip2.io
Referer: https://bule40.ip2.io/include/base.css
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
X-Forwarded-Proto: https

net/http: abort Handler
/root/go/src/net/http/httputil/reverseproxy.go:309 (0x8300a3f)
	(*ReverseProxy).ServeHTTP: panic(http.ErrAbortHandler)
/root/goworkspace/pkg/mod/github.com/gin-gonic/gin@v1.3.0/utils.go:48 (0x853d6cd)
	WrapH.func1: h.ServeHTTP(c.Writer, c.Request)
/root/sish/http.go:113 (0x85570b9)
	startHTTPHandler.func2: gin.WrapH(proxy)(c)
/root/goworkspace/pkg/mod/github.com/gin-gonic/gin@v1.3.0/context.go:108 (0x852f7e4)
	(*Context).Next: c.handlers[c.index](c)
/root/goworkspace/pkg/mod/github.com/gin-gonic/gin@v1.3.0/recovery.go:48 (0x853d509)
	RecoveryWithWriter.func1: c.Next()
/root/goworkspace/pkg/mod/github.com/gin-gonic/gin@v1.3.0/context.go:108 (0x852f7e4)
	(*Context).Next: c.handlers[c.index](c)
/root/goworkspace/pkg/mod/github.com/gin-gonic/gin@v1.3.0/logger.go:84 (0x853cb16)
	LoggerWithWriter.func1: c.Next()
/root/goworkspace/pkg/mod/github.com/gin-gonic/gin@v1.3.0/context.go:108 (0x852f7e4)
	(*Context).Next: c.handlers[c.index](c)
/root/sish/http.go:40 (0x8556a72)
	startHTTPHandler.func1: c.Next()
/root/goworkspace/pkg/mod/github.com/gin-gonic/gin@v1.3.0/context.go:108 (0x852f7e4)
	(*Context).Next: c.handlers[c.index](c)
/root/goworkspace/pkg/mod/github.com/gin-gonic/gin@v1.3.0/gin.go:397 (0x85366ab)
	serveError: c.Next()
/root/goworkspace/pkg/mod/github.com/gin-gonic/gin@v1.3.0/gin.go:390 (0x853647b)
	(*Engine).handleHTTPRequest: serveError(c, http.StatusNotFound, default404Body)
/root/goworkspace/pkg/mod/github.com/gin-gonic/gin@v1.3.0/gin.go:326 (0x8535ff9)
	(*Engine).ServeHTTP: engine.handleHTTPRequest(c)
/root/go/src/net/http/server.go:2774 (0x82d7293)
	serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/root/go/src/net/http/server.go:3323 (0x82d88bc)
	initNPNRequest.ServeHTTP: h.h.ServeHTTP(rw, req)
/root/go/src/net/http/h2_bundle.go:5688 (0x82b3fbc)
	(*http2serverConn).runHandler: handler(rw, req)
/root/go/src/runtime/asm_386.s:1321 (0x8099860)
	goexit: BYTE	$0x90	// NOP

[GIN] 2019/09/01 - 20:35:22 | 500 | 19.199853728s |  106.77.180.107 | GET      /include/Orbitron700.woff

**Comment by antoniomika** [comment]
This happens when the communication between gin/the ssh channel becomes broken. Gin handles this cleanly so it isn't an issue.
