### ISSUE TITLE
Change key algorithm

### ISSUE THREAD

**Issue by assamsamy** [antoniomika/sish#190]
Hey, thanks for the repo ! 
I'm attemping to forward a local server hosted in an embedded linux 32 bits (dropbear ssh client). Sish return me this error in my VPS. 
`ssh: no common algorithm for host key; client offered: [ecdsa-sha2-nistp256 ecdsa-sha2-nistp384 ecdsa-sha2-nistp521 ssh-rsa ssh-dss], server offered: [ssh-ed25519]`

How to change the type of sish key to rsa or ecdsa ?

**Comment by antoniomika** [comment]
Hey @assamsamy,

You should just need to remove the currently used ssh key (from wherever you have sish configured to look) and replace it with a key that works for you. You can create an ssh key as normal using `ssh-keygen -t rsa -b 2048` or the like.
