### ISSUE TITLE
Strange behaviour when trying to use server-sent events (SSE) - possibly compression related?

### ISSUE THREAD

**Issue by ezzatron** [antoniomika/sish#192]
I was testing out sish for use with a Webpack-based dev server, and noticed that for some reason, sish breaks the hot module replacement (HMR) feature which is using server-sent events (SSE) to push code changes to the browser.

I made a screen recording of the phenomenon. The top browser window is being accessed via sish, whereas the bottom window is being accessed directly:

https://user-images.githubusercontent.com/100152/133586149-1693b0a2-2934-4d4c-84d3-44ba8b4483eb.mov

As you can see, the sish version takes a few updates to start working. Once it starts working, it seems to usually be one update behind, but also misses some updates entirely. The only possible culprit I can think of is compression, because it's known to cause issues with SSE - see [this explanation](https://github.com/expressjs/compression#server-sent-events):

> To compress content, a window of the output needs to be buffered up in order to get good compression. Typically when using server-sent events, there are certain block of data that need to reach the client.

I don't really know how to turn this into a nice reproducible demo unfortunately. The specific package doing the SSE in this case is [webpack-hot-middleware](https://github.com/webpack-contrib/webpack-hot-middleware), but I'm not sure that helps much. I tried to create a much smaller reproduction with a simple SSE server, but had no luck getting the same problem to occur.

**Comment by ezzatron** [comment]
I should have double-checked the compression headers before posting. Neither of these seems to be compressed, so I don't think it's that 😕

**Comment by antoniomika** [comment]
Thanks @ezzatron for the report?

Would you mind opening the JS console for each window and sharing the same video had with that?

Also, are there any logs from sish that you can share either?

**Comment by ezzatron** [comment]
Sorry for the delayed response. The logs don't offer much (I get the `setsockopt TCP_NODELAY: Invalid argument` error under normal sish operation):

    [stdout] Press Ctrl-C to close the session.
    [stdout]
    [stdout] Starting SSH Forwarding service for http:80. Forwarded connections can be accessed via the following methods:
    [stdout] HTTP: http://sodium-nitrogen-river.<redacted>
    [stdout] HTTPS: https://sodium-nitrogen-river.<redacted>
    [stdout]
    [stderr] setsockopt TCP_NODELAY: Invalid argument
    [stderr] setsockopt TCP_NODELAY: Invalid argument
    [stderr] setsockopt TCP_NODELAY: Invalid argument
    [stderr] setsockopt TCP_NODELAY: Invalid argument
    [stderr] setsockopt TCP_NODELAY: Invalid argument
    [stderr] setsockopt TCP_NODELAY: Invalid argument

Here's a recording of the console (accessing via sish):

https://user-images.githubusercontent.com/100152/133703179-dbd91158-db03-4ed7-b83f-9a26b3b80808.mov

And here's a recording of the network panel (accessing via sish):

https://user-images.githubusercontent.com/100152/133703312-f86e2e5b-dfe6-4171-88ed-3f71a0db51bd.mov

Versus the network panel when the server is accessed directly:

https://user-images.githubusercontent.com/100152/133703682-040be530-4c2b-4444-9abc-933e2dff263f.mov

It seems like some kind of buffering issue? Without sish, the SSE request _immediately_ sees a response, but with sish the request is "pending" until I make the first code change. Is there any kind of buffering going on in sish perhaps?

**Comment by ezzatron** [comment]
FWIW I found something similar digging through ngrok's issues: https://github.com/inconshreveable/ngrok/issues/135

**Comment by ezzatron** [comment]
More evidence that this might be caused by buffering - when I open the SSE endpoint directly in the browser, I can see that it's sending through data in chunks that are exactly 4096 bytes in size.

**Comment by antoniomika** [comment]
Interesting! Can you try to see if this happens when doing a tcp forward instead of an http forward? I'm curious if that changes things also.

**Comment by ezzatron** [comment]
Okay, I think there's no need for that as I've figured out the cause (with the help of @jmalloc). It seems that at some point, the go standard library improved SSE support by flushing immediately. The problem is, that they do an explicit string check for `text/event-stream` as the value of the `Content-Type` header, but the middleware specifies a character encoding (e.g. `text/event-stream;charset=utf-8`). It's actually a bug in go, as they are not parsing the header value before comparing the MIME type.

I confirmed this by firing up an SSE server that uses the same `Content-Type` header. The problem then becomes reproducible. If I remove the `charset` parameter, the issue disappears again.

So it's not a bug in sish! My friend @jmalloc is going to make a PR against golang. I'll post that here when it's ready. Thanks for your help.

**Comment by ezzatron** [comment]
Relevant PR: https://github.com/golang/go/pull/48427

**Comment by antoniomika** [comment]
Nice! Looks a like a fun bug to figure out! Thanks for keeping me updated.

**Comment by jmalloc** [comment]
Just to note this somewhere - I suspect the code that intercepts HTTP responses in order to log them on the web console will still interfere with SSE or any other kind of "keep-alive" style response without a fixed content length.
