### ISSUE TITLE
--https-certificate-file & --https-certificate-key-file

### ISSUE THREAD

**Issue by frankhommers** [antoniomika/sish#193]
I'd like to have the above items instead of only the directory. This way I can point them right to my letsencrypt directory containing cert.pem and privkey.pem. Also I don't need symbolic links.

**Comment by antoniomika** [comment]
Hey @frankhommers,

I'm going to keep this as-is due to it being most general. Having added HTTPS auto reload in my upcoming PR, there's more reason to leave it at that (I use sish with multiple domains and it is very convenient using the current method with letsencrypt)
