### ISSUE TITLE
No interactive shell possible in container

### ISSUE THREAD

**Issue by frankhommers** [antoniomika/sish#194]
```bash
$ docker exec -it sish /bin/sh
OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown
```
Also there is no bash or other shell that I know off.

This makes debugging the docker image really hard when something goes wrong. 

(BTW: Great project!!)

**Comment by frankhommers** [comment]
@antoniomika I don't see how that commit closes this issue.. Did you reference the wrong commit hash?

**Comment by antoniomika** [comment]
@frankhommers nope. I intentionally want sish to be based on a scratch image (better for security and size, big benefit of using golang with static compilation). What we will do now is publish the full build image using the exact same tags to dockerhub in a [different repo](https://hub.docker.com/r/antoniomika/sish-build-image/tags). All you'd need to do to access a shell to debug would be to update the image name and change the command to use `app` as the entrypoint. I might update the docker image to use the same entrypoint to make that clearer though.

**Comment by antoniomika** [comment]
Looking at the diff above, I think github is doing something weird. Here's the correct diff: https://github.com/antoniomika/sish/commit/9806498725e11b34398636fb0a3f762f6d255fd4

Probably has to do with my force pushes
