### ISSUE TITLE
RSA ssh keys

### ISSUE THREAD

**Issue by iwex** [antoniomika/sish#196]
Does it support RSA keys? I tried, but got  `debug1: send_pubkey_test: no mutual signature algorithm`. Then I generate ed25519 key and he works fine.

**Comment by antoniomika** [comment]
Hey @iwex,

Yes, sish supports RSA keys. I generated a new RSA key using ssh-keygen and sish was able to load it just fine. I was also able to force connecting using just an RSA cipher. Can you share some reproduction steps for this? 

Gonna close this issue while we confirm it's a problem with sish.
