### ISSUE TITLE
Non-HTTP port not working

### ISSUE THREAD

**Issue by capriciousduck** [antoniomika/sish#197]
Here is my docker command. When I use other than 80 for HTTP address sish doesn't work. Please can you tell what I'm doing wrong?

docker run -itd --name sish --restart unless-stopped \
  -v /mnt/sish/ssl:/ssl \
  -v /mnt/sish/keys:/keys \
  -v /mnt/sish:/pubkeys \
  --net=host antoniomika/sish:latest \
  --ssh-address=:2222 \
  --http-address=:10000 \
  --https-address=:443 \
  --https=false \
  --authentication=false \
  --domain=mydomain.com \
  --https-certificate-directory=/ssl \
  --private-key-location=/keys/ssh_key \
  --authentication-keys-directory=/pubkeys \
  --bind-random-ports=false \
  --bind-random-subdomains=false \
  --idle-connection=false \
  --admin-console=true \
  --cleanup-unbound=true \
  --cleanup-unbound-timeout=1s \
  --admin-console-token=mytoken

**Comment by antoniomika** [comment]
WIthout much context here, I'm not sure what I can help with. Please add more reproduction steps, logs, etc.
