### ISSUE TITLE
Explicit parameter to setup a TCP Alias tunnel instead of a HTTP(S) proxy

### ISSUE THREAD

**Issue by blop** [antoniomika/sish#199]
Hello,

This is a new feature request for an optional explicit parameter to setup a TCP alias tunnel instead of a HTTP(S) tunnel.
Something like :
`ssh -R myalias:80:127.0.0.1:80 sish.server type=tcp-alias
`
In the same spirit as the other explicit parameters, like the ones introduced for #167.

Currently if we choose the port defined for either HTTP or HTTPS, sish will create a HTTP(S) tunnel and use the alias to compute the subdomain, which is great by default.
Since #198 we can even change the default ports used for HTTP and HTTPS to something different than 80 and 443.

But adding an explicit parameter would be even more convenient to allow both at the same time and let the client choose.
This would offer another resolution to #185 as well.

Thank you!

**Comment by antoniomika** [comment]
Hey @blop,

By providing `tcp-alias=true` as a command to the SSH command, this is now implemented!

**Comment by blop** [comment]
Thank you so much !
