### ISSUE TITLE
Pubkey authentication does not work for Archlinux clients, asks for password

### ISSUE THREAD

**Issue by misterzirillo** [antoniomika/sish#200]
I noticed today that my Arch machine is always required to input a password when hosting a tunnel or connecting to one. At first I thought I had copied my pubkey to sish's directory incorrectly. I fiddled with it a bunch and I ended up creating a new one without any luck. I also tried explicitly disabling password auth with `-o PasswordAuthentication=no` which didn't work.

For comparison I tried the same thing from my raspberry pi (Ubuntu). As expected, adding my Pi's public key in the pubkey directory allowed both hosting a tunnel and connecting to an existing one without entering a password. I verified the correct behavior using WSL/Ubuntu on my Windows machine and the `ubuntu:rolling` docker image.

I found you can reproduce the problem with the Arch image:
1. `docker run -it --rm archlinux:latest`
2. `pacman -Sy`
3. `pacman -S openssh`
4. `ssh-keygen` (no args or passcode)
5. Copy pubkey to sish's directory 
6. `ssh -R test:22:localhost:22 whereever_sish_is`

It appears to be a difference of clients. Pubkey auth works fine for other SSH services (github, gitlab, etc). Arch is on OpenSSH 8.8 and Ubuntu is 8.2. Does anyone have anything else I could try?

**Comment by antoniomika** [comment]
Hey @misterzirillo,

Looking into this, it seems this occurs because the `ssh-keygen` in arch will generate RSA keys by default instead of ED25519 keys. sish's default host key is an ED25519 key, which is why it won't work. sish currently doesn't have support for multiple host keys (mainly due to handing passphrases for multiple keys).
