### ISSUE TITLE
Can this be used with MC to do virtual lan?

### ISSUE THREAD

**Issue by pinbuck** [antoniomika/sish#210]
I'm trying to get me and my friends off of all the annoying tunneling software out there like hamachi, playit.gg, ngrok, etc. which are proprietary and require accounts. Does this tool meet the requirement, and if so could you make a tutorial for both win/lin/mac?

**Comment by antoniomika** [comment]
This can be done using sish, but you'll probably have better luck using the following:

[ZeroTier](https://www.zerotier.com/) - Fully open source, including the controller. You can host it yourself, or you can use their controller for free from [here](https://github.com/dec0dOS/zero-ui)
[Tailscale](https://tailscale.com/) - Not fully open source, might be a bit more straight forward to setup.

If you want to use sish though, follow the instructions [here](https://github.com/antoniomika/sish/blob/main/deploy/gcloud.md) to install it on a free VPS. Then, you run the following on your minecraft server:

```bash
ssh -R 25565:localhost:25565 your-vps-ip
```

And access it from your-vps-ip:25565. This will open the server to everyone. If you want only certain people to access it, run:

```bash
ssh -R mcserver:25565:localhost:25565 your-vps-ip
```

And your friends join by running:

```bash
ssh -L 25565:mcserver:25565 your-vps-ip
```

And connect to `localhost:25565` in MC.

I think ZeroTier is honestly the easiest option here though, your mileage may vary!
