### ISSUE TITLE
Problem.when compile for mips

### ISSUE THREAD

**Issue by santa2021** [antoniomika/sish#212]
I am getting this error when I compile the program for mips:
# github.com/phuslu/iploc
../../go/pkg/mod/github.com/phuslu/iploc@v1.0.20211029/iploc.go:44:33: undefined: ip4bin
../../go/pkg/mod/github.com/phuslu/iploc@v1.0.20211029/iploc.go:45:13: undefined: ip4bin
../../go/pkg/mod/github.com/phuslu/iploc@v1.0.20211029/iploc.go:46:13: undefined: ip4bin
../../go/pkg/mod/github.com/phuslu/iploc@v1.0.20211029/iploc.go:50:41: undefined: ip6bin
../../go/pkg/mod/github.com/phuslu/iploc@v1.0.20211029/iploc.go:51:2: undefined: ip6bin
../../go/pkg/mod/github.com/phuslu/iploc@v1.0.20211029/iploc.go:51:12: cannot assign []byte to ip6bin in multiple assignment
../../go/pkg/mod/github.com/phuslu/iploc@v1.0.20211029/iploc.go:53:33: undefined: ip6bin
../../go/pkg/mod/github.com/phuslu/iploc@v1.0.20211029/iploc.go:54:13: undefined: ip6bin
../../go/pkg/mod/github.com/phuslu/iploc@v1.0.20211029/iploc.go:55:13: undefined: ip6bin

Previously, when I compiled version 1.1.6, there was no such error 
How can this be fixed?

**Comment by antoniomika** [comment]
What's the specific arch? Needs to be in these lists: 

https://github.com/phuslu/iploc/blob/v1.0.20220129/iploc_be.go
https://github.com/phuslu/iploc/blob/v1.0.20220129/iploc_le.go

You might have to revert the iploc version for your build, I'm not 100% sure on it though.
