### ISSUE TITLE
Strange Error

### ISSUE THREAD

**Issue by capriciousduck** [antoniomika/sish#213]
Here is my docker command:

docker run -d --name sish \
  --restart unless-stopped \
  -v /mnt/sish/ssl:/ssl \
  -v /mnt/sish/keys:/keys \
  -v /mnt/sish/pubkeys:/pubkeys \
  --net=host antoniomika/sish:latest \
  --ssh-address=:2222 \
  --http-address=:7777 \
  --https=false \
  --authentication=true \
  --authentication-password=sishpassword \
  --private-keys-directory=/keys/ssh_key \
  --authentication-keys-directory=/pubkeys \
  --bind-random-ports=true \
  --bind-random-subdomains=true \
  --domain=my.domain.tld \
  --idle-connection=false \
  --admin-console=true \
  --cleanup-unbound=true \
  --cleanup-unbound-timeout=1s \
  --admin-console-token=sishpassword

Here is the error:

2022/02/06 - 07:33:03 | Starting SSH service on address: :2222
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xab71cd]

goroutine 1 [running]:
github.com/antoniomika/sish/utils.loadPrivateKeys.func2({0x7fffcf5aee24, 0xd}, {0x0, 0x0}, {0xd622e0, 0xc0000ad140})
        /app/utils/utils.go:261 +0x4d
path/filepath.WalkDir({0x7fffcf5aee24, 0xd}, 0xc000261c00)
        /usr/local/go/src/path/filepath/path.go:467 +0x50
github.com/antoniomika/sish/utils.loadPrivateKeys(0xc0000af380)
        /app/utils/utils.go:260 +0xa5
github.com/antoniomika/sish/utils.GetSSHConfig()
        /app/utils/utils.go:474 +0x6d
github.com/antoniomika/sish/sshmuxer.Start()
        /app/sshmuxer/sshmuxer.go:113 +0x5bf
github.com/antoniomika/sish/cmd.runCommand(0x155d060, {0xc493f9, 0xf, 0xf})
        /app/cmd/sish.go:215 +0x17
github.com/spf13/cobra.(*Command).execute(0x155d060, {0xc00018a010, 0xf, 0xf})
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x155d060)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/antoniomika/sish/cmd.Execute(...)
        /app/cmd/sish.go:210
main.main()
        /app/main.go:12 +0x25
2022/02/06 - 07:33:03 | Starting SSH service on address: :2222
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xab71cd]

goroutine 1 [running]:
github.com/antoniomika/sish/utils.loadPrivateKeys.func2({0x7ffd0d345e24, 0xd}, {0x0, 0x0}, {0xd622e0, 0xc0000a3230})
        /app/utils/utils.go:261 +0x4d
path/filepath.WalkDir({0x7ffd0d345e24, 0xd}, 0xc0002afc00)
        /usr/local/go/src/path/filepath/path.go:467 +0x50
github.com/antoniomika/sish/utils.loadPrivateKeys(0xc00041b450)
        /app/utils/utils.go:260 +0xa5
github.com/antoniomika/sish/utils.GetSSHConfig()
        /app/utils/utils.go:474 +0x6d
github.com/antoniomika/sish/sshmuxer.Start()
        /app/sshmuxer/sshmuxer.go:113 +0x5bf
github.com/antoniomika/sish/cmd.runCommand(0x155d060, {0xc493f9, 0xf, 0xf})
        /app/cmd/sish.go:215 +0x17
github.com/spf13/cobra.(*Command).execute(0x155d060, {0xc000144010, 0xf, 0xf})
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x155d060)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/antoniomika/sish/cmd.Execute(...)
        /app/cmd/sish.go:210
main.main()
        /app/main.go:12 +0x25
2022/02/06 - 07:33:04 | Starting SSH service on address: :2222
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xab71cd]

goroutine 1 [running]:
github.com/antoniomika/sish/utils.loadPrivateKeys.func2({0x7fff0802ce24, 0xd}, {0x0, 0x0}, {0xd622e0, 0xc00040b860})
        /app/utils/utils.go:261 +0x4d
path/filepath.WalkDir({0x7fff0802ce24, 0xd}, 0xc000299c00)
        /usr/local/go/src/path/filepath/path.go:467 +0x50
github.com/antoniomika/sish/utils.loadPrivateKeys(0xc000405790)
        /app/utils/utils.go:260 +0xa5
github.com/antoniomika/sish/utils.GetSSHConfig()
        /app/utils/utils.go:474 +0x6d
github.com/antoniomika/sish/sshmuxer.Start()
        /app/sshmuxer/sshmuxer.go:113 +0x5bf
github.com/antoniomika/sish/cmd.runCommand(0x155d060, {0xc493f9, 0xf, 0xf})
        /app/cmd/sish.go:215 +0x17
github.com/spf13/cobra.(*Command).execute(0x155d060, {0xc000030110, 0xf, 0xf})
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x155d060)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/antoniomika/sish/cmd.Execute(...)
        /app/cmd/sish.go:210
main.main()
        /app/main.go:12 +0x25
2022/02/06 - 07:33:05 | Starting SSH service on address: :2222
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xab71cd]

goroutine 1 [running]:
github.com/antoniomika/sish/utils.loadPrivateKeys.func2({0x7fff3a87ae24, 0xd}, {0x0, 0x0}, {0xd622e0, 0xc000117140})
        /app/utils/utils.go:261 +0x4d
path/filepath.WalkDir({0x7fff3a87ae24, 0xd}, 0xc000593c00)
        /usr/local/go/src/path/filepath/path.go:467 +0x50
github.com/antoniomika/sish/utils.loadPrivateKeys(0xc0004932b0)
        /app/utils/utils.go:260 +0xa5
github.com/antoniomika/sish/utils.GetSSHConfig()
        /app/utils/utils.go:474 +0x6d
github.com/antoniomika/sish/sshmuxer.Start()
        /app/sshmuxer/sshmuxer.go:113 +0x5bf
github.com/antoniomika/sish/cmd.runCommand(0x155d060, {0xc493f9, 0xf, 0xf})
        /app/cmd/sish.go:215 +0x17
github.com/spf13/cobra.(*Command).execute(0x155d060, {0xc000030110, 0xf, 0xf})
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x155d060)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/antoniomika/sish/cmd.Execute(...)
        /app/cmd/sish.go:210
main.main()
        /app/main.go:12 +0x25
2022/02/06 - 07:33:06 | Starting SSH service on address: :2222
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xab71cd]

goroutine 1 [running]:
github.com/antoniomika/sish/utils.loadPrivateKeys.func2({0x7ffdf382fe24, 0xd}, {0x0, 0x0}, {0xd622e0, 0xc0000a7290})
        /app/utils/utils.go:261 +0x4d
path/filepath.WalkDir({0x7ffdf382fe24, 0xd}, 0xc000129c00)
        /usr/local/go/src/path/filepath/path.go:467 +0x50
github.com/antoniomika/sish/utils.loadPrivateKeys(0xc0004871e0)
        /app/utils/utils.go:260 +0xa5
github.com/antoniomika/sish/utils.GetSSHConfig()
        /app/utils/utils.go:474 +0x6d
github.com/antoniomika/sish/sshmuxer.Start()
        /app/sshmuxer/sshmuxer.go:113 +0x5bf
github.com/antoniomika/sish/cmd.runCommand(0x155d060, {0xc493f9, 0xf, 0xf})
        /app/cmd/sish.go:215 +0x17
github.com/spf13/cobra.(*Command).execute(0x155d060, {0xc0001b4010, 0xf, 0xf})
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x155d060)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/antoniomika/sish/cmd.Execute(...)
        /app/cmd/sish.go:210
main.main()
        /app/main.go:12 +0x25
2022/02/06 - 07:33:08 | Starting SSH service on address: :2222
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xab71cd]

goroutine 1 [running]:
github.com/antoniomika/sish/utils.loadPrivateKeys.func2({0x7fff4eefee24, 0xd}, {0x0, 0x0}, {0xd622e0, 0xc0004826f0})
        /app/utils/utils.go:261 +0x4d
path/filepath.WalkDir({0x7fff4eefee24, 0xd}, 0xc000669c00)
        /usr/local/go/src/path/filepath/path.go:467 +0x50
github.com/antoniomika/sish/utils.loadPrivateKeys(0xc000405450)
        /app/utils/utils.go:260 +0xa5
github.com/antoniomika/sish/utils.GetSSHConfig()
        /app/utils/utils.go:474 +0x6d
github.com/antoniomika/sish/sshmuxer.Start()
        /app/sshmuxer/sshmuxer.go:113 +0x5bf
github.com/antoniomika/sish/cmd.runCommand(0x155d060, {0xc493f9, 0xf, 0xf})
        /app/cmd/sish.go:215 +0x17
github.com/spf13/cobra.(*Command).execute(0x155d060, {0xc000030110, 0xf, 0xf})
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x155d060)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/antoniomika/sish/cmd.Execute(...)
        /app/cmd/sish.go:210
main.main()
        /app/main.go:12 +0x25
2022/02/06 - 07:33:12 | Starting SSH service on address: :2222
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xab71cd]

goroutine 1 [running]:
github.com/antoniomika/sish/utils.loadPrivateKeys.func2({0x7ffc5590ee24, 0xd}, {0x0, 0x0}, {0xd622e0, 0xc000503110})
        /app/utils/utils.go:261 +0x4d
path/filepath.WalkDir({0x7ffc5590ee24, 0xd}, 0xc000195c00)
        /usr/local/go/src/path/filepath/path.go:467 +0x50
github.com/antoniomika/sish/utils.loadPrivateKeys(0xc000489110)
        /app/utils/utils.go:260 +0xa5
github.com/antoniomika/sish/utils.GetSSHConfig()
        /app/utils/utils.go:474 +0x6d
github.com/antoniomika/sish/sshmuxer.Start()
        /app/sshmuxer/sshmuxer.go:113 +0x5bf
github.com/antoniomika/sish/cmd.runCommand(0x155d060, {0xc493f9, 0xf, 0xf})
        /app/cmd/sish.go:215 +0x17
github.com/spf13/cobra.(*Command).execute(0x155d060, {0xc0001b4010, 0xf, 0xf})
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x155d060)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/antoniomika/sish/cmd.Execute(...)
        /app/cmd/sish.go:210
main.main()
        /app/main.go:12 +0x25
2022/02/06 - 07:33:19 | Starting SSH service on address: :2222
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xab71cd]

goroutine 1 [running]:
github.com/antoniomika/sish/utils.loadPrivateKeys.func2({0x7ffc7911ce24, 0xd}, {0x0, 0x0}, {0xd622e0, 0xc000117da0})
        /app/utils/utils.go:261 +0x4d
path/filepath.WalkDir({0x7ffc7911ce24, 0xd}, 0xc0005a1c00)
        /usr/local/go/src/path/filepath/path.go:467 +0x50
github.com/antoniomika/sish/utils.loadPrivateKeys(0xc00012b380)
        /app/utils/utils.go:260 +0xa5
github.com/antoniomika/sish/utils.GetSSHConfig()
        /app/utils/utils.go:474 +0x6d
github.com/antoniomika/sish/sshmuxer.Start()
        /app/sshmuxer/sshmuxer.go:113 +0x5bf
github.com/antoniomika/sish/cmd.runCommand(0x155d060, {0xc493f9, 0xf, 0xf})
        /app/cmd/sish.go:215 +0x17
github.com/spf13/cobra.(*Command).execute(0x155d060, {0xc000030110, 0xf, 0xf})
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x155d060)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/antoniomika/sish/cmd.Execute(...)
        /app/cmd/sish.go:210
main.main()
        /app/main.go:12 +0x25
2022/02/06 - 07:33:32 | Starting SSH service on address: :2222
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xab71cd]

goroutine 1 [running]:
github.com/antoniomika/sish/utils.loadPrivateKeys.func2({0x7fff3ed1ee24, 0xd}, {0x0, 0x0}, {0xd622e0, 0xc000115110})
        /app/utils/utils.go:261 +0x4d
path/filepath.WalkDir({0x7fff3ed1ee24, 0xd}, 0xc0002c3c00)
        /usr/local/go/src/path/filepath/path.go:467 +0x50
github.com/antoniomika/sish/utils.loadPrivateKeys(0xc00012d110)
        /app/utils/utils.go:260 +0xa5
github.com/antoniomika/sish/utils.GetSSHConfig()
        /app/utils/utils.go:474 +0x6d
github.com/antoniomika/sish/sshmuxer.Start()
        /app/sshmuxer/sshmuxer.go:113 +0x5bf
github.com/antoniomika/sish/cmd.runCommand(0x155d060, {0xc493f9, 0xf, 0xf})
        /app/cmd/sish.go:215 +0x17
github.com/spf13/cobra.(*Command).execute(0x155d060, {0xc000030110, 0xf, 0xf})
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x155d060)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/antoniomika/sish/cmd.Execute(...)
        /app/cmd/sish.go:210
main.main()
        /app/main.go:12 +0x25
2022/02/06 - 07:33:58 | Starting SSH service on address: :2222
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xab71cd]

goroutine 1 [running]:
github.com/antoniomika/sish/utils.loadPrivateKeys.func2({0x7ffd971f7e24, 0xd}, {0x0, 0x0}, {0xd622e0, 0xc0000a51d0})
        /app/utils/utils.go:261 +0x4d
path/filepath.WalkDir({0x7ffd971f7e24, 0xd}, 0xc0005e3c00)
        /usr/local/go/src/path/filepath/path.go:467 +0x50
github.com/antoniomika/sish/utils.loadPrivateKeys(0xc00040f520)
        /app/utils/utils.go:260 +0xa5
github.com/antoniomika/sish/utils.GetSSHConfig()
        /app/utils/utils.go:474 +0x6d
github.com/antoniomika/sish/sshmuxer.Start()
        /app/sshmuxer/sshmuxer.go:113 +0x5bf
github.com/antoniomika/sish/cmd.runCommand(0x155d060, {0xc493f9, 0xf, 0xf})
        /app/cmd/sish.go:215 +0x17
github.com/spf13/cobra.(*Command).execute(0x155d060, {0xc00013a010, 0xf, 0xf})
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x155d060)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/antoniomika/sish/cmd.Execute(...)
        /app/cmd/sish.go:210
main.main()
        /app/main.go:12 +0x25
2022/02/06 - 07:34:50 | Starting SSH service on address: :2222
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xab71cd]

goroutine 1 [running]:
github.com/antoniomika/sish/utils.loadPrivateKeys.func2({0x7ffef44eae24, 0xd}, {0x0, 0x0}, {0xd622e0, 0xc0000a5230})
        /app/utils/utils.go:261 +0x4d
path/filepath.WalkDir({0x7ffef44eae24, 0xd}, 0xc00060dc00)
        /usr/local/go/src/path/filepath/path.go:467 +0x50
github.com/antoniomika/sish/utils.loadPrivateKeys(0xc0004936c0)
        /app/utils/utils.go:260 +0xa5
github.com/antoniomika/sish/utils.GetSSHConfig()
        /app/utils/utils.go:474 +0x6d
github.com/antoniomika/sish/sshmuxer.Start()
        /app/sshmuxer/sshmuxer.go:113 +0x5bf
github.com/antoniomika/sish/cmd.runCommand(0x155d060, {0xc493f9, 0xf, 0xf})
        /app/cmd/sish.go:215 +0x17
github.com/spf13/cobra.(*Command).execute(0x155d060, {0xc00013a010, 0xf, 0xf})
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x155d060)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/antoniomika/sish/cmd.Execute(...)
        /app/cmd/sish.go:210
main.main()
        /app/main.go:12 +0x25
2022/02/06 - 07:35:50 | Starting SSH service on address: :2222
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xab71cd]

goroutine 1 [running]:
github.com/antoniomika/sish/utils.loadPrivateKeys.func2({0x7ffc1b53de24, 0xd}, {0x0, 0x0}, {0xd622e0, 0xc0000bbd40})
        /app/utils/utils.go:261 +0x4d
path/filepath.WalkDir({0x7ffc1b53de24, 0xd}, 0xc000273c00)
        /usr/local/go/src/path/filepath/path.go:467 +0x50
github.com/antoniomika/sish/utils.loadPrivateKeys(0xc0000cd1e0)
        /app/utils/utils.go:260 +0xa5
github.com/antoniomika/sish/utils.GetSSHConfig()
        /app/utils/utils.go:474 +0x6d
github.com/antoniomika/sish/sshmuxer.Start()
        /app/sshmuxer/sshmuxer.go:113 +0x5bf
github.com/antoniomika/sish/cmd.runCommand(0x155d060, {0xc493f9, 0xf, 0xf})
        /app/cmd/sish.go:215 +0x17
github.com/spf13/cobra.(*Command).execute(0x155d060, {0xc000030110, 0xf, 0xf})
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x155d060)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/antoniomika/sish/cmd.Execute(...)
        /app/cmd/sish.go:210
main.main()
        /app/main.go:12 +0x25

**Comment by antoniomika** [comment]
Looks like you provided a file instead of a directory for `private-keys-directory`.

**Comment by capriciousduck** [comment]
Still not working. I need no HTTPS and I want password authentication. Then is the below command the right one?

docker run -d --name sish \
  --restart unless-stopped \
  -v /mnt/$(hostname)/sish/ssl:/ssl \
  -v /mnt/$(hostname)/sish/keys:/keys \
  -v /mnt/$(hostname)/sish/pubkeys:/pubkeys \
  --net=host antoniomika/sish:latest \
  --ssh-address=:2222 \
  --http-address=:7777 \
  --https=false \
  --authentication=true \
  --authentication-password='sishpassword' \
  --bind-random-ports=true \
  --bind-random-subdomains=true \
  --domain=mydomain.tld \
  --idle-connection=false \
  --admin-console=true \
  --cleanup-unbound=true \
  --cleanup-unbound-timeout=1s \
  --admin-console-token='sishpassword'
