### ISSUE TITLE
Is it possible to get the currently connected client information in JSON?

### ISSUE THREAD

**Issue by kamihicouki** [antoniomika/sish#214]
In other words, it's like an API version of admin-console

**Comment by antoniomika** [comment]
Yes there is. The endpoint returns json and the code is available [here](https://github.com/antoniomika/sish/blob/main/utils/console.go#L186). The endpoint returns data that looks like this:

`GET /_sish/api/clients?x-authorization=$admin-console-token`

```json
{
   "clients":{
      "":{
         "listeners":[

         ],
         "pubKey":"",
         "pubKeyFingerprint":"",
         "remoteAddr":"",
         "routeListeners":{
            "httpListeners":{

            },
            "listeners":{
               
            },
            "tcpAliases":{
               
            }
         },
         "session":"",
         "user":"",
         "version":""
      }
   },
   "status":true
}
```

**Comment by antoniomika** [comment]
Just a heads up, changing `clients.{}.pubKey` to be the authorizedkeys format instead of the ssh wire format of the public key (#215). This is for internal uses but might be easier for parsing the actual public key in order areas if you use this API.
