### ISSUE TITLE
Latest Docker images are huge

### ISSUE THREAD

**Issue by pete-woods** [antoniomika/sish#217]
https://hub.docker.com/r/antoniomika/sish/tags

Something changed recently, and your images are >600MiB, when they used to be circa 7MiB.

**Comment by antoniomika** [comment]
Hey @pete-woods 

Huh you're right! Looks like the debug build image is being tagged as latest on this repo instead of my other one. I have a quick fix for it, but in the meantime: images tagged with commit should be the same small size (and based on a scratch image).

**Comment by antoniomika** [comment]
Should be fixed! Back down to the 7mb size 🎉
