### ISSUE TITLE
Trying out

### ISSUE THREAD

**Issue by cedricve** [antoniomika/sish#22]
Hey,

Great solution, trying to make it work. I have setup the pubkey and keys, but when I start the portforward then I got this.

      Starting SSH Fowarding service for http:80. Forwarded connections can be accessed via the following methods:
      HTTP: http://g5u.ssi.sh:80

I run following on the server.

      docker run -itd \
        -v ~/keys/priv:/keys \
        -v ~/keys/pub:/pubkeys \
        -e "DOMAIN=verstraeten.io" \
        --net=host antoniomika/sish:latest \
        -sish.httpsenabled=false \
        -sish.addr=:2222 \
        -sish.http=:80 \
        -sish.keysdir=/pubkeys 

From the client I run.

      ssh -p 2222 -R 80:localhost:3000 178.62.x.y

I have setup my DNS to support wildcards from (verstraeten.io -> 178.62.x.y) and I disabled the firewall for testing (ufw disable).

Any idea? 

Kind regards
Cédric

**Comment by antoniomika** [comment]
Hello!

Did you happen to set `-sish.domain` to the right value (it sounds like `verstraeten.io`)? sish tries to handle virtual hosting dynamically, so the domain would have to be defined for it.

**Comment by antoniomika** [comment]
Hi @cedricve,

Circling back on this, have you had any success getting things working?

**Comment by antoniomika** [comment]
Hi @cedricve,

Gonna close this issue for now. If you have any other issues, feel free to reopen it!
