### ISSUE TITLE
Authentication keys directory: no key found

### ISSUE THREAD

**Issue by sylvainbx** [antoniomika/sish#220]
Hi,
I have an issue with the last versions of sish: using `--authentication-keys-directory=/pubkeys` result in the following error message in the logs: 
```
Can't load file authorized_keys as public key: ssh: no key found
```

Here's the content of the pubkeys directory:
```bash
root@tunnel:/apps/sish# ls -lha pubkeys/
total 16K
drwxr-xr-x 2 root root 4.0K Mar 22 11:04 .
drwxr-xr-x 6 root root 4.0K Mar 29 09:08 ..
-rw------- 1 root root 5.0K Nov  8 10:03 authorized_keys
```

`authorized_keys` is a perfect copy of `/root/.ssh/authorized_keys` which works for connecting to the host through ssh. Also this used to work with the previous version (docker image ID = 0a348c0d7770) but no more since I've updated my installation a few weeks ago (docker image ID = cb7a4d90876e). I've updated to the last version this morning but without any more luck.

**Comment by antoniomika** [comment]
Hey @sylvainbx,

Without actually seeing the file, I'm not too much help. Would you mind sharing that with me? You can also send it to me over email if you'd rather not post it on GitHub.

Best,

**Comment by sylvainbx** [comment]
I sent you the file by email ;)

**Comment by antoniomika** [comment]
Hey @sylvainbx,

So it looks like that message happens because there is a comment at the end of the file and sish can't find a key in that comment (it iterates through the bytes of the file pulling out the public keys).

That being said, that is more a debug statement than an error. sish should still load all of those keys (and you should be able to authenticate with them). What I'm going to do is not log those errors unless debug is enabled and also print out the specific part of the file that is causing those issues.

Be on the lookout for another release in a few hours and let me know if you think that is sufficient.

**Comment by sylvainbx** [comment]
Hi @antoniomika ,
I've updated my installation this morning with the last release and I can confirm that your changes solves the issue.
Thanks a lot!

**Comment by sylvainbx** [comment]
Hi @antoniomika ,
This morning I tried to authenticate to my sish server again, but I failed. I had to switch back to password authentication because the public keys authentication is again asking for a password (although I didn't set one in the config) . No message is provided in the logs. Can we reopen this issue?

Please let me know if you need more info.

**Comment by antoniomika** [comment]
If that's the case it sounds more like the auth mechanism has failed (sish will still fallback to password auth if it's not configured). Have you made any changes to your authorized keys file? Could you please try enabling debug and see if there are any messages in sish that are useful. Could you also use `-vvv` as part of your ssh command to enable debug?

**Comment by sylvainbx** [comment]
I ran into debug mode and saw the message you added the last time:
```
sish           | 2022/04/20 - 07:07:47 | Can't load file authorized_keys:"# Below your custom ssh keys from '/root/.ssh/instance_keys'
sish           | " as public key: ssh: no key found
```
So I removed the comments at the end of the `authorized_keys` file and restarted but without any more luck. Here's the full logs:
- [server](https://pastebin.com/pPnb4RGY)
- [client](https://pastebin.com/jVCUcTVA)

**Comment by antoniomika** [comment]
From looking at the logs, it looks like the public keys are imported just fine. We would see a failed message for each line of the file if nothing was found. 

It didn't look like the client was using an SSH key when it tried auth. Have you changed any of your SSH flags?

**Comment by sylvainbx** [comment]
I get it! When connecting, this little debug message should have warned me but I failed to view it:
```
debug1: Offering public key: /home/sylvain/.ssh/id_rsa RSA SHA256:NHtsu85/9RX9SNvkjJT7Efxs8F3V840u2I0ZHYuhEfA
debug1: send_pubkey_test: no mutual signature algorithm
```

So I changed my ~/.ssh/config file like this and it worked:
```
 Host *
  PubkeyAcceptedKeyTypes +ssh-rsa
  IdentityFile ~/.ssh/id_rsa
```

Sorry for bothering :pray:
