### ISSUE TITLE
Auto redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by sonntuet1997** [antoniomika/sish#222]
Hello,

How do I set up this so that every request sent to the HTTP port will be redirected to the HTTPS port?

**Comment by antoniomika** [comment]
This is not something sish will implement. Look into using a [reverse proxy](https://lmgtfy.app/?q=How+to+Redirect+HTTP+to+HTTPS+in+Nginx) to achieve this.

**Comment by sonntuet1997** [comment]
You mean like setting an Nginx in front of the Sish? Like: client -> nginx -> sish -> local server ? or client -> sish -> nginx -> local server.

The first one would make auto acquiring SSL certificates become difficult. And I tried the second but cannot find the right config
