### ISSUE TITLE
Cannot access port 80 as tcp

### ISSUE THREAD

**Issue by sonntuet1997** [antoniomika/sish#223]
Hello,

I want to create a tunnel that I can access from http://azure.abcd.xyz or https://azure.abcd.xyz. The thing is: I want the Sish server tunnels with my computer via TCP protocol instead of using HTTP/HTTPS. How can I do it?

Here'is my current setting:
<img width="429" alt="Screen Shot 2022-04-04 at 15 00 10" src="https://user-images.githubusercontent.com/33181397/161500003-095243a8-c213-4d15-b348-4281b480dfde.png">

Last tried command: 
<img width="549" alt="Screen Shot 2022-04-04 at 14 43 37" src="https://user-images.githubusercontent.com/33181397/161497083-87e88859-74ff-44b1-b510-ed1289bea836.png">

**Comment by antoniomika** [comment]
You need to set the listen address for http(s) to something other an 80 and 443 as sish cannot do both TCP and HTTPS forwarding on the same port. You also need to remove the `tcp-alias` part of the command.

**Comment by sonntuet1997** [comment]
But I still want to use subdomains.

**Comment by sonntuet1997** [comment]
This is just a trick I came up with because there is something wrong with the basic authentication in the Azure server (Kerberos Authentication Proxy issue).

**Comment by sonntuet1997** [comment]
FYI, you can try to access these links:
http://uetbc.xyz:8080 
http://azure.uetbc.xyz
(Account: testaccount; Pass: !@34abcd)
One with TCP, one with HTTP/HTTPS protocol

**Comment by antoniomika** [comment]
Hrm,

Are either of these supposed to work, because neither actually work for me:

```bash
a@b:~# curl -vvv http://azure.uetbc.xyz -u 'testaccount:!@34abcd' 2>&1 | grep 'HTTP/1.1'
> GET / HTTP/1.1
< HTTP/1.1 401 Unauthorized
a@b:~# curl -vvv http://uetbc.xyz:8080 -u 'testaccount:!@34abcd' 2>&1 | grep 'HTTP/1.1'
> GET / HTTP/1.1
< HTTP/1.1 401 Unauthorized
```

**Comment by sonntuet1997** [comment]
> Hrm,
> 
> Are either of these supposed to work, because neither actually work for me:
> 
> ```shell
> a@b:~# curl -vvv http://azure.uetbc.xyz -u 'testaccount:!@34abcd' 2>&1 | grep 'HTTP/1.1'
> > GET / HTTP/1.1
> < HTTP/1.1 401 Unauthorized
> a@b:~# curl -vvv http://uetbc.xyz:8080 -u 'testaccount:!@34abcd' 2>&1 | grep 'HTTP/1.1'
> > GET / HTTP/1.1
> < HTTP/1.1 401 Unauthorized
> ```

You can try it on the Chrome browser!

**Comment by antoniomika** [comment]
Not sure why chrome would make a difference here. It should work from HTTP basic auth regardless. For example:

Setup a tunnel with httpbin on the other side:

```bash
ssh -R foo:80:httpbin.org:80 -R 8080:httpbin.org:80 ssi.sh
```

And then test auth:

```bash
curl -vvv 'http://foo.ssi.sh:8080/basic-auth/testaccount/!@34abcd' -u 'testaccount:!@34abcd' 2>&1 | grep 'HTTP/1.1'
> GET /basic-auth/testaccount/!@34abcd HTTP/1.1
< HTTP/1.1 200 OK

curl -vvv 'http://foo.ssi.sh/basic-auth/testaccount/!@34abcd' -u 'testaccount:!@34abcd' 2>&1 | grep 'HTTP/1.1'
> GET /basic-auth/testaccount/!@34abcd HTTP/1.1
< HTTP/1.1 200 OK
```

And with a wrong password:

```bash
curl -vvv 'http://foo.ssi.sh/basic-auth/testaccount/!@34abcd' -u 'testaccount:!@34abc' 2>&1 | grep 'HTTP/1.1'
> GET /basic-auth/testaccount/!@34abcd HTTP/1.1
< HTTP/1.1 401 Unauthorized

curl -vvv 'http://foo.ssi.sh:8080/basic-auth/testaccount/!@34abcd' -u 'testaccount:!@34abc' 2>&1 | grep 'HTTP/1.1'
> GET /basic-auth/testaccount/!@34abcd HTTP/1.1
< HTTP/1.1 401 UNAUTHORIZED
```

So looks like something else is wrong (not with sish).

**Comment by sonntuet1997** [comment]
I don't know. But please try it on a browser instead of a terminal. 

> Not sure why chrome would make a difference here. It should work from HTTP basic auth regardless. For example:
> 
> Setup a tunnel with httpbin on the other side:
> 
> ```shell
> ssh -R foo:80:httpbin.org:80 -R 8080:httpbin.org:80 ssi.sh
> ```
> 
> And then test auth:
> 
> ```shell
> curl -vvv 'http://foo.ssi.sh:8080/basic-auth/testaccount/!@34abcd' -u 'testaccount:!@34abcd' 2>&1 | grep 'HTTP/1.1'
> > GET /basic-auth/testaccount/!@34abcd HTTP/1.1
> < HTTP/1.1 200 OK
> 
> curl -vvv 'http://foo.ssi.sh/basic-auth/testaccount/!@34abcd' -u 'testaccount:!@34abcd' 2>&1 | grep 'HTTP/1.1'
> > GET /basic-auth/testaccount/!@34abcd HTTP/1.1
> < HTTP/1.1 200 OK
> ```
> 
> And with a wrong password:
> 
> ```shell
> curl -vvv 'http://foo.ssi.sh/basic-auth/testaccount/!@34abcd' -u 'testaccount:!@34abc' 2>&1 | grep 'HTTP/1.1'
> > GET /basic-auth/testaccount/!@34abcd HTTP/1.1
> < HTTP/1.1 401 Unauthorized
> 
> curl -vvv 'http://foo.ssi.sh:8080/basic-auth/testaccount/!@34abcd' -u 'testaccount:!@34abc' 2>&1 | grep 'HTTP/1.1'
> > GET /basic-auth/testaccount/!@34abcd HTTP/1.1
> < HTTP/1.1 401 UNAUTHORIZED
> ```
> 
> So looks like something else is wrong (not with sish).

**Comment by sonntuet1997** [comment]
<img width="890" alt="Screen Shot 2022-04-09 at 22 07 46" src="https://user-images.githubusercontent.com/33181397/162579842-52f65b75-6e17-47c1-aebb-27e087b34bb9.png">
<img width="1439" alt="Screen Shot 2022-04-09 at 22 08 03" src="https://user-images.githubusercontent.com/33181397/162579847-1e830dcc-525e-4392-9300-5fb9dbe9af83.png">

**Comment by antoniomika** [comment]
I'm getting a 404 with the azure.uetbc.xyz address, is this expected?

**Comment by sonntuet1997** [comment]
> I'm getting a 404 with the azure.uetbc.xyz address, is this expected?

Yes, I forgot to keep the machine alive. Fixed it!
