### ISSUE TITLE
Wildcard forwarding

### ISSUE THREAD

**Issue by sonntuet1997** [antoniomika/sish#224]
Hello,

Can I use something like: ``bash
ssh -R *.foo:80:localhost:80 sish.xyz
`` to forward all requests from *.foo.sish.xyz to my local machine?

**Comment by antoniomika** [comment]
This isn't something that sish currently supports, but I don't really see a reason why it doesn't have this feature. I'll look at implementing that today.

**Comment by antoniomika** [comment]
On second thought, because you can't bind wildcards of wildcards via sish I don't think this feature would be best served by sish. I think this is another place where a reverse proxy can be used.

**Comment by sonntuet1997** [comment]
I can set DNS to bind specific subdomain, like: 
*.foo.sish.xyz => myPublicIP.
*.sish.xyz => myPublicIP.

**Comment by sonntuet1997** [comment]
Or at least I want it to forward all requests to my server (only has private IP)
