### ISSUE TITLE
Support for HTTP/3

### ISSUE THREAD

**Issue by sonntuet1997** [antoniomika/sish#227]
Hi,

I'm wondering if this proxy could support HTTP/3?

**Comment by antoniomika** [comment]
Because HTTP3 utilizes QUIC (and therefore UDP), SSH tunnels are not able to forward this traffic type and is therefore not supported.

**Comment by gedw99** [comment]
You can forward quic through web sockets I believe. 

@antoniomika if your interested I can find a go package that does this. I am on mobile

**Comment by antoniomika** [comment]
Hey @gedw99,

Yes please! Any help finding the libraries will get us closer to implementation.

**Comment by gedw99** [comment]
hey @antoniomika have a look here: https://github.com/yomorun/yomo-presence-backend

it might help, but have not had much time to dig into it.

There are also a few other golang projects using quit and websockets together
