### ISSUE TITLE
SISH not stable

### ISSUE THREAD

**Issue by gvsurenderreddy** [antoniomika/sish#23]
SISh is crashing a lot .It's not stable as serveo.net.  Time to Time  it crashes and generate new keys sir is it possible to use the same old generated keys from SISH instead of new keys from SISH when it restart.

**Comment by antoniomika** [comment]
Do you have any of the stack traces from where it would crash? I haven't had any experience with this (my instance has been running for >>>2mo without an issue). With regards to persisting the host keys, make sure the path defined by ` -sish.pkloc` (default "keys/ssh_key") is persisted between reboots.

**Comment by antoniomika** [comment]
Closing this for now as I've had no response.

**Comment by gvsurenderreddy** [comment]
Yes i have defined hotkeys -sish.pkloc /etc/ssh after reboot it doesn't take old keys sish generates new on server and on client i have remove old keys and make new ssh .

**Comment by antoniomika** [comment]
Hmm, are you running this in docker? If you are, is `/etc/ssh` persistent or does it only live with the container? If you're not using docker, do the permissions on `/etc/ssh` allow for the user running `sish` to access the directory?

**Comment by gvsurenderreddy** [comment]
Okay Sir.I'm not a fan of Docker i'm using standalone application.Sir 1 more question how can i know which subdomains are be assigned by SISH and can i also give a time out for the subdomain that be used ,The reason i'm testing your service since long time When i do reboot Client machine once the client Machine is on when i try that subdomain i get the message its being used .IS there is anyway that I can remove the subdomains which are not being used and reassign back.

Finally Thanks for the great effort and time making such as beauty .

**Comment by gvsurenderreddy** [comment]
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:Gv9heo5UQeK7NuBSWqzfnioEr/kKdZcGUdOlKg6XJAs.
Please contact your system administrator.
Add correct host key in /root/.ssh/known_hosts to get rid of this message.
Offending RSA key in /root/.ssh/known_hosts:1

SISH fails and it restarts and the keys are changed
