### ISSUE TITLE
Client side cli

### ISSUE THREAD

**Issue by gedw99** [antoniomika/sish#233]
Very cool project 

i noticed that the user needs to do sone technical things in order to setup things on their desktop 

the steps seem to be here : https://github.com/antoniomika/sish/blob/main/deploy/gcloud.md

would a cli for users be a good idea ? 
it would essentially automate as many of the steps as possible for a user to interact with an already setup server.

**Comment by antoniomika** [comment]
Thanks for the kind words!

The installation part of sish is a bit out of purview for the client, as the whole goal is to try and use SSH as much as possible. 

Setup is only required once, and the google compute engine setup is pretty easy to follow using their interactive tutorials page ([here](https://ssh.cloud.google.com/cloudshell/editor?shellonly=true&cloudshell_git_repo=https%3A%2F%2Fgithub.com%2Fantoniomika%2Fsish&cloudshell_git_branch=main&cloudshell_tutorial=deploy%2Fgcloud.md)). I'd prefer to leave install to operators as we provide docker images and binaries for all different types of operating systems and architectures. Happy to add more instructions or example manifests to the wiki though if there are some you'd like to contribute!
