### ISSUE TITLE
Tunnel the same host/port to multiple destinations at the same time

### ISSUE THREAD

**Issue by oprypkhantc** [antoniomika/sish#235]
Hey.

Currently, sish supports `--http-load-balancer` option, which allows forwarding HTTP requests to multiple destinations. The feature I'm requesting is a similar behaviour, but instead of selecting one destination and tunneling the request, sish would instead forward the HTTP request to all destinations at once and return a predefined HTTP response (from a different host/endpoint?). 

This is likely outside of the scope of sish, but it's worth asking.

**Comment by antoniomika** [comment]
Unfortunately this is out of the scope of sish. There are other proxy solutions that are dedicated to that use case (traffic mirroring), such as [haproxy](https://www.haproxy.com/de/blog/haproxy-traffic-mirroring-for-real-world-testing/). Sorry!

(reason it is out of scope is sish just implements a simple round robin balancer. anything more complex than that should really be a separate project)
