### ISSUE TITLE
Asking for a password

### ISSUE THREAD

**Issue by raghunrv** [antoniomika/sish#236]
```
The authenticity of host '[ssi.sh]:2222 ([104.225.216.27]:2222)' can't be established.
ED25519 key fingerprint is SHA256:jJDD2ObGNkf9euI7ZVB9Qy+GhZU0FQE1+pUwlvsBVJE.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '[ssi.sh]:2222,[104.225.216.27]:2222' (ED25519) to the list of known hosts.
username@ssi.sh's password: 
```
Asking for password not sure which password and where to get it

**Comment by antoniomika** [comment]
Hey @kerostampcrab,

Unfortunately, the demo instance at ssi.sh is no more. I removed that from the README as I had to deal with abuse.

You can however run your own sish instance in google cloud for free forever. Just follow the instructions here: https://github.com/antoniomika/sish#google-cloud-platform
