### ISSUE TITLE
TCP alias rejecting uppercase letters

### ISSUE THREAD

**Issue by blop** [antoniomika/sish#237]
Hello,

It seems that the named TCP alias feature doesn't accept any uppercase letter.

The following commands are working : 
```
ssh -R local:22:127.0.0.1:22 sish.server
ssh -R loc-al:22:127.0.0.1:22 sish.server
ssh -R local123:22:127.0.0.1:22 sish.server
```

The following commands are NOT working ("remote port forwarding failed for listen port") : 
```
ssh -R Local:22:127.0.0.1:22 sish.server
ssh -R locAl:22:127.0.0.1:22 sish.server
ssh -R LOCAL:22:127.0.0.1:22 sish.server
```

As hostnames are case insensitive and we need to avoid collisions, shouldn't sish just lowercase the user input instead of throwing an error ? (same for -L tunnels)

Thank you!

Olivier

**Comment by antoniomika** [comment]
Hey @blop,

Hrm this is actually how the functionality is currently implemented (and works for me as well). What version of sish are you running?

PS: hope you’ve been well! Haven’t seen you around here in a bit!

Best,

**Comment by antoniomika** [comment]
Awesome, good to hear!

I see the issue now, it's because of `force-requested-aliases`. That function also needs to lowercase the addresses (which is wasn't). I pushed the fix and it'll be released as v2.4.1!

**Comment by blop** [comment]
Thank you !
It works in 2.4.1.

**Comment by blop** [comment]
@antoniomika It seems to be broken again since version 2.5.0, and still in 2.8.1 :o 

```
WARNING: Server requests forwarding for unknown listen_port 22
ssh: rejected: administratively prohibited (open failed)
```

**Comment by antoniomika** [comment]
Should be fixed in v2.9.1!

**Comment by blop** [comment]
@antoniomika Still not working in v2.9.1 :'(

**Comment by antoniomika** [comment]
```
ssh -R aSDF:22:localhost:22 ssi.sh
Press Ctrl-C to close the session.

Starting SSH Forwarding service for tcp:22. Forwarded connections can be accessed via the following methods:
TCP Alias: asdf:22

Connection to ssi.sh closed by remote host.
Connection to ssi.sh closed.
```

Works for me! What's the configuration you're using?

**Comment by blop** [comment]
It fails when trying to actually connect to the TCP alias, not when setting it up.

tunnel side we get : 
`WARNING: Server requests forwarding for unknown listen_port 22
ssh: rejected: administratively prohibited (open failed)`

client side we get :
`kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535`

Same configuration as above ;-)

**Comment by antoniomika** [comment]
@blop Now this is fixed :)

**Comment by blop** [comment]
Yeah! It's working fine in v2.9.2 ;-)
Thanks !
