### ISSUE TITLE
Can't disable TCP aliases

### ISSUE THREAD

**Issue by FloatingMind12** [antoniomika/sish#239]
Hi again
I always get a TCP alias when I request a tunnel with subdomain with the `ssh -p 2222 -R subdomain:xx:localhost:xx domain.com` command even if I add a `--tcp-aliases=false` argument. I instead except something like **tcp://subdomain.domain.com:xx** to come out
Am I actually misunderstanding things?

Here is my full arguments list by the way
```
--domain=domain.com
--ssh-address=:2222
--http-address=:80
--https=false
--tcp-aliases=false
--authentication-keys-directory=/pubkeys
--private-keys-directory=/keys
--bind-random-ports=false
--bind-random-subdomains=false
--log-to-client=true
--ping-client-timeout=2m
--log-to-file=true
--log-to-file-path=/logs/sish.log
--cleanup-unauthed-timeout=2m
--idle-connection=false
--bind-random-aliases=false
```

**Comment by antoniomika** [comment]
Subdomains will only be assigned if the port used is an http(s) port, otherwise a TCP Alias is used. Are you trying to use http(s) forwards?

**Comment by FloatingMind12** [comment]
As I said I expect something like **tcp://subdomain.domain.com:xx** but I guess it's not possible so I'll just make do with the domain root
Thanks for confirming my doubt anyway
