### ISSUE TITLE
Create multiple reverse tunnels in separate SSH commands

### ISSUE THREAD

**Issue by seyuboglu** [antoniomika/sish#252]
I'm able to make multiple reverse tunnels with a single SSH command like so: 
```
ssh -p 2222 -R abc:80:localhost:1234  -R xyz:80:localhost:6789 YOURDOMAIN
```

However, if you don't know up front how many tunnels you will need, it may be necessary to establish the tunnels in separate SSH comands. 
```
ssh -p 2222 -R abc:80:localhost:1234 YOURDOMAIN
ssh -p 2222 -R xyz:80:localhost:6789 YOURDOMAIN
```

When I try to establish the second connection I get:
```
mux_client_request_session: read from master failed: Broken pipe
ssh: connect to host YOURDOMAIN port 2222: Connection refused
```
and the first connection closes with `Shared connection to YOURDOMAIN closed.`

Note that its possible to reproduce this without the tunneling:
```
ssh -p 2222
ssh -p 2222
```

How is the ssh server in sish configured to handle multiple connections? Is there a recommended way of doing this in sish?

**Comment by antoniomika** [comment]
Hey @seyuboglu,

sish handles this complete fine actually, it should not be an issue connecting multiple clients. 

Are you using ControlMaster? That's something that sish does not support unfortunately.

Best,
