### ISSUE TITLE
Login password to SSI.sh

### ISSUE THREAD

**Issue by speusippo** [antoniomika/sish#264]
Hi,
thanks for your service. I'm mistaking something.
If I try with ssh -R jacopo:80:localhost:80 ssi.sh I get a response with login and password from ssi.sh.

I don't know ssi.sh login, of course. What I'm doing wrong?

J.

**Comment by antoniomika** [comment]
Please refer here:

https://github.com/antoniomika/sish/issues/201#issuecomment-988937007
