### ISSUE TITLE
Use Case Remote Connection to repair system

### ISSUE THREAD

**Issue by jkksqd** [antoniomika/sish#267]
Hello,
first off, thanks for developing this program and making it available to the world. I am looking for a program that lets me connect to a few different computers behind routers that have no port-forwarding available. That is where I stumbled upon `sish`.

Is it possible to just run a vps with the docker image at an arbitrary domain, i.e. sish.myremoteconnection.com  and then initiate a connection via ssh between my local machine and each of my remote computers (one at a time) via this vps?

Do I have to keep a constant connection between my remote computers and the vps? Meaning that the remote computer has to initiate the ssh connection? Or does it suffice that they ping my vps, i know their addresses and then change the configuration accordingly on the vps and can then connect from my local pc to the remote computer?  Meaning I initiate with my local machine to the remote computer but only after changing the config on the vps?

Sorry if this was already been questioned, I searched the issues and did not find a 100% similar use case.

**Comment by antoniomika** [comment]
Hey @jkksqd 

Yep, this is a valid use case for sish. Unfortunately, any services you'd want to connect to through sish need to establish a tunnel connection to sish (meaning a constant connection would be needed).

**Comment by jkksqd** [comment]
hey @antoniomika ,
thank you for your fast response. 

Best wishes

Jack
