### ISSUE TITLE
sh -R 2222:localhost:22 ssi.sh Permission denied

### ISSUE THREAD

**Issue by Thandibirani** [antoniomika/sish#270]
sh -R 2222:localhost:22 ssi.sh
account_name@ssi.sh's password: 
Permission denied, please try again.
account_name@ssi.sh's password: 
Connection closed by 199.241.136.212 port 22

help please

**Comment by bibo38** [comment]
You need to set up your own instance. See https://github.com/antoniomika/sish/issues/201#issuecomment-988937007

**Comment by eduardscript** [comment]
I have the same problem
