### ISSUE TITLE
websocket connections will be closed once a while

### ISSUE THREAD

**Issue by eslym** [antoniomika/sish#274]
the websocket connection keep getting closed after few seconds, i looking through the logs and found this line

```
time="2023-06-08T07:13:33Z" level=error msg="vulcand/oxy/forward/websocket: Error when copying from backend to client: websocket: close 1006 (abnormal closure): unexpected EOF"
```

**Comment by antoniomika** [comment]
This likely occurs because of idle timeout checks. You can disable them by setting `--idle-connection=false`. You can also ensure that your websocket is properly being pinged in order to not hit the timeout instead.
