### ISSUE TITLE
URL string replacement in the returned HTML

### ISSUE THREAD

**Issue by nczz** [antoniomika/sish#289]
Hi, thank you for open-sourcing such a great project!

During my usage, I found that if the HTML content outputted by my program contains absolute paths instead of relative paths, the links in the resulting document will become invalid.

I would like to inquire if it would be possible to add a 'URL replacement' parameter and functionality, so that the HTML content can replace the current domain used for browsing?

**Comment by antoniomika** [comment]
Sorry for the delay.

I think this is out of scope for sish. You can use a reverse proxy such as Caddy or Nginx to do this.

Thanks for reaching out!
