### ISSUE TITLE
How to change domain name?

### ISSUE THREAD

**Issue by 0xh4di** [antoniomika/sish#29]
How can I change ssi.sh domain name and deploy on custom domain name or use server IP address instead?

**Comment by antoniomika** [comment]
You set the domain to use with the following flag that is listed in the readme:
```
  -sish.domain string
        The domain for HTTP(S) multiplexing (default "ssi.sh")
```
You are able to use the IP address to establish an ssh connection to sish, but you are not able to use the IP address to connect over HTTP, only TCP. The reason for this is the HTTP(S) handler requires the hostname to be sent to the server, which it is unable to be in these situations.
