### ISSUE TITLE
Feature request: allow reading password from file

### ISSUE THREAD

**Issue by amospalla** [antoniomika/sish#299]
Hello,

actualy sish allows setting a password with the `--authentication-password=` parameter but that exposes the password to any local user who is able to list processes.

The request would be to add a parameter like `--authentication-password-file=` which tells sish to read a password from the specified file, this way it can not be read by anyone except by the user executing the process.

**Comment by antoniomika** [comment]
This is actually already supported. You can use a config file ([like this](https://github.com/antoniomika/sish/blob/main/config.example.yml)) to provide any command line flags (including password).

I've also just fixed environment variable settings as well. So you can provide it as an env var by setting: `SISH_AUTHENTICATION_PASSWORD`. The env setting follows a similar template for all other variables, `SISH_` followed by the setting in uppercase, with the `-` replace with a `_`.

Hope this helps!

**Comment by amospalla** [comment]
Oh, I've searched for this before and never found it, obviously I didn't search well enough.

I was convinced something like this didn't exist.

Thank you very much.

**Comment by antoniomika** [comment]
Not a problem! We've overhauled the sish documentation but probably could do a better job of highlighting the different ways to configure it!
