### ISSUE TITLE
Is it possible to run it in debain or openwrt running in Rasberry Pi

### ISSUE THREAD

**Issue by Eldho1416** [antoniomika/sish#305]
Hi,

I have no much idea about ssh tunneling, I tried running in debian as instructed and i'm getting this error
```
# runtime/cgo
gcc: error: unrecognized command-line option '-marm'
```

**Comment by antoniomika** [comment]
Hey @Eldho1416 

Yep, any golang supported OS/architecture should be supported. Are you attempting to build binaries yourself? If so, make sure to disable CGO using `CGO_ENABLED=0`.

**Comment by Eldho1416** [comment]
He me understand this, i need to build binaries in the sever or client?

Is it possible to run this my own server? 

I feel so dumb please me with a guide if any 😅

**Comment by antoniomika** [comment]
Yep, you can run this on your own server.

You only need to build binaries for your server, the client is just ssh. There's no guide other than installing Go locally and using `go build cmd/sish.go` and executing the resultant program.

**Comment by Eldho1416** [comment]
I'm sorry to ask this. I have raspberry (A) and i have a aws server (B) and i have My laptop (C)

I want to access A using C via B is this possible? And i need to build binaries in B?

**Comment by antoniomika** [comment]
This is possible and no you don't need to build any binaries. You can follow the install guide [here](https://docs.ssi.sh/getting-started). You can also download a binary from the GitHub Releases and install it yourself.

**Comment by Eldho1416** [comment]
Okay i will try it out thank you for the help

**Comment by antoniomika** [comment]
Yep, no problem! I'll close this, but feel free to message here or IRC if you need more help!
