### ISSUE TITLE
Nested subdomain routerd but without proper https handling

### ISSUE THREAD

**Issue by ptrbojko** [antoniomika/sish#314]
Hi there, I've deployed sish along with dnscertbot as per docs.

Everything works as desired except when trying to setup nested subdomain

```
ssh -p 2222 -o ServerAliveInterval=60 -o HostKeyAlgorithms=+ssh-rsa -R domain:80:localhost:80 -R subdomain.domain:80:localhost:80  mytnlserver.com 

Press Ctrl-C to close the session.

Starting SSH Forwarding service for http:80. Forwarded connections can be accessed via the following methods:
HTTP: http://domain.mytnlserver.com
HTTPS: https://domain.mytnlserver.com

Starting SSH Forwarding service for http:80. Forwarded connections can be accessed via the following methods:
HTTP: http://subdomain.domain.mytnlserver.com
HTTPS: https://subdomain.domain.mytnlserver.com
```

And then 
1 http://domain.mytnlserver.com works as desired
2 https://domain.mytnlserver.com works as desired with proper wildcard certyficate
3 http://subdomain.domain.mytnlserver.com works as desired
4 https://subdomain.domain.mytnlserver.com DOES NOT WORK

Is nested subromain supported?

**Comment by antoniomika** [comment]
Hi @ptrbojko 

It is supported, but you need to generate your own certificate for `*.domain.mytnlserver.com` or enable on demand certificates from let's encrypt.

Closing this for now, feel free to comment if you have any other issues.
