### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by wdhdev** [antoniomika/sish#319]
Hi, I was wondering if IPv6 is supported by sish? I currently run it on IPv4, however I want to add IPv6 support as well, how would I do that?

**Comment by antoniomika** [comment]
IPv6 is indeed supported by sish!

To use IPv6, set your listen addresses to a comma separated string of addresses. For example:

```
      --tcp-address=tcp://192.168.1.1,tcp6://[fdf6:a22a:2e47:fd87::1]
      --ssh-address=tcp://192.168.1.1:22,tcp6://[fdf6:a22a:2e47:fd87::1]:22
      --http-address=tcp://192.168.1.1:80,tcp6://[fdf6:a22a:2e47:fd87::1]:80
      --https-address=tcp://192.168.1.1:443,tcp6://[fdf6:a22a:2e47:fd87::1]:443
```

**Comment by wdhdev** [comment]
Thanks! I think this would be a good addition to the docs for any one in the future wanting IPv6 support :)
