### ISSUE TITLE
Port Reallocation

### ISSUE THREAD

**Issue by capriciousduck** [antoniomika/sish#32]
Hi, I created a tunnel using 22000 as ssh port in my client machine. I exited the session and I used the same port in another machine, but now I am not able to ssh the machine. I am not able to reallocate the port previously used.

I hosted my sish server on my aws server.

**Comment by antoniomika** [comment]
Did the session fully exit or was there a network loss? If it was network loss this can happen but it should be freed once the timeout occurs (depends on the socket). I haven't been able to reproduce with normal exits though.
