### ISSUE TITLE
Add Versioning

### ISSUE THREAD

**Issue by dpishchukhin** [antoniomika/sish#36]
Hi @antoniomika,

can you add versions to your binaries and Docker images to track changes?

**Comment by antoniomika** [comment]
@dpishchukhin are you looking for something more than tagging images based on commit hash? Main reason I ask is because I don't distribute binaries other than for docker (but I could look into adding those if you think they'd be worthwhile).

**Comment by dpishchukhin** [comment]
@antoniomika docker image tags are good. It would be great to add `sish version` command to see a version. the version could be a timestamp from my point of view.

**Comment by antoniomika** [comment]
@dpishchukhin I just added auto-building for sish (go binaries added to releases as well as versioned docker images). The docker images are tagged based on git version tag as well as commit hash. I've also added a `-sish.version` flag to print binary version information. Let me know if you have any other issues!

**Comment by dpishchukhin** [comment]
@antoniomika great! thank you!
