### ISSUE TITLE
Use on Windows without Docker

### ISSUE THREAD

**Issue by Deilan** [antoniomika/sish#41]
Is there a way to use it on Windows 7+ without Docker?

**Comment by antoniomika** [comment]
Hi @Deilan,

I personally haven't tested this, but theoretically if the version of Windows you have has support for `AF_UNIX` I think it would work. I also don't have any Windows computers to test on sadly. Would you be able to help with that?

**Comment by Deilan** [comment]
Hey @antoniomika!

Yep, let's try this out!

Would you post instructions here or should I email you so we can continue to communicate via e-mail or messenger?

**Comment by antoniomika** [comment]
I can post the instructions here! Would you be comfortable if I just created a Windows binary and uploaded here or would you like to try to compile it on your own?

**Comment by Deilan** [comment]
Let's try your binaries, and if something goes wrong, I will try to build it myself :)

**Comment by antoniomika** [comment]
@Deilan Here you go! Let me know how it goes:

[sish.exe.zip](https://github.com/antoniomika/sish/files/3841791/sish.exe.zip)

**Comment by Deilan** [comment]
Unpacked and launched it successfully:

https://i.imgur.com/K9h7A1I.png

I guess it needs some additional configuration now

**Comment by antoniomika** [comment]
Cool! Go ahead and create the two directories `pubkeys` and `keys` in the same directory that sish is. Go ahead and start the process with `-sish.auth=false -sish.debug=true -sish.subdomainlen=3 -sish.httpsenabled=false -sish.http=localhost:8081 -sish.addr=localhost:2222 -sish.domain=testing.ssi.sh -sish.forcerandomsubdomain=false -sish.bindrandom=false -sish.tcpalias=true -sish.proxyprotoenabled=false` set as process flags. Once that's running, you should be able to `ssh -R test:80:httpbin.org:80 localhost -p 2222`, and then access `http://test.testing.ssi.sh`!

**Comment by antoniomika** [comment]
@Deilan looks like the binaries work fine! I'm gonna add the ability to auto build those and then will close this issue!
