### ISSUE TITLE
Connection to sish-host.com closed by remote host.

### ISSUE THREAD

**Issue by BenHarris** [antoniomika/sish#42]
Hey, love the project and mostly working well! I have got the server up and running (currently on an AWS EC2 instance). I can connect to it from all of the following with a standard `ssh -oStrictHostKeyChecking=no -p 2222 -R ben:80:localhost:80 sish-host.com`
- [x] Remote CentOS Server
- [x] Windows PowerShell
- [x] Local docker container (docker exec -it xxxxxxx sh)

But the second I run this within a container (docker run or compose), it just fails. I've tried just about everything I could think of, but can't work it out. This is the `ssh -v` output
```OpenSSH_8.1p1, OpenSSL 1.1.1d  10 Sep 2019
debug1: Reading configuration data /etc/ssh/ssh_config
Pseudo-terminal will not be allocated because stdin is not a terminal.
debug1: Connecting to sish-host.com [99.99.99.99] port 2222.
debug1: Connection established.
debug1: identity file /root/.ssh/id_rsa type -1
debug1: identity file /root/.ssh/id_rsa-cert type -1
debug1: identity file /root/.ssh/id_dsa type -1
debug1: identity file /root/.ssh/id_dsa-cert type -1
debug1: identity file /root/.ssh/id_ecdsa type -1
debug1: identity file /root/.ssh/id_ecdsa-cert type -1
debug1: identity file /root/.ssh/id_ed25519 type -1
debug1: identity file /root/.ssh/id_ed25519-cert type -1
debug1: identity file /root/.ssh/id_xmss type -1
debug1: identity file /root/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.1
debug1: Remote protocol version 2.0, remote software version Go
debug1: no match: Go
debug1: Authenticating to sish-host.com:2222 as 'root'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-rsa SHA256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
debug1: checking without port identifier
Warning: Permanently added '[sish-host.com]:2222,[99.99.99.99]:2222' (RSA) to the list of known hosts.
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /root/.ssh/id_rsa
debug1: Will attempt key: /root/.ssh/id_dsa
debug1: Will attempt key: /root/.ssh/id_ecdsa
debug1: Will attempt key: /root/.ssh/id_ed25519
debug1: Will attempt key: /root/.ssh/id_xmss
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentication succeeded (none).
Authenticated to sish-host.com ([99.99.99.99]:2222).
debug1: Remote connections from ben:80 forwarded to local address localhost:80
debug1: channel 0: new [client-session]
debug1: Entering interactive session.
debug1: pledge: network
Press Ctrl-C to close the session.
Starting SSH Fowarding service for http:80. Forwarded connections can be accessed via the
following methods:
HTTP: http://ben.sish-host.com:80
HTTPS: https://ben.sish-host.com:443
debug1: channel 0: free: client-session, nchannels 1
debug1: fd 0 clearing O_NONBLOCK
debug1: fd 2 clearing O_NONBLOCK
Connection to sish-host.com closed by remote host.
Transferred: sent 1700, received 1512 bytes, in 0.0 seconds
Bytes per second: sent 42334.2, received 37652.5
debug1: Exit status -1
sish_1 exited with code 255
```

This is the server-side
```
15:44:05 Accepted SSH connection for: 44.44.44.44:58208
15:44:05 Main Channel Info session
15:44:05 Handling session for connection: &{session [] 0 0 32768 32768 0xc000162a10 true 0 0xc000205740 {0 0} 0xc0002056e0 false {0xc00014be40 2097152 0 false} 0xc000208f00 0xc000208f40 {0 0} 2097152 {0 0} false map[]}
15:44:05 Main Request Info tcpip-forward true benP
15:44:05 Error trying to write message to socket: read tcp 10.0.2.4:2222->44.44.44.44:58208: use of closed network connection
15:44:05 Closed SSH connection for: 44.44.44.44:58208 user: root
15:44:13 =======Start=========
15:44:13 ===Goroutines=====
15:44:13 10
15:44:13 ===Listeners======
15:44:13 [::]:2222 &{0xc0000cf500 {<nil> 0}}
15:44:13 ===Clients========
15:44:13 ===HTTP Clients===
15:44:13 ========End==========
```

Where 99.99.99.99 is sish on the EC2 server and 44.44.44.44 is my local IP.

I have been using this as a basis https://github.com/jacobtomlinson/docker-serveo. It works fine with my serveo instance on the same 99.99.99.99 server. For the purposes of testing, I created a minimal Dockerfile, which is confirmed and working with Serveo, but not with sish.
```
FROM alpine:3

RUN apk --no-cache add openssh
ENTRYPOINT ["ssh", "-v", "-oStrictHostKeyChecking=no", "-p", "2222", "-R", "ben:80:localhost:80", "sish-host.com"]
```

Here are my sish params
```
      -sish.addr=:2222
      -sish.auth=false
      -sish.https=:443
      -sish.http=:80
      -sish.httpsenabled=true
      -sish.httpspems=/etc/letsencrypt/live/sish-host.com
      -sish.keysdir=/pubkeys
      -sish.password=""
      -sish.pkloc=/keys/ssh_key
      -sish.bindrandom=false
      -sish.domain=sish-host.com
      -sish.forcerandomsubdomain=false
      -sish.debug=true
```

If I can do anything to support, please let me know. Thanks again!

**Comment by BenHarris** [comment]
I'm extremely new to Golang, so in a little over my head, but it looks like the issue is manifesting in channels.go around line 51. My understanding is that the client isn't sending any data - maybe because it's not interactive? It means err == io.EOF, but even though that is the case, it seems we don't want to close it as the connection is still active.

Commenting out the break in `case <-sshConn.Close:` and the break after the `select` allows it to work, but the connection is then not cleaned up when you kill the client. It's not so bad if you are using random subdomains, but you can't use your custom subdomain again until you restart the server.

Not sure if it helps, but when it dies (instantly), the following are set
dataRead = 4
data = 120

**Comment by antoniomika** [comment]
@BenHarris so I have a fix in #45 for this issue. Your problem looks to be a bit different from #44, but the fix for you can benefit from the that PR and I'll merge it soon. For your docker example, you need to either start SSH with the `-N` flag to tell SSH to not run a remote command and to keep the session open. You can also start the container with the `-i` or `-t` flag to tell docker to either make the session interactive or allocate a TTY, that way SSH will know to keep the session open.

**Comment by BenHarris** [comment]
@antoniomika hope you're enjoying KubeCon! Thanks for the update - looks like good progress. Few things from my end

1) `ssh -v -t -oStrictHostKeyChecking=no -p 2222 -R ben:80:localhost:80 sish-host.com` and  `ssh -v -tt -oStrictHostKeyChecking=no -p 2222 -R ben:80:localhost:80 sish-host.com` now cause a panic. Whether it should work or not, it should probably be handled slightly more gracefully.
```
2019/11/20 07:50:07 Accepted SSH connection for: 44.44.44.44:59130
2019/11/20 07:50:07 Closed SSH connection for: 44.44.44.44:59130 user: root
panic: send on closed channel
goroutine 326 [running]:

main.sendMessage(0xc000021180, 0xadde18, 0x3a)
       /app/utils.go:396 +0x10e
main.getOpenHost.func1.2(0xc00049be01)
       /app/utils.go:305 +0x5b
main.getOpenHost.func1.3(0xc00049bee0, 0x12, 0xc00049bee0)
       /app/utils.go:311 +0xdb
main.getOpenHost.func1(0x6f, 0x100)
       /app/utils.go:322 +0x17f
main.getOpenHost(0xc000126cc0, 0x9, 0xc000139cb0, 0xc000021180, 0x2, 0xc000052380)
       /app/utils.go:328 +0x77
main.handleRemoteForward(0xc0000211c0, 0xc000021180, 0xc000139cb0)
       /app/requests.go:118 +0x756
main.handleRequest(0xc0000211c0, 0xc000021180, 0xc000139cb0)
       /app/handle.go:24 +0x132
created by main.handleRequests
       /app/handle.go:16 +0x71
```

2) `ssh -v -n -oStrictHostKeyChecking=no -p 2222 -R ben:80:localhost:80 sish-host.com` causes a slightly different panic, but looks to be ultimately the same issue as 1:
```
2019/11/20 07:56:38 Accepted SSH connection for: 44.44.44.44:56906
2019/11/20 07:56:38 Error trying to write message to socket: read tcp 10.0.2.4:2222->44.44.44.44:56906: use of closed network connection
2019/11/20 07:56:38 Closed SSH connection for: 44.44.44.44:56906 user: root
panic: send on closed channel

goroutine 28 [running]:
main.sendMessage(0xc000141780, 0xc00008da20, 0xac)
       /app/utils.go:396 +0x10e
main.handleRemoteForward(0xc0001417c0, 0xc000141780, 0xc000139cb0)
       /app/requests.go:147 +0xa3f
main.handleRequest(0xc0001417c0, 0xc000141780, 0xc000139cb0)
       /app/handle.go:24 +0x132
created by main.handleRequests
       /app/handle.go:16 +0x71
```

3) You no-longer get the `This subdomain is unavaible. Assigning a random subdomain.` When attempting to use a subdomain, which is already in use
```
Press Ctrl-C to close the session.

Starting SSH Fowarding service for http:80. Forwarded connections can be accessed via the following methods:
HTTP: http://py2.sish-host.com:80
HTTPS: https://py2.sish-host.com:443
```

4) Using the `-N` flag isn't really practical as you then don't get the output from the server. Just:
```
Setting up forwarding from ben:sish-host.com to localhost:80
Warning: Permanently added 'sish-host.com]:2222,[99.99.99.99]:2222' (RSA) to the list of known hosts.
```

As above, I could see it working with `-it`. I'm running the the client as a docker-compose service for local development. The idea being that you run `docker compose up` and you get your whole environment and an exposed domain in one. Adding `tty: true` to the docker compose file seems to work well. I'm not sure if there will be any negative concequenses as a result of it.

Just one last thing. Now the use of closed connections is a little more expected, it makes the non-debug server logs a bit too verbose. Is is worth moving these into the debug log?
```
Error writing to writer: read unix /tmp/44.44.44.44:37502:80516713026->@: use of closed network connection
Error trying to write message to socket: EOF
```

**Comment by antoniomika** [comment]
@BenHarris looks like I broke more things than I fixed. Sorry about that 😬. I'll take a look as soon as I can.

**Comment by BenHarris** [comment]
Oops! No worries 😝!

Just a bit more info. I was still finding my connections closing after 60 seconds. That just happened to be the same as my `ServerAliveInterval`. Setting `ServerAliveInterval` to `0`, essentially disabling it stopped this happening. But, again, should probably be handled more gracefully. I believe it sends an EOF, but EOF in this context doesn't mean connection closed.

**Comment by antoniomika** [comment]
@BenHarris any chance we could jump on a mutual chat? I'm unable to reproduce some of the issues you sent and want to make sure I'm attempting them properly! I can be reached on IRC (#sish) and Keybase (@antoniomika) primarily

**Comment by antoniomika** [comment]
@BenHarris newest release has updates for terminal output, formatting, and logs. Give it a try and let me know what issues you're having. I'm gonna leave some long-lived processes running today and will see what's going on.

**Comment by antoniomika** [comment]
@BenHarris after the latest update (v0.0.9) things should be good to go! I also added a new `-sish.logtoclient` flag to actually send HTTP and TCP connections logs to the terminal too. Let me know how it works for you!

**Comment by antoniomika** [comment]
Hey @BenHarris, just looping back on this to see how things are going.

**Comment by BenHarris** [comment]
Hey @antoniomika apologies for the delay, I didn't seem to get an email notification for some reason!!

All working well at my end. Will pop you an email as I don't use IRC or Keybase.

**Comment by BenHarris** [comment]
> @BenHarris after the latest update (v0.0.9) things should be good to go! I also added a new `-sish.logtoclient` flag to actually send HTTP and TCP connections logs to the terminal too. Let me know how it works for you!

Just tested `-sish.logtoclient` out and it works nicely :ok_hand:
