### ISSUE TITLE
Tunnel does not work without ssh session

### ISSUE THREAD

**Issue by broglep-koubachi** [antoniomika/sish#44]
We want to setup a tunnel without the use of ssh session because we don't have a terminal/tty on client side (tunnel started as part of systemd) and pseudo tty seems to be not supported. 

Steps to reproduce

1. Connect via : `ssh -p 2222  -R test:80:localhost:9000 localhost -N`
2. Perform a request HTTP request to `http test.testing.ssi.sh:8081`

Issues we see in light of our requirement:

1. SSHConnection.Messages chan blocks requests.handleRemoteForward if there is no session (chan consumer setup in handleSession)
2. Currently the connection management & architecture of sish relies on the fact that there is a session and as long as it is open, the tunnel is kept open. 

We have the following questions:

1. Does our use case make sense? Would you be willing to add support for it
2. What changes would have to be done to the architecture to support it?
3. How could we help with implementing this (we are rather new new to go)

We have hacked around a bit with the code. By making the messages chan non-blocking and some small other tweaks we could at least get the tunnel to work. But we lack the ability to detect when a ssh connection is closed and then remove it.

**Comment by BenHarris** [comment]
Hey @broglep-koubachi, I believe this is actually the same as my issue #42 

I've done the same as you (probably) and basically commented out the `if err != nil && err == io.EOF {` block in channels.go. It makes it work, but I have the same issue of cleaning up closed connections.

**Comment by antoniomika** [comment]
@BenHarris @broglep-koubachi looks like you're right @BenHarris! Sorry for just getting to you two, currently at KubeCon and things are a bit hectic. I'll take a look when I get some downtime!

**Comment by antoniomika** [comment]
Hey @broglep-koubachi, I have a fix in for your issues (#45) and will be merging that soon. I definitely think your workload is definitely in scope for this project, so I hope this fix works for you!
