### ISSUE TITLE
-sish.http and -sish.https not used in terminal output

### ISSUE THREAD

**Issue by BenHarris** [antoniomika/sish#46]
The following output doesn't seem to honour the `-sish.https=:8443` and `-sish.http=:8080` parameters.
```
HTTP: http://sish-host.com:80
HTTPS: https://sish-host.com:443
```

I was actually looking for a way to remove the port if it uses the default 80/443.

**Comment by antoniomika** [comment]
I'm gonna close this issue in favor of consolidating it for #47!
