### ISSUE TITLE
Improve server-side logging

### ISSUE THREAD

**Issue by BenHarris** [antoniomika/sish#48]
It would be handy if we logged the new connections on the server-side.

Something like `log.Printf("HTTP forwarding started: http://%s:%d -> %s", host, *httpPort, chanListener.Addr().String())` after `requestMessages += fmt.Sprintf("HTTP: http://%s:%d\r\n", host, *httpPort)` on line 129 of requests.go (not sure we need anything extra for HTTPS, but might be useful).

I guess we should also do something similar around the TCP handling a few lines later.

**Comment by antoniomika** [comment]
Just added this, tracking in #42
