### ISSUE TITLE
Nothing is happening after the command "ssh -p 2222 -R 80:localhost:8080 ssi.sh"

### ISSUE THREAD

**Issue by sapgreengem** [antoniomika/sish#49]
I am new to linux and ssh port forwarding. I am using raspbian os for this "sish". Previously I have used SERVEO port forwarding to expose my port. As I found this alternative I tried to use sish.

my docker works well and I also have successfully installed sish according to the instruction. But the command "ssh -p 2222 -R 80:localhost:8080 ssi.sh" gives no response and any output. I am stuck here.

please help me to solve this.

**Comment by antoniomika** [comment]
Hello!

There is no longer an public version of sish available to test because of abuse. It's super easy to setup though.

Sorry for the inconvenience!
