### ISSUE TITLE
Append SSH Username to subdomain

### ISSUE THREAD

**Issue by buffcode** [antoniomika/sish#62]
It would be nice to have the option to append the SSH username to the subdomain.
This way a multi-user team that works on the same project could use the same subdomain and would not get a random hosts assigned.

**Example (current):**
- User Alice wants to expose "project" and receives `project.ssi.sh`
- User Bob wants to expose "project" and receives `52f.ssi.sh`

The next day Bob wakes up early:
- User Bob wants to expose "project" and receives `project.ssi.sh`
- User Alice wants to expose "project" and receives `7km.ssi.sh`

**=> Links / webhooks etc. for both of them are broken**

**Example (proposal):**
- User Alice wants to expose "project" and receives `project-alice.ssi.sh`
- User Bob wants to expose "project" and receives `project-bob.ssi.sh`

This feature would be opt-in per instance and ensures, that a developer does not always need to care of making the hostname unique enough in order to receive a stable hostname. Of course there is no garantuee and the fallback will still generate a random hostname. But this will decrease the likelihood of collisions.

**Comment by antoniomika** [comment]
Hi @buffcode thanks for the issue! I think this could be a cool feature, I'm just trying to think if there is a different use case for the username. I can't really think of a specific place for it, but regardless we could make this feature available behind a flag. Do you have any other thoughts on this?
