### ISSUE TITLE
"Garbage collector" for unused user defined subdomains

### ISSUE THREAD

**Issue by fork04** [antoniomika/sish#65]
Error from the log: "The subdomain foo.bar.com is unavailable. Assigning a random subdomain". 

The subdomain  foo was used earlier and ssh connection was lost, but sish assumes it is still in use.

**Comment by antoniomika** [comment]
Hmm, do you have an example of how to reproduce this? I haven't experienced it myself.

**Comment by fork04** [comment]
I had this case three times on two different machines, but with a new admin panel, who cares ;)

**Comment by antoniomika** [comment]
Heh, fair enough. I think I solved the issue with the latest version on the `admin_features` branch/tag. You can pull the `admin_features` tag from dockerhub to test out the latest stuff. I also updated the console to fix some issues.

**Comment by fork04** [comment]
@antoniomika, I`ve pulled latest image, and now everything  seems to work fine, also gzip works flawlessly.  I think, now remains to refine web templates, and merge the code.

**Comment by antoniomika** [comment]
@fork04 great! I'm glad that's the case! Do you have any recommendations for the web console that I could work on tomorrow/today

**Comment by fork04** [comment]
I think you could organize the appearance of the admin interface a bit, maybe something like that? - https://i.imgur.com/qNWhWYH.png. Maybe also add basicauth on the admin side?

**Comment by antoniomika** [comment]
@fork04 in hopes of keeping PRs small, I'm gonna go ahead and merge in admin changes and close your two issues. I'm gonna create a new issue to track changes we could potentially make for the admin parts now and I'll tag you over there.
