### ISSUE TITLE
Admin console upgrades

### ISSUE THREAD

**Issue by antoniomika** [antoniomika/sish#66]
Now that there are admin features implemented with a basic admin interface, we probably want to make the UI/UX better than it currently is. I'm attaching some screenshots here of what the interface currently looks like:
- The generic admin page listing all connected clients and their respective tunnels. The unix sockets are included, but those are for handling the HTTP(S)/TCP aliasing (which can be disconnected from their respective entries). 
    - The reason we use unix sockets is for allowing other applications running on the server host to interface with connected tunnels in a unix transparent way.

![image](https://user-images.githubusercontent.com/6239308/71484848-7b1ce100-27dc-11ea-8858-150897ab44f2.png)

- The admin panel specifically for HTTP(S) tunnels.

![image](https://user-images.githubusercontent.com/6239308/71485032-43faff80-27dd-11ea-9548-b7fcb83522b2.png)
![image](https://user-images.githubusercontent.com/6239308/71485059-642abe80-27dd-11ea-84b1-8043458e1ae8.png)

**Comment by antoniomika** [comment]
@fork04 Tracking here.

**Comment by fork04** [comment]
If you have more than one tunnel connected to shish, and in the admin panel you change the context to another tunnel, the Routes menu below does not change completely to the selected context.

**Comment by fork04** [comment]
@antoniomika have you had the opportunity to test the web interface based on my comments?

**Comment by antoniomika** [comment]
Hey @fork04,

Was just able to repro what you were saying. Should have a fix in today!

**Comment by fork04** [comment]
@antoniomika - now works great, thx!

**Comment by fork04** [comment]
Home buttons in header aren't dynamically created when authorization string is enabled.

**Comment by antoniomika** [comment]
@fork04 hmm, I'll take a look at this.

**Comment by antoniomika** [comment]
Closing in favor of #85
