### ISSUE TITLE
Access to Admin/Service Console

### ISSUE THREAD

**Issue by ebartz** [antoniomika/sish#68]
Hi there,

thanks for the work that you put into this project!

I just wanted to have a look at the console but actually I can't seem to find any information about how to access it.

I have set these parameters which should hopefully activate it:

```
-sish.adminenabled=true
-sish.admintoken=1234ABCD
-sish.serviceconsoleenabled=true
```

How would I access the console?

I have seen some routes in the code which may imply that it is accessed by adding /_sish/console to the URL. But there I only get an error 404.

Any help is highly appreciated. Thanks

**Comment by antoniomika** [comment]
Hey @ebartz,

Sorry for the late reply! I honestly didn't want to document the consoles yet because they're still more or less not production ready, but here's how to access them.

For the general admin console that lists all connected clients and tunnels, use the following scheme:
```
$rootDomain/_sish/console?x-authorization=$adminToken
```
Where `$rootDomain` is the root of the sish instance (without a subdomain used) and `$adminToken` is the password you set. The service console for each tunnel can be accessed by either the link sent in the initial tunnel info (when you first establish a connection) or via using the subdomain set as the `$rootDomain`

**Comment by Snck3rs** [comment]
I'm not sure if i'm misusing or misunderstanding this feature or if i should create a new issue on that. So correct me if i'm wrong.

Let's pretend the main domain of the service is `example.tld `
The access to the web console of a shared tunnel on e.g. `dev.example.tld` via
- `https://dev.example.tld/_sish/console?x-authorization=$serviceToken`
- `https://dev.example.tld/_sish/console?x-authorization=$adminToken`

both works fine.

But if i want to access the main admin console via `https://example.tld/_sish/console?x-authorization=$adminToken` to see which tunnels are actually open, i just get an error 404.
What am i doing wrong?

Thank you @antoniomika  for this great software and best wishes from germany
Thomas

**Comment by antoniomika** [comment]
Hey @Snck3rs!

Thanks for the kind words! 

The 404 is interesting, that should be the correct route (root/_sish/console?x-authorization=$TOKEN). What are the CLI flags you're using? Maybe one isn't defined.

There's some work I want to do to revamp both the admin and service consoles which should help with this UX as well.

**Comment by Snck3rs** [comment]
Hey @antoniomika thank you for your quick response!

These are the flags i'm using (in docker compose environment)

```
--ssh-address=:2222
--http-address=:80
--https-address=:443
--https=false
--https-certificate-directory=/ssl
--authentication-keys-directory=/pubkeys
--private-keys-directory=/keys
--bind-random-ports=false
--bind-random-subdomains=false
--domain=sub.domain.tld
--admin-console
--admin-console-token="TOKEN"
--service-console
--log-to-client
--idle-connection-timeout=1h
--proxy-ssl-termination
```

P.S. Sounds cool - unfortunately i'm not a go developer, but could assist with testing if you need one. i mainly program in php and have some scripts running in python.

**Comment by antoniomika** [comment]
No problem! And that config looks good at a glance. Just confirming, you're utilizing sub.domain.tld as the root for the URL you're trying?

**Comment by Snck3rs** [comment]
That's right. I'm using a subdomain as root domain for sish. so the shared services are available as sub-sub domains. That works fine - even the service console is working fine under that circumstances.

I'm using traefik as reverse proxy and it handles the ssl certificates as well.

**Comment by antoniomika** [comment]
Hrm, if you try the sish container directly (without traefik) for the admin console (and make sure to set the host properly in the request), does it work? I have some concern that could be the issue or the token has special characters and is incorrect?

**Comment by Snck3rs** [comment]
I don't think there is something wrong with the token itself. if i use the subdomain of the service with the admin token, i can access the console of that particular service. but i'll try a plain testing without traefik to be sure there is no misconfiguration at this side.

**Comment by antoniomika** [comment]
Hey @Snck3rs, just checking in. Were you able to figure it out?
