### ISSUE TITLE
Number of sessions from auth user

### ISSUE THREAD

**Issue by fork04** [antoniomika/sish#69]
Number of allowed sessions from authorized  users -sish.noofallowedsessions
  -sish.auth Whether or not to require auth on the SSH service
  -sish.pkloc string SSH server private key (default "keys/ssh_key")

or allowed sessions per key/named tunnel configured from key file?

**Comment by antoniomika** [comment]
Thanks @fork04! I don't think this is in scope for this project though, so I'm gonna close this issue!
