### ISSUE TITLE
Question: Using sish as a "port forwarding slave"

### ISSUE THREAD

**Issue by IngwiePhoenix** [antoniomika/sish#70]
Hello there!

Due to how my ISP has set up my broadband access, I can not do port-forwarding from my router - or, my type of connection in general. To be honest, I am not exactly sure what is preventing me from port-forwarding...but, I have to do with what I have. :)

That is why I have been looking for a way to expose ports on my local homeserver to my server, to utilize NGINX as a reverse proxy to access them. So, I have a few questions:

1. Can I run sish to forward only HTTP and TCP connections, so that I can NGINX to add my HTTPS certificates ontop?
2. I would like to dedicate the subdomain `home.ingwie.io` to everything related to my homeserver and use subdomains to differenciate between the various things running on it. I am not aware if NGINX has wildcard support in `server_name` though - but, I wouldn't be surprised if it did. That way, I could run another instance of NGINX on my homeserver to handle subdomains (`foo.home.ingwie.io` for instance). What would be the flags I'd have to pass to sish to tell it that `home.ingwie.io` is the main domain to use?
3. Do you know if any way to automate SSH tunnel setup? I am using an older Mac Mini server and I do have a general idea of how to set up `launchd` services to run commands much like `systemd`. What commands would I have to use to bring up a tunnel, shut it down or verify it's status?

I am looking forward to your reply!

Kind regards,
Ingwie

**Comment by antoniomika** [comment]
Hi ingwie,

Yep, sish should work fine for what you are trying to do! Also, nginx does support wildcard server name definitions and can even do SSL offload (if you are interested), but sish has native support for SSL also, so you don't necessarily need the nginx instance infront of it. Here are some more specific answers to your questions:

1. Yes, you can use sish to forward both HTTP(S) and TCP connections. sish has native support for ssl, so you can also just configure sish to use a wildcard cert for what you want. That being said, you can also use nginx. Here's an example to get you started:
```
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

server {
    server_name home.ingwie.io *.home.ingwie.io;

    listen 80;
    listen [::]:80;

    proxy_buffering off;

    location / {
        proxy_pass http://localhost:8081;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_hide_header X-Frame-Options;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}

server {
    server_name home.ingwie.io *.home.ingwie.io;

    ssl_certificate /etc/nginx/certs/home.ingwie.io.crt;
    ssl_certificate_key /etc/nginx/certs/home.ingwie.io.key;

    # dhparams file
    ssl_dhparam /etc/nginx/certs/dhparam.pem;

    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    ssl_protocols TLSv1.2;
    ssl_ciphers "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384";
    ssl_prefer_server_ciphers on;

    proxy_buffering off;

    location / {
        proxy_pass https://localhost:22443;
        proxy_set_header Host $host;
        proxy_redirect http:// https://;
        proxy_http_version 1.1;
        proxy_hide_header X-Frame-Options;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}
```
2. nginx does indeed have support for wildcards, so just take a look at the config I wrote above! You can configure sish to use the domain you want as the root by setting the `-sish.domain` flag to something like `-sish.domain=home.ingwie.io`. 
3. For automating ssh tunneling, I use [autossh](https://www.harding.motd.ca/autossh/) in a docker container with host networking which works great for me. Here's a [gist](https://gist.github.com/lenciel/d353a04a3a7bc0278ec6) I found that pretty much outlines what you're looking to do.

I'd try to eliminate the need for nginx if possible. It doesn't really add anything to sish's functionality because you can route to each service locally if you're just reverse proxying them (i.e. like so):
```bash
ssh -R foo:80:localhost:8080 home.ingwie.io
```
This would forward `foo.home.ingwie.io` on http(s) to localhost:8080. You can provide multiple remote forward ports to nginx also: 
```bash
ssh -R foo:80:localhost:8080 -R foo2:443:localhost:8443 home.ingwie.io
```
I also replaced the `80` to `443` telling sish to connect to the service at localhost:8443 over HTTPS instead of just HTTP. Therefore, if you setup a single autossh tunnel with multiple forwards defined, you can get what you want without having to use nginx on either side if you don't want to.

Hopefully this all helps. Feel free to send me a message over email or IRC or keybase or on this issue. More than happy to help!

**Comment by IngwiePhoenix** [comment]
Thank you very much for the lengthy response!

I mainly use NGINX as a reverse proxy since I have it configured with certbot for Let's Encrypt/ACME and because I found it easy to just manage all the sites I use through `sites-enabled/-disabled` folders, by linking the files across that I want to have enabled and remove those that I do not want to have served. Its really just a poor-man's vhost setup ^^; But hey, it works.

I'll make sure to read the gist! Though I have not heared of autossh before, so I will make sure to check it out. Now all that is left to do is figuring out the proper commands and signals I would need to do to configure `launchd` to start, stop and possibly restart the forwarding. I would imagine that SSH does accept signals like `SIGTERM` and alike to perform actions. I mean, it's basically the old-school way of sending events to processes. Efficient, but it requires some reading.

Again, thank you a lot! I will start to set up my stuff now. :)

Have a great day!

**Comment by antoniomika** [comment]
Yep, no problem! I definitely know `autossh` supports all of those, so make sure you check that out. Feel free to let me know if you have any issues!

**Comment by IngwiePhoenix** [comment]
Just read over the Gist and still thinking about how to best structure this. But I guess I will end up creating a template out of the gist and re-generate it for any port that I would possibly need to have and create individual service entries for each. Also how exactly do I use autossh's monitoring port (`-M`)? Creating multiple services on the same monitoring port might cause issues later on when I want to also tunnel TCP connections.

**Comment by antoniomika** [comment]
You don't actually need to use the monitoring port. You wouldn't want to use a single tunnel for all of the connections?

**Comment by IngwiePhoenix** [comment]
Alright, I am almost set! However, I am having a bit of an issue tunneling a http connection.

First of, I am using Docker Compose:
```
version: "3"
services:
  sish:
    image: antoniomika/sish:latest
    container_name: sish
    #depends_on: 
    #  - letsencrypt
    volumes:
      #- ./letsencrypt:/etc/letsencrypt
      - ./pubkeys:/pubkeys
      - ./keys:/keys
    command: |
      -sish.addr=:9022
      -sish.https=:9443
      -sish.http=:9080
      -sish.httpsenabled=false
      -sish.keysdir=/pubkeys
      -sish.pkloc=/keys/ssh_key
      -sish.bindrandom=false
      -sish.domain=$DOMAIN
      -sish.forcerandomsubdomain=false
    network_mode: host
    restart: always
```

Second, nginx is running on my local maschine's port 80. So, I want to forward my local 80 to sish - which I assume would be 9080? Anyway, I tried this:
```
ingwie@macmini.local /o/s/ingwie.me $ ssh -p 9022 -R 9080:localhost:80 ingwie.io ssi.sh
Warning: remote port forwarding failed for listen port 9080
Press Ctrl-C to close the session.

No forwarding requests sent. Closing connection.
Connection to ingwie.io closed by remote host.
```

I did do an `ufw allow` on that port and I got rid of that error but, no matter which order I do, it won't work ^^;

I might be overlooking something so... have any suggestions?

**Comment by antoniomika** [comment]
So even if your http(s) addr is different (you set it to `9080`), you still use port `80` for the first part of the forward request. The reason for this is sish does different things for http multiplexing in comparison to tcp multiplexing. Give `ssh -p 9022 -R 80:localhost:80 ingwie.io` a try.

**Comment by IngwiePhoenix** [comment]
Oooooooh! That worked! But I also realized I had my domain misconfigured...derp. ^^ Well, while I am waiting for CloudFlare DNS to do it's thing, I'd love to suggest an addition to the documentation:

Make the user aware of the fact that the "destination port" (i.e. 80) is NOT the actual port, but more a "flag" sent to sish to distinguish what exactly is being forwarded.

This is the pitfall I ultimatively fell into :) But this is now exactly what I want. All that is left to set up my `launchd` file(s) and make sure stuff is logged properly. And configure NGINX, of course. But hey, I am exactly where I wanted to be at!

Thank you very much for being so patient with me. Now that I get to _actually_ use it, sish is going to be a huge, huge help for me and my limited internet connection setup. Also, on that note: I am apparently using DOCSIS 3.0, which doesn't just primarily use IPv6 but also a different architecture in general which ends up prohibiting port forwarding in traditional means. Therefore using sish is a very welcome solution for me.

One last question: What options do I have to handle accessing the root domain itself? Like, can I configure one "endpoint" to respond to the root domain? Otherwise I'll just drop in a 404 page for completeness, or return a 503 alltogether. (Or a 420 for the lols :) ).

Again, thank you a lot for your help!

**Comment by antoniomika** [comment]
No problem! And that's really strange regarding the port forwarding stuff. The fact that you're using docsis 3.0 shouldn't really impact port forwarding at all. Only thing I can think of is your ISP is firewalling things upstream. 

I actually have that documented [here](https://github.com/antoniomika/sish#how-it-works) albeit could be a lot more visible, so I'll put that on the backlog to change. Currently for the root domain, the only things you can configure are whether or not to redirect it using the following flags:
```
  -sish.redirectroot
        Whether or not to redirect the root domain (default true)
  -sish.redirectrootlocation string
        Where to redirect the root domain to (default "https://github.com/antoniomika/sish")
```
If this isn't set, the root domain will just 404. Since you're using nginx, you can easily set this to send back whatever you'd like though!

**Comment by IngwiePhoenix** [comment]
Ahh, well the information about the ports seems a little hidden and not too clear. Maybe add a few examples and clarify that no matter what ports are given in the `-sish` options, the `ssi.sh` script only really looks for mappings to port 80 and 443. Also I just forwarded my homeserver's SSH too and it works great. I do get sporadic disconnects - but that is likely due to me currently using raw SSH plus `screen` for testing things out. And now that CloudFlare took care of my DNS, you can see a friendly hello at http://www.ingwie.me :). Im probably just going to set `-sish.redirectrootlocation www.ingwie.me`. A little bit backwards to what you'd usually do but...it works, I guess.

Anyway. Things are working as expected now and I can now start playing around with my homeserver being actually accessible to the public! This is really awesome and will be a lot of fun to test with. I mean, it may just be a 2007 Mac Mini, but it can still provide some stuff nevertheless. I'm gonna enjoy this - a lot. :)

**Comment by IngwiePhoenix** [comment]
In addition, here is the `launchd` file I ended up using:

```plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>KeepAlive</key>
  <true/>
  <key>Label</key>
  <string>homebrew.autossh.sish.http</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>AUTOSSH_LOG</key>
    <string>/opt/logs/autossh.sish.http.log</string>
  </dict>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/local/bin/autossh</string>
    <string>-M</string>
    <string>30001</string>
    <string>-i</string>
    <string>/Users/Ingwie/.ssh/id_rsa</string>
    <string>-p</string>
    <string>9022</string>
    <string>-R</string>
    <string>www:80:localhost:80</string>
    <string>root@ingwie.io</string>
    <string>ssi.sh</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>WorkingDirectory</key>
  <string>/Users/Ingwie</string>
  <key>StandardErrorPath</key>
  <string>/opt/logs/autossh.sish.http.stderr.log</string>
</dict>
</plist>
```

Additional options would be to set `StandardOutputPath` and using `AUTOSSH_DEBUG` to have it be chatty - OR to use `-v` in the command. But now I have them (one for ssh, one for http) registered. I can now just use this as a template if I have a different service I want to hook up :)

Maybe you can take some use out of this!
