### ISSUE TITLE
Unclean disconnect leaves reserved subdomain still active

### ISSUE THREAD

**Issue by IngwiePhoenix** [antoniomika/sish#71]
Hey!

I just had a power outage - it was only short - and my Mac Mini server rebooted on it's own afterwards as I had configured it to do. When it reconnected, I noticed that connecting to my "usual" domain did yield a 502 error, while the SSH tunnel worked just fine.

As it turns out, while inspecting the logs both on sish and the launch daemon, I noticed that sish kept reporting that `www.ingwie.me was unavailable`. Well, that _should_ not have been true. The server was disconnected by force and somehow, the tunnel just stuck around. Accessing the tunnel showed that it tried to talk to a unix socket that was pretty much dead as the original connection had been broken, at this point. Just restarting the Docker container fixed it and my launch daemon reconnected - and this time with the actual domain - just fine.

Is it possible to introduce an option that purges a subdomain when a new connection with the same name is established? Or do you have  a different idea on how to tell sish to drop the dead socket so the related domain can be used again?

Kind regards,
Ingwie

**Comment by antoniomika** [comment]
Oh interesting, I thought I had previously fixed this. I'll see if I can reproduce anything

**Comment by antoniomika** [comment]
@IngwiePhoenix I have a potentially fix up in the PR at #72. If you could give that a try (use the docker image `antoniomika/sish:540d70f3c3d06acc28af2d1980bc1a0b237662be`), that should fix it. You can also change the ping interval (`-sish.pinginterval`) to change it from the default of 10 seconds also.

**Comment by antoniomika** [comment]
@IngwiePhoenix I merged my changes after my testing worked well. Feel free to repull the latest image to see if that works.
