### ISSUE TITLE
Use sish without docker

### ISSUE THREAD

**Issue by Varooneh** [antoniomika/sish#77]
Hi Antoni,

I'm not familiar with go and docker. Can you help me how to run sish without docker on *nix or windows?

Thank you.

**Comment by xtream1101** [comment]
Download a release from https://github.com/antoniomika/sish/releases for your OS, then extract it and there should be an executable file that you run with your command line args like `./sish -sish.addr=:2222 -sish.http=:80` ....

**Comment by neomvll** [comment]
ok,
I want use sish on my raspberry to expose a site runing on localhost:8080.
I downloaded last release from here https://github.com/antoniomika/sish/releases/download/v0.4.0/sish-0.4.0.linux-armv6.tar.gz, extract and trying a command like:
sudo ./sish -sish.addr=:8080 -sish.http=:80 -sish.domain=my-hass-test.ssi.sh
But, I getting this:
2020/02/22 21:32:47 Starting SSH service on address: :8080
2020/02/22 21:32:47 Generated RSA Keypair
2020/02/22 21:32:47 Error writing to file: open keys/ssh_key: no such file or directory
2020/02/22 21:32:47 listen tcp :8080: bind: address already in use

So, can you help me pls?

**Comment by xtream1101** [comment]
@neomvll This is about running the server, what you seem to be looking for is on the client side.

You would want to run `ssh -p 2222 -R 80:localhost:8080 your-sish-server.com` on your raspberry pi.

**Comment by antoniomika** [comment]
Thanks for the help @xtream1101! Gonna close this issue now. Feel free to open it again if you have any other questions!

**Comment by Cvar1984** [comment]
> Download a release from https://github.com/antoniomika/sish/releases for your OS, then extract it and there should be an executable file that you run with your command line args like `./sish -sish.addr=:2222 -sish.http=:80` ....

Hi there, can you make it for aarch64 ?

**Comment by antoniomika** [comment]
@Cvar1984 should be able to! I'll add that to #85

**Comment by deadcoder0904** [comment]
I tried @xtream1101's solution `.\sish.exe -sish.addr=:8000 -sish.http=:80` on Windows 10 but couldn't get it to work. I got an error:

> 2020/05/17 - 20:32:13 | open deploy/pubkeys/: The system cannot find the path specified.

I used [Serveo](https://serveo.net/) & this worked for me `ssh -R 80:localhost:3000 serveo.net` perfectly.

Any suggestions @antoniomika on how to install without Docker?

**Comment by antoniomika** [comment]
@deadcoder0904 you need to configure the sish paths to be windows paths. This requires setting up your own service, there isn't one publicly available.

**Comment by deadcoder0904** [comment]
Any guides? @antoniomika I am new to setting this up stuff

**Comment by antoniomika** [comment]
@deadcoder0904 take a look at the readme and look at the file paths. These flags
```
 -sish.keysdir string
        Directory for public keys for pubkey auth (default "pubkeys/")
```

Need to be updated to locations of folders that exist. I think in the windows download they should exist there, but you need to set it so they use Windows file paths `\` instead of `/`
