### ISSUE TITLE
Add X-Forwarded-Proto

### ISSUE THREAD

**Issue by Mika56** [antoniomika/sish#8]
Hello,

When Sish is accessed on the HTTPs port, the `X-Forwarded-Proto: https` header should be added to the request to the upstream server.
This allows the upstream server to know that the connection is secured with HTTPs, even if the last connection (from Sish to upstream) is not.

**Comment by antoniomika** [comment]
This should now be solved with d4bd84c! Let me know if you have any other questions!

**Comment by Mika56** [comment]
Tested and working 👍 
Thank you!
