### ISSUE TITLE
Consider removing sish prefixes from flags

### ISSUE THREAD

**Issue by shinenelson** [antoniomika/sish#81]
I don't understand why the flags have the `sish` keyword as a prefix. It seems to be redundant considering the binary is also called `sish`. This would add unnecessary extra types when typing in flags and arguments.

**Comment by antoniomika** [comment]
To be honest, this was just force of habit when adding the command flags. Modifying them would definitely be a breaking change and require a major revision update. That would probably be the only reason to keep this as-is. Happy to turn this into an RFC if anyone feels particularly strongly about this.

**Comment by tuarrep** [comment]
I agree with @shinenelson.
Perhaps giving a try to replace the `flag` package by spf13/pflag which seems to be a drop-in replacement but offers flag aliases and depracations (https://github.com/spf13/pflag/blob/master/README.md#mutating-or-normalizing-flag-names)

**Comment by antoniomika** [comment]
@tuarrep that's not a bad idea! I'm gonna track this issue in #85 and close this one. The plan right now is to use cobra and pull a 1.0.0 release once all of those milestones are completed.
