### ISSUE TITLE
Not Working-just commit info in logs

### ISSUE THREAD

**Issue by capriciousduck** [antoniomika/sish#87]
It is not working.

When I execute  ` ssh -p 2222 -R sync:80:localhost:8384 capcloud.live`

I get not. When I check logs I see.....

`Date: 2020-05-03T03:22:51Z
Version: v1.0.0-rc
Commit: 93028414cc94378b0d9177199608efce3090577d
Date: 2020-05-03T03:22:51Z
Version: v1.0.0-rc
Commit: 93028414cc94378b0d9177199608efce3090577d
Date: 2020-05-03T03:22:51Z
Version: v1.0.0-rc
Commit: 93028414cc94378b0d9177199608efce3090577d
Date: 2020-05-03T03:22:51Z`

**Comment by capriciousduck** [comment]
Here is the docker command I used.

```
docker run -d --name sish --restart unless-stopped \
  --net=host antoniomika/sish:latest \
   -v ~/sish/ssl:/ssl \
   -v ~/sish/keys:/keys \
   -v ~/sish/pubkeys:/pubkeys \
  -sish.addr=:2222 \
  -sish.http=:80 \
  -sish.httpsenabled=false \
  -sish.bindrandom=true \
  -sish.auth=true \
  -sish.password=duckisgood \
  -sish.forcerandomsubdomain=false \
 -sish.domain=capcloud.live
```

**Comment by antoniomika** [comment]
@capriciousduck you're using v1.0.0 with the old flags. New ones can be found in the readme on that branch.

**Comment by capriciousduck** [comment]
I am getting an error at the flag "--authentication" . And how do I process if the server on which SISH is being installed is access with a root password(I do not use ssh keys to log in to my sish server).

**Comment by capriciousduck** [comment]
Could you please give the exact command ? I want only HTTP and with a text as a password?

The flags are bit tricky(for me). I couldn't understand.

And is it possible to use your previous app instead?

**Comment by antoniomika** [comment]
@capriciousduck you could use the previous app by using the `v0.4.0` docker tag. A command using ssh password auth would look like this:
```bash
docker run -d --name sish \
  --restart unless-stopped \
  -v ~/sish/ssl:/ssl \
  -v ~/sish/keys:/keys \
  -v ~/sish/pubkeys:/pubkeys \
  --net=host antoniomika/sish:latest \
  --ssh-address=:2222 \
  --http-address=:80 \
  --https=false \
  --authentication=true \
  --authentication-password="Here is your password" \
  --private-key-location=/keys/ssh_key \
  --bind-random-ports=true \
  --bind-random-subdomains=false \
  --domain=capcloud.live
```

**Comment by capriciousduck** [comment]
I am getting the following error: 

`2020/05/21 06:46:31 unable to execute root command: unknown flag: --https`

**Comment by capriciousduck** [comment]
If I remove the https flag and recreate the container, I get:

'2020/05/21 06:53:15 unable to execute root command: unknown flag: --authentication'

**Comment by antoniomika** [comment]
Now it sounds like you're using the old version of sish. Change the image to antoniomika/sish:v1.0-work

**Comment by capriciousduck** [comment]
I did a bit of edit and managed to create the container. However, I get issues with the private key format.

`docker run -d --name sish \
  --restart unless-stopped \
  -v ~/sish/ssl:/ssl \
  -v ~/sish/keys:/keys \
  -v ~/sish/pubkeys:/pubkeys \
  --net=host antoniomika/sish:latest \
  --ssh-address=:2222 \
  --http-address=:80 \
  --enable-https=false \
  --enable-authentication=true \
  --authentication-password=docker run -d --name sish \
  --restart unless-stopped \
  -v ~/sish/ssl:/ssl \
  -v ~/sish/keys:/keys \
  -v ~/sish/pubkeys:/pubkeys \
  --net=host antoniomika/sish:latest \
  --ssh-address=:2222 \
  --http-address=:80 \
  --enable-https=false \
  --enable-authentication=true \
  --authentication-password=xxxx \
  --private-key-location=/keys/ssh_key \
  --bind-random-ports=true \
  --bind-random-subdomains=false \
  --domain=capcloud.live \
  --private-key-location=/keys/ssh_key \
  --bind-random-ports=true \
  --bind-random-subdomains=false \
  --domain=capcloud.live`


I get the following error after the edit:

`2020/05/21 - 06:57:57 | Starting SSH service on address: :2222
2020/05/21 - 06:57:57 | ssh: invalid openssh private key format
2020/05/21 - 06:57:58 | Starting SSH service on address: :2222
2020/05/21 - 06:57:58 | ssh: invalid openssh private key format
2020/05/21 - 06:57:58 | Starting SSH service on address: :2222
2020/05/21 - 06:57:58 | ssh: invalid openssh private key format
2020/05/21 - 06:57:59 | Starting SSH service on address: :2222
2020/05/21 - 06:57:59 | ssh: invalid openssh private key format
2020/05/21 - 06:58:00 | Starting SSH service on address: :2222
2020/05/21 - 06:58:00 | ssh: invalid openssh private key format`

**Comment by capriciousduck** [comment]
Still get the error even after using the v1.0-work

`2020/05/21 - 07:02:15 | Starting SSH service on address: :2222
2020/05/21 - 07:02:15 | ssh: invalid openssh private key format
2020/05/21 - 07:02:16 | Starting SSH service on address: :2222
2020/05/21 - 07:02:16 | ssh: invalid openssh private key format
2020/05/21 - 07:02:16 | Starting SSH service on address: :2222
2020/05/21 - 07:02:16 | ssh: invalid openssh private key format
2020/05/21 - 07:02:17 | Starting SSH service on address: :2222
2020/05/21 - 07:02:17 | ssh: invalid openssh private key format
2020/05/21 - 07:02:19 | Starting SSH service on address: :2222
2020/05/21 - 07:02:19 | ssh: invalid openssh private key format
2020/05/21 - 07:02:21 | Starting SSH service on address: :2222
2020/05/21 - 07:02:21 | ssh: invalid openssh private key format`

**Comment by capriciousduck** [comment]
Do I use the old app instead?

**Comment by antoniomika** [comment]
You could use the old app, but from the error above it looks like the file setting for the private_key_location is likely incorrect. You can try removing that for now.

**Comment by capriciousduck** [comment]
After removing the private key location... I get few more errors. Anyways, I'll switch to the old app.

`2020/05/21 - 07:27:15 | Starting SSH service on address: :2222
2020/05/21 - 07:27:15 | Generated RSA Keypair
2020/05/21 - 07:27:15 | Error writing to file: open deploy/keys/ssh_key: no such file or directory
2020/05/21 - 07:27:15 | ssh: invalid openssh private key format
2020/05/21 - 07:27:16 | Starting SSH service on address: :2222
2020/05/21 - 07:27:16 | Generated RSA Keypair
2020/05/21 - 07:27:16 | Error writing to file: open deploy/keys/ssh_key: no such file or directory
2020/05/21 - 07:27:16 | ssh: invalid openssh private key format
2020/05/21 - 07:27:17 | Starting SSH service on address: :2222
2020/05/21 - 07:27:17 | Generated RSA Keypair
2020/05/21 - 07:27:17 | Error writing to file: open deploy/keys/ssh_key: no such file or directory
2020/05/21 - 07:27:17 | ssh: invalid openssh private key format
2020/05/21 - 07:27:18 | Starting SSH service on address: :2222
2020/05/21 - 07:27:18 | Generated RSA Keypair
2020/05/21 - 07:27:18 | Error writing to file: open deploy/keys/ssh_key: no such file or directory
2020/05/21 - 07:27:18 | ssh: invalid openssh private key format
2020/05/21 - 07:27:19 | Starting SSH service on address: :2222
2020/05/21 - 07:27:19 | Generated RSA Keypair
2020/05/21 - 07:27:19 | Error writing to file: open deploy/keys/ssh_key: no such file or directory
2020/05/21 - 07:27:19 | ssh: invalid openssh private key format
2020/05/21 - 07:27:21 | Starting SSH service on address: :2222
2020/05/21 - 07:27:21 | Generated RSA Keypair
2020/05/21 - 07:27:21 | Error writing to file: open deploy/keys/ssh_key: no such file or directory
2020/05/21 - 07:27:21 | ssh: invalid openssh private key format
2020/05/21 - 07:27:25 | Starting SSH service on address: :2222
2020/05/21 - 07:27:25 | Generated RSA Keypair
2020/05/21 - 07:27:25 | Error writing to file: open deploy/keys/ssh_key: no such file or directory
2020/05/21 - 07:27:25 | ssh: invalid openssh private key format`

**Comment by capriciousduck** [comment]
Using the v0.4.0 tag, I get...

`Error writing to file: open keys/ssh_key: no such file or directory`

sorry to annoy you like this. I've very limited knowledge related to ssh.

**Comment by antoniomika** [comment]
This is because the `keys` directory doesn't exist in the container. Make sure you added the volume bind so that sish can create the ssh host key.
