### ISSUE TITLE
Colab

### ISSUE THREAD

**Issue by capriciousduck** [antoniomika/sish#89]
I am trying to create a tunnel from google colab. I installed vnc and xfce4 in the colab and trying to create a tunnel with ssh for vnc access. I am getting the "host key verification failed" error. Do you have any idea about this?

**Comment by antoniomika** [comment]
I do not and I actually won't provide help for this use case because I personally do not condone it. Colab is a free service that makes data scientists' lives much easier and this does not sound like an appropriate use case for the tool.
