### ISSUE TITLE
Http request timeout over tunel

### ISSUE THREAD

**Issue by brzezinol** [antoniomika/sish#91]
Hi, I looking for some timeout configuration param, which is responsible for http request timeout over tunnel.
I encounter problem with sending request through sish tunnel, when api server not respond in 8s, SISH returns http 502 Bad Gateway to request client, but server is still processing that request.

**Comment by antoniomika** [comment]
If you're using the older version of sish, the flag is `-sish.idletimeout`. The readme includes information for those
