### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by capriciousduck** [antoniomika/sish#93]
I see there were many updates to your app. Do I need to re-create my docker container to have any updated version?

**Comment by capriciousduck** [comment]
And I'm thinking to use the latest one. Which tag should I use? latest or v1.0-work?

**Comment by antoniomika** [comment]
yes, the docker container needs to be updated and the command flags also need to be updated. Since v1.0 is now released, it is accessible with the latest docker tag.

**Comment by capriciousduck** [comment]
I see that `--bind-random-subdomains` is, by default, set to true. Does that mean that even if I did provide a desired one, I will not get the desired one? This is somewhat forcing, right?

**Comment by capriciousduck** [comment]
Oh man, I am again getting the errors. Though, I am using the latest image. I deleted the old image with the v0.4.0 tag.

This is the error:
`2020/06/07 - 16:00:05 | Starting SSH service on address: :2222
2020/06/07 - 16:00:05 | Error loading private key, generating a new one: open /keys/ssh_key: no such file or directory
2020/06/07 - 16:00:05 | Generated ED25519 Keypair`

**Comment by antoniomika** [comment]
Correct, this would force any connecting client to receive a random subdomain. For the defaults, I tried to go with "sane+safe" as the main driving factor. In you don't want that setting, you can just set it to false when you start sish.

**Comment by antoniomika** [comment]
It looks like you need to update the data directory paths that you volume mount and pass to sish.

**Comment by capriciousduck** [comment]
I just deleted the old directory while creating the new container. So, I think the error is not because of them.

**Comment by antoniomika** [comment]
I see. That error above shouldn't have prevented the application from starting. Are there other issues?

**Comment by capriciousduck** [comment]
I am using the following command:

`docker run -d --name SISH \
  --restart unless-stopped \
  -v /mnt/systemdisk/sish/ssl:/ssl \
  -v /mnt/systemdisk/sish/keys:/keys \
  -v /mnt/systemdisk/sish/pubkeys:/pubkeys \
  --net=host antoniomika/sish:latest \
  --ssh-address=:2222 \
  --http-address=:80 \
  --https=false \
  --authentication=true \
  --authentication-password=mypass \
  --private-key-location=/keys/ssh_key \
  --bind-random-ports=false \
  --bind-random-subdomains=false \
  --domain=mydomain.tld`

**Comment by capriciousduck** [comment]
I get the following when I try to create a new connection:

`ssh -p 2222 -R sync:80:localhost:8384 mydomain.tld`

And here are sish logs:
`docker logs sish
2020/06/07 - 16:00:05 | Starting SSH service on address: :2222
2020/06/07 - 16:00:05 | Error loading private key, generating a new one: open /keys/ssh_key: no such file or directory
2020/06/07 - 16:00:05 | Generated ED25519 Keypair
2020/06/07 - 16:02:19 | Starting SSH service on address: :2222
2020/06/07 - 16:02:55 | Accepted SSH connection for: 59.88.206.75:51436
2020/06/07 - 16:03:00 | read tcp 45.148.29.149:2222->59.88.206.75:51436: use of closed network connection
2020/06/07 - 16:03:12 | Accepted SSH connection for: 59.88.206.75:51438
2020/06/07 - 16:03:17 | read tcp 45.148.29.149:2222->59.88.206.75:51438: use of closed network connection
2020/06/07 - 16:09:01 | Starting SSH service on address: :2222
2020/06/07 - 16:09:18 | Accepted SSH connection for: 59.88.206.75:51528
2020/06/07 - 16:09:23 | read tcp 45.148.29.149:2222->59.88.206.75:51528: use of closed network connection`

**Comment by capriciousduck** [comment]
What do I do now?

**Comment by antoniomika** [comment]
What is the output from the ssh client? Can you add `-vvv` to your ssh command to show verbose output?

**Comment by capriciousduck** [comment]
I'm very sorry. I just switched to the older app(v0.4.0) to avoid headaches as I have no errors while using it.

**Comment by antoniomika** [comment]
That's fine. Not sure where that error is coming from. Gonna close this issue.
