### ISSUE TITLE
Idea: support dynamic key management

### ISSUE THREAD

**Issue by gucki** [antoniomika/sish#95]
When adding/ removing/ updating keys (authentication-keys-directory) a restart of the service is required. This causes a disruption of service for all current users. Instead the changes should be picked up without a restart.

**Comment by antoniomika** [comment]
@gucki this is already implemented and should just work. What does your deployment setup look like?

**Comment by gucki** [comment]
Right, just tested different scenarios (add, remove, edit) again it works. :+1:
