### ISSUE TITLE
Possible bug: ssh client with option "-N" causes server to behave weird

### ISSUE THREAD

**Issue by gucki** [antoniomika/sish#96]
When running the ssh client with option "-N" (don't execute remote command) the server shows a "weird" behavior, like not really establishing a connection to the client for incomming requests and thus showing a bad gateway. From the logs it seems the "setup" process of new connections is not fully completed.

**Comment by antoniomika** [comment]
Hmm, I think this is an issue with sending a message to the underlying SSH connection which is technically blocking. I have an idea of where I can find this.
