### ISSUE TITLE
already in use for ssh port

### ISSUE THREAD

**Issue by etheaven** [antoniomika/sish#99]
Hey, trying out sish, selfhosted, my server already runs ssh - obviously at port 22, I can't disable it otherwise it would cut me off, what is the correct approach to this to be able to use sish?
Log repeatedly doing this:

```
sish           | 2020/06/13 - 22:15:06 | [INFO][cache:0xc000074410] Started certificate maintenance routine
sish           | 2020/06/13 - 22:15:06 | listen tcp :22: bind: address already in use

```

**Comment by antoniomika** [comment]
@etheaven howdy!

I recommend running it either on a port other than `22` or running ssh on a port other than 22.

**Comment by etheaven** [comment]
Guess there was no other way. Solved by making ssh default to 2222 as is in config example.
